// RLCP1_COSE_ESP256 (m1-completion/03-signing.md) tests: the fixture below is
// an INDEPENDENTLY generated P-256 signature (Python cryptography, ECDSA over
// the exact Sig_structure bytes) — not produced by the code under test.

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

#include "routeloom/config_cose.hpp"
#include "routeloom/config_dev.hpp"
#include "routeloom/endpoint_wire.hpp"

namespace {

int failures = 0;
#define CHECK(expr) do { if (!(expr)) { std::fprintf(stderr, "CHECK failed %s:%d: %s\n", __FILE__, __LINE__, #expr); ++failures; } } while (false)
#define CHECK_OK(expr) do { const auto _status = (expr); if (!_status.ok()) { std::fprintf(stderr, "STATUS failed %s:%d: %s (%s)\n", __FILE__, __LINE__, #expr, _status.detail); ++failures; } } while (false)

using namespace routeloom;

// Generated by tools-independent Python cryptography — P-256 X||Y.
constexpr std::uint64_t kAuthorityId = 0xA17;
constexpr std::array<std::uint8_t, 64> kPubkey{{
    0x84,0xa9,0xd1,0x36,0x38,0xf7,0x47,0xd1,0xf4,0x24,0x89,0xb3,0xf7,0x23,0x91,0x54,
    0x6b,0xd2,0x58,0x27,0xab,0x15,0x63,0x2d,0x99,0x34,0x79,0x09,0x7b,0xed,0xe6,0x14,
    0xcf,0xe6,0x25,0x0b,0x3b,0x5d,0x86,0xa7,0xde,0x24,0xe6,0x8a,0xab,0x02,0x11,0xcf,
    0x51,0x54,0xbc,0xec,0xa2,0x79,0x47,0xa5,0x4c,0x45,0xfa,0x14,0xba,0x82,0x0f,0xc0}};

constexpr char kPermitHex[] =
    "d2844da2012804480000000000000a17a058b65243433101000001000100010000000000"
    "00000700000000000000c30000000000000a170000000100000000000000053031323334"
    "35363738393a3b3c3d3e3f00000000000000040000000000000005000102030405060708"
    "090a0b0c0d0e0f101112131415161718191a1b1c1d1e1fa0a1a2a3a4a5a6a7a8a9aaabacad"
    "aeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf000000000000b007c0c1c2c3c4c5c6c7c8c9"
    "cacbcccdcecf000075300006000000020200012a5840dfa9f29837c472991637187c21fe"
    "a5d59082795d29a07ff9929f8f8b2c7605f122494d5ef92a75c64ee55da028f1ce4d0a18"
    "b80c28dfad1b582b928def5a4781";

std::vector<std::uint8_t> unhex(const char* hex) {
  std::vector<std::uint8_t> out;
  for (const char* p = hex; p[0] && p[1]; p += 2) {
    auto nib = [](char c) -> std::uint8_t {
      if (c >= '0' && c <= '9') return static_cast<std::uint8_t>(c - '0');
      if (c >= 'a' && c <= 'f') return static_cast<std::uint8_t>(c - 'a' + 10);
      return static_cast<std::uint8_t>(c - 'A' + 10);
    };
    out.push_back(static_cast<std::uint8_t>(nib(p[0]) * 16 + nib(p[1])));
  }
  return out;
}

ConfigPermitContext context() {
  ConfigPermitContext ctx{};
  ctx.network = 7;
  ctx.target = 0xC3;
  ctx.config_namespace = endpoint::kConfigNamespaceSdk;
  ctx.authorized_issuer = kAuthorityId;
  ctx.authority_generation = 1;
  return ctx;
}

// Independent RCR2 fixture (same methodology as the permit: fresh P-256
// keypair, Python cryptography ECDSA over the exact Sig_structure bytes
// with the recovery-domain external AAD — not produced by this code).
// Reprovision intent, J=4/R=2, snapshot {f1:1, f3:true}.
constexpr std::uint64_t kRecoveryAuthorityId = 0xB2D;
constexpr std::array<std::uint8_t, 64> kRecoveryPubkey{{
    0xe7,0xd5,0x44,0x28,0xcc,0x91,0xe3,0xc7,0xe4,0xfd,0x46,0xc3,0x74,0x72,0x54,0x04,
    0x07,0x4f,0x8b,0x45,0x21,0x42,0x16,0xc4,0xc1,0xf5,0x5a,0xa7,0x0c,0xb0,0xa6,0x13,
    0xad,0x2a,0x77,0xe0,0x4b,0x5c,0xc6,0x33,0x4e,0x65,0x03,0x4c,0x62,0x7c,0x81,0x9f,
    0xd5,0xa1,0x80,0x88,0x96,0x05,0x95,0xc9,0x5f,0x7f,0xbb,0x85,0x26,0x76,0x7c,0x53}};

constexpr char kRecoveryHex[] =
    "d2844da2012804480000000000000b2da0587c52435232020100010001000000"
    "0000000000000700000000000000c30000000000000b2d000000010000000000"
    "00002c303132333435363738393a3b3c3d3e3f00000004000000000000000200"
    "0c0000fbc39ede56d10cd10c15972b8a6e2e4a7b139e156957178e5ebad0639e"
    "c7054d0001020001010003010001015840c712c3b4be4ed151a782b255a7873f"
    "70e0783ac41ee707b08ee526c9b34b1bfd751fb365653416bd176e47ca1490aa"
    "634a2cb6ee247b398ac798cc99a9c70871";

struct RecoveryFixture {
  CoseEsp256AuthorityVerifier verifier;
  std::vector<std::uint8_t> object{unhex(kRecoveryHex)};
  RecoveryFixture() {
    verifier.provision(kRecoveryAuthorityId,
                       ByteView{kRecoveryPubkey.data(), kRecoveryPubkey.size()});
  }
};

ConfigPermitContext recovery_context() {
  ConfigPermitContext ctx = context();
  ctx.authorized_issuer = kRecoveryAuthorityId;
  return ctx;
}

struct Fixture {
  CoseEsp256AuthorityVerifier verifier;
  std::vector<std::uint8_t> permit{unhex(kPermitHex)};
  Fixture() {
    verifier.provision(kAuthorityId,
                       ByteView{kPubkey.data(), kPubkey.size()});
  }
};

void test_cose_permit_valid() {
  Fixture f;
  CHECK(f.verifier.ready());
  CHECK(f.verifier.security_profile() == SecurityProfile::Production);
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;
  CHECK_OK(f.verifier.verify_permit(context(),
                                    ByteView{f.permit.data(), f.permit.size()},
                                    payload, verified));
  CHECK(verified);
  CHECK(payload.size == 182);  // RCC1 header 176 + one 6-byte field TLV
  // The decoded payload is the real RCC1 command bound to the context.
  endpoint::ConfigCommand cmd{};
  CHECK_OK(endpoint::config_command_decode(payload.view(), cmd));
  CHECK(cmd.network == 7 && cmd.target == 0xC3 && cmd.authority == kAuthorityId);
  CHECK(cmd.next_revision == 5 && cmd.field_count == 1);
}

void test_cose_permit_denied_variants() {
  Fixture f;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;

  // Tampered payload byte (inside RCC1 body) — signature no longer covers it.
  {
    auto tampered = f.permit;
    tampered[40] ^= 0x01;
    CHECK_OK(f.verifier.verify_permit(
        context(), ByteView{tampered.data(), tampered.size()}, payload,
        verified));
    CHECK(!verified);
  }
  // Tampered signature.
  {
    auto tampered = f.permit;
    tampered[tampered.size() - 10] ^= 0x80;
    CHECK_OK(f.verifier.verify_permit(
        context(), ByteView{tampered.data(), tampered.size()}, payload,
        verified));
    CHECK(!verified);
  }
  // Wrong kid in protected header — a different claimed authority.
  {
    auto tampered = f.permit;
    tampered[12] ^= 0x01;  // last kid byte
    CHECK_OK(f.verifier.verify_permit(
        context(), ByteView{tampered.data(), tampered.size()}, payload,
        verified));
    CHECK(!verified);
  }
  // Context mismatch: wrong target node.
  {
    auto ctx = context();
    ctx.target = 0x999;
    CHECK_OK(f.verifier.verify_permit(
        ctx, ByteView{f.permit.data(), f.permit.size()}, payload, verified));
    CHECK(!verified);
  }
  // Context mismatch: wrong authorized issuer (kid != authorized_issuer).
  {
    auto ctx = context();
    ctx.authorized_issuer = 0xB0B;
    CHECK_OK(f.verifier.verify_permit(
        ctx, ByteView{f.permit.data(), f.permit.size()}, payload, verified));
    CHECK(!verified);
  }
  // Context mismatch: wrong authority generation (RCC1 carries generation=1).
  {
    auto ctx = context();
    ctx.authority_generation = 9;
    CHECK_OK(f.verifier.verify_permit(
        ctx, ByteView{f.permit.data(), f.permit.size()}, payload, verified));
    CHECK(!verified);
  }
}

void test_cose_permit_malformed() {
  Fixture f;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;

  // Errors (malformed envelopes), not silent denials:
  auto expect_error = [&](std::vector<std::uint8_t> mutated) {
    verified = true;
    const Status s = f.verifier.verify_permit(
        context(), ByteView{mutated.data(), mutated.size()}, payload, verified);
    CHECK(!s.ok());
    CHECK(!verified);
  };
  { auto m = f.permit; m[0] = 0xD3; expect_error(m); }      // wrong tag
  { auto m = f.permit; m[1] = 0x83; expect_error(m); }      // array(3)
  { auto m = f.permit; m[2] = 0x58; expect_error(m); }      // non-minimal bstr
  { auto m = f.permit; m[2] = 0x5F; expect_error(m); }      // indefinite bstr
  { auto m = f.permit; m[3] = 0xA3; expect_error(m); }      // protected map3
  { auto m = f.permit; m[4] = 0x07; expect_error(m); }      // alg=+7 not -9
  { auto m = f.permit; m[17] = 0xA1; expect_error(m); }     // unprotected nonempty
  { auto m = f.permit; m.push_back(0x00); expect_error(m); }// trailing byte
  { auto m = f.permit; m.pop_back(); expect_error(m); }     // truncated sig
  { auto m = f.permit; m.resize(10); expect_error(m); }     // floor bound
}

void test_cose_permit_signature_bounds() {
  Fixture f;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;
  const std::size_t sig_off = f.permit.size() - 64;  // R||S inside last bstr

  // S flipped high-S (s -> n - s): canonicality rule rejects it.
  {
    auto m = f.permit;
    // n - s mod encoding: flip top bit of S keeps magnitude high but < n.
    m[sig_off + 32] ^= 0x80;
    const Status s = f.verifier.verify_permit(
        context(), ByteView{m.data(), m.size()}, payload, verified);
    // High-S or wrong value — denied either way; never an error.
    CHECK(s.ok() && !verified);
  }
  // R = 0 → denied.
  {
    auto m = f.permit;
    std::memset(m.data() + sig_off, 0, 32);
    const Status s = f.verifier.verify_permit(
        context(), ByteView{m.data(), m.size()}, payload, verified);
    CHECK(s.ok() && !verified);
  }
  // S = n (out of range) → denied.
  {
    auto m = f.permit;
    std::memcpy(m.data() + sig_off + 32, kSecp256r1Order.data(), 32);
    const Status s = f.verifier.verify_permit(
        context(), ByteView{m.data(), m.size()}, payload, verified);
    CHECK(s.ok() && !verified);
  }
}

void test_cose_provisioning() {
  CoseEsp256AuthorityVerifier v;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;
  // Unprovisioned verifier fails closed with an error, not a verdict.
  const std::vector<std::uint8_t> permit = unhex(kPermitHex);
  CHECK(!v.ready());
  CHECK(!v.verify_permit(context(), ByteView{permit.data(), permit.size()},
                         payload, verified)
             .ok());

  // Off-curve / invalid public key is refused at provisioning time.
  std::array<std::uint8_t, 64> bad_key{};
  std::memset(bad_key.data(), 0xAA, bad_key.size());
  v.provision(kAuthorityId, ByteView{bad_key.data(), bad_key.size()});
  CHECK(!v.ready());

  // Wrong size is refused too.
  v.provision(kAuthorityId, ByteView{kPubkey.data(), 32});
  CHECK(!v.ready());

  // Valid key provisions and verifies.
  v.provision(kAuthorityId, ByteView{kPubkey.data(), kPubkey.size()});
  CHECK(v.ready());
  verified = false;
  CHECK_OK(v.verify_permit(context(), ByteView{permit.data(), permit.size()},
                           payload, verified));
  CHECK(verified);
}

void test_cose_permit_cross_profile() {
  Fixture f;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;

  // A dev-HMAC envelope (no COSE tag) must NOT verify under the ESP256
  // profile — there is no downgrade path, the selected profile is exact.
  DevConfigAuthorityVerifier dev_v(
      ByteView{reinterpret_cast<const std::uint8_t*>("dev-key-material"),
               16});
  ConfigPermitContext ctx = context();
  const std::array<std::uint8_t, 32> dev_hmac{};  // shape only — never valid
  std::vector<std::uint8_t> dev_permit(f.permit.size(), 0x42);
  const Status s = f.verifier.verify_permit(
      ctx, ByteView{dev_permit.data(), dev_permit.size()}, payload, verified);
  CHECK(!s.ok() && !verified);
  (void)dev_v;
  (void)dev_hmac;
}

void test_cose_permit_der_signature_rejected() {
  Fixture f;
  endpoint::EncodedConfigCommand payload{};
  bool verified = false;
  // DER-encoded ECDSA signatures are ~70-72 bytes, not the fixed raw R||S —
  // re-shaping the signature bstr to a DER blob must fail the exact parse.
  auto m = f.permit;
  const std::size_t sig_hdr = m.size() - 66;  // 0x58 0x40 before signature
  CHECK(m[sig_hdr] == 0x58 && m[sig_hdr + 1] == 0x40);
  m[sig_hdr + 1] = 70;                         // claim bstr(70)
  m[sig_hdr + 2] = 0x30;                       // DER SEQUENCE marker
  m.insert(m.end(), 6, 0x00);                  // pad to claimed length
  const Status s = f.verifier.verify_permit(
      context(), ByteView{m.data(), m.size()}, payload, verified);
  CHECK(!s.ok() && !verified);
}

void test_cose_sig_structure_codec() {
  // Sig_structure round-trip shape: array4 + "Signature1" + 3 bstrs.
  const std::array<std::uint8_t, 13> prot{{0xa2,0x01,0x28,0x04,0x48,
                                         0,0,0,0,0,0,0x0A,0x17}};
  ByteBuffer<kConfigPermitAadSize> aad{};
  CHECK_OK(config_permit_aad(7, 0xC3, endpoint::kConfigNamespaceSdk, aad));
  const std::array<std::uint8_t, 4> pl{{1, 2, 3, 4}};
  ByteBuffer<kCosePermitMax + 64> sig{};
  CHECK_OK(cose_sig_structure(ByteView{prot.data(), prot.size()}, aad.view(),
                              ByteView{pl.data(), pl.size()}, sig));
  CHECK(sig.bytes[0] == 0x84 && sig.bytes[1] == 0x6A);
  CHECK(std::memcmp(sig.bytes.data() + 2, "Signature1", 10) == 0);
  CHECK(sig.bytes[12] == 0x4D);                       // protected bstr(13)
  CHECK(sig.bytes[12 + 14] == 0x58 &&
        sig.bytes[12 + 15] == 45);                    // aad bstr(45)
  // payload bstr(4) uses the short form after the aad.
  CHECK(sig.bytes[12 + 14 + 47] == 0x44);

  // AAD length is pinned to the expected context size — wire bytes never in.
  ByteBuffer<kCosePermitMax + 64> unused{};
  CHECK(!cose_sig_structure(ByteView{prot.data(), prot.size()},
                            ByteView{pl.data(), pl.size()},
                            ByteView{pl.data(), pl.size()}, unused).ok());
}

void test_cose_recovery_valid() {
  RecoveryFixture f;
  endpoint::EncodedRecoveryIntent payload{};
  bool verified = false;
  CHECK_OK(f.verifier.verify_recovery(
      recovery_context(), ByteView{f.object.data(), f.object.size()},
      payload, verified));
  CHECK(verified);
  endpoint::ConfigRecoveryIntent intent{};
  CHECK_OK(endpoint::config_recovery_decode(payload.view(), intent));
  CHECK(intent.mode == endpoint::kRcr2ModeReprovision);
  CHECK(intent.new_store_generation == 4);
  CHECK(intent.new_revision == 2);
  CHECK(intent.baseline.size == 12);
  CHECK(intent.authority == kRecoveryAuthorityId);
  CHECK(intent.authority_generation == 1);

  // Any tamper denies: the signature binds the recovery-domain AAD.
  auto bad = f.object;
  bad[bad.size() - 1] ^= 0x01;
  verified = true;
  CHECK_OK(f.verifier.verify_recovery(
      recovery_context(), ByteView{bad.data(), bad.size()}, payload,
      verified));
  CHECK(!verified);

  // A context pinning another generation denies (same pin as permits).
  ConfigPermitContext ctx = recovery_context();
  ctx.authority_generation = 2;
  verified = true;
  CHECK_OK(f.verifier.verify_recovery(
      ctx, ByteView{f.object.data(), f.object.size()}, payload, verified));
  CHECK(!verified);
}

void test_cose_lane_cross_injection() {
  // The lanes never cross-verify: a permit object through verify_recovery
  // and a recovery object through verify_permit are both refused — the
  // AAD domains differ on both sides of the envelope.
  Fixture permit;
  RecoveryFixture recovery;
  endpoint::EncodedRecoveryIntent rpayload{};
  endpoint::EncodedConfigCommand ppayload{};
  bool verified = true;
  // Same key on both sides: only the AAD domain differs, so a valid
  // permit envelope still denies on the recovery lane (and the short
  // RCR2 payload fails the permit lane's parse).
  const Status s1 = permit.verifier.verify_recovery(
      context(), ByteView{permit.permit.data(), permit.permit.size()},
      rpayload, verified);
  CHECK(s1.ok() && !verified);
  verified = true;
  const Status s2 = recovery.verifier.verify_permit(
      recovery_context(),
      ByteView{recovery.object.data(), recovery.object.size()}, ppayload,
      verified);
  CHECK(!s2.ok() && !verified);
}

}  // namespace

int main() {
  test_cose_permit_valid();
  test_cose_permit_denied_variants();
  test_cose_permit_malformed();
  test_cose_permit_signature_bounds();
  test_cose_provisioning();
  test_cose_permit_cross_profile();
  test_cose_permit_der_signature_rejected();
  test_cose_sig_structure_codec();
  test_cose_recovery_valid();
  test_cose_lane_cross_injection();
  if (failures != 0) {
    std::fprintf(stderr, "%d cose checks failed\n", failures);
    return 1;
  }
  std::puts("RouteLoom COSE ESP256 tests passed");
  return 0;
}
