// Member session wire (G-SEC P4 §5.3/§5.4) against
// protocol/sdkv1-golden/handshake/ (generated by the independent
// tools/gen_sdkv1_handshake_vectors.py, mirrored by
// host/routeloom-keysched): session EAD encode/decode, the carrier and
// end bindings, the capability/contexts digests, the 15-element
// Exporter contexts (including the true max-length encoding), and the
// RFC 9528 EDHOC_Exporter KDF from a known PRK. Valid vectors must
// decode to the listed fields and re-encode byte-for-byte; `*_flip_*`
// vectors must additionally differ from their base; invalid vectors
// must be refused.

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "routeloom/bootstrap_transport.hpp"
#include "routeloom/kdf.hpp"
#include "routeloom/key_schedule.hpp"
#include "routeloom/sdkv1_join_transport.hpp"
#include "routeloom/sdkv1_session_wire.hpp"

#ifndef ROUTELOOM_SDKV1_GOLDEN_DIR
#define ROUTELOOM_SDKV1_GOLDEN_DIR "protocol/sdkv1-golden"
#endif

namespace {

int failures = 0;
std::string current;
#define CHECK(expr)                                                                  \
  do {                                                                               \
    if (!(expr)) {                                                                   \
      std::fprintf(stderr, "CHECK failed %s:%d [%s]: %s\n", __FILE__, __LINE__,      \
                   current.c_str(), #expr);                                          \
      ++failures;                                                                    \
    }                                                                                \
  } while (false)

using namespace routeloom;
using namespace routeloom::sdkv1;
using Fields = std::map<std::string, std::string>;

Fields parse_flat_json(const std::string& text) {
  Fields fields;
  std::size_t pos = 0;
  while (pos < text.size()) {
    const std::size_t key_begin = text.find('"', pos);
    if (key_begin == std::string::npos) break;
    const std::size_t key_end = text.find('"', key_begin + 1);
    if (key_end == std::string::npos) break;
    const std::size_t colon = text.find(':', key_end + 1);
    if (colon == std::string::npos) break;
    std::size_t cursor = colon + 1;
    while (cursor < text.size() && std::isspace(static_cast<unsigned char>(text[cursor]))) {
      ++cursor;
    }
    std::string value;
    if (cursor < text.size() && text[cursor] == '"') {
      const std::size_t value_end = text.find('"', cursor + 1);
      if (value_end == std::string::npos) break;
      value = text.substr(cursor + 1, value_end - cursor - 1);
      pos = value_end + 1;
    } else {
      std::size_t value_end = cursor;
      while (value_end < text.size() &&
             std::isdigit(static_cast<unsigned char>(text[value_end]))) {
        ++value_end;
      }
      value = text.substr(cursor, value_end - cursor);
      pos = value_end;
    }
    fields[text.substr(key_begin + 1, key_end - key_begin - 1)] = value;
  }
  return fields;
}

std::uint64_t num(const Fields& fields, const std::string& key) {
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.empty()) {
    std::fprintf(stderr, "[%s] missing numeric field %s\n", current.c_str(), key.c_str());
    ++failures;
    return 0;
  }
  return std::strtoull(it->second.c_str(), nullptr, 10);
}

std::vector<std::uint8_t> hex(const Fields& fields, const std::string& key) {
  std::vector<std::uint8_t> out;
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.size() % 2 != 0) {
    std::fprintf(stderr, "[%s] missing hex field %s\n", current.c_str(), key.c_str());
    ++failures;
    return out;
  }
  for (std::size_t i = 0; i < it->second.size(); i += 2) {
    out.push_back(static_cast<std::uint8_t>(std::strtoul(it->second.substr(i, 2).c_str(), nullptr, 16)));
  }
  return out;
}

template <std::size_t N>
std::array<std::uint8_t, N> hex_array(const Fields& fields, const std::string& key) {
  std::array<std::uint8_t, N> out{};
  const auto bytes = hex(fields, key);
  if (bytes.size() == N) {
    std::copy(bytes.begin(), bytes.end(), out.begin());
  } else {
    std::fprintf(stderr, "[%s] field %s is not %zu bytes\n", current.c_str(), key.c_str(), N);
    ++failures;
  }
  return out;
}

std::string read_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  std::ostringstream contents;
  contents << input.rdbuf();
  return contents.str();
}

bool bytes_equal(const std::uint8_t* got, const std::size_t got_size,
                 const std::vector<std::uint8_t>& want) {
  return got_size == want.size() && std::equal(want.begin(), want.end(), got);
}

void check_format(const Fields& fields) {
  const auto it = fields.find("format");
  CHECK(it != fields.end() && it->second == "routeloom-sdkv1-handshake-golden-v1");
}

void check_intent(const Fields& fields) {
  const auto value = hex(fields, "value_hex");
  SessionIntent intent{};
  CHECK(session_intent_decode(ByteView{value.data(), value.size()}, intent).ok());
  CHECK(intent.purpose == static_cast<std::uint8_t>(num(fields, "purpose")));
  CHECK(intent.profile == static_cast<std::uint8_t>(num(fields, "profile")));
  CHECK(intent.caps_i == static_cast<std::uint32_t>(num(fields, "caps_i")));
  CHECK(intent.boot_i == static_cast<std::uint32_t>(num(fields, "boot_i")));
  CHECK(bytes_equal(intent.binding.data(), intent.binding.size(), hex(fields, "binding_hex")));
  std::array<std::uint8_t, kSessionIntentBytes> encoded{};
  CHECK(session_intent_encode(intent, encoded).ok());
  CHECK(bytes_equal(encoded.data(), encoded.size(), value));
}

void check_state(const Fields& fields) {
  const auto value = hex(fields, "value_hex");
  SessionState state{};
  CHECK(session_state_decode(ByteView{value.data(), value.size()}, state).ok());
  CHECK(state.purpose == static_cast<std::uint8_t>(num(fields, "purpose")));
  CHECK(state.profile == static_cast<std::uint8_t>(num(fields, "profile")));
  CHECK(state.site_epoch == static_cast<std::uint32_t>(num(fields, "site_epoch")));
  CHECK(state.rs_epoch == static_cast<std::uint32_t>(num(fields, "rs_epoch")));
  CHECK(state.gk_epoch == static_cast<std::uint32_t>(num(fields, "gk_epoch")));
  CHECK(state.boot == static_cast<std::uint32_t>(num(fields, "boot")));
  CHECK(state.caps == static_cast<std::uint32_t>(num(fields, "caps")));
  std::array<std::uint8_t, kSessionStateBytes> encoded{};
  CHECK(session_state_encode(state, encoded).ok());
  CHECK(bytes_equal(encoded.data(), encoded.size(), value));
}

void check_confirm(const Fields& fields) {
  const auto value = hex(fields, "value_hex");
  ContextConfirm confirm{};
  CHECK(context_confirm_decode(ByteView{value.data(), value.size()}, confirm).ok());
  CHECK(confirm.purpose == static_cast<std::uint8_t>(num(fields, "purpose")));
  CHECK(confirm.profile == static_cast<std::uint8_t>(num(fields, "profile")));
  CHECK(bytes_equal(confirm.contexts_digest.data(), confirm.contexts_digest.size(),
                    hex(fields, "digest_hex")));
  std::array<std::uint8_t, kContextConfirmBytes> encoded{};
  CHECK(context_confirm_encode(confirm, encoded).ok());
  CHECK(bytes_equal(encoded.data(), encoded.size(), value));
}

keys::LinkCarrier carrier_from(const Fields& fields) {
  keys::LinkCarrier carrier{};
  carrier.network = num(fields, "network");
  carrier.node_i = num(fields, "node_i");
  carrier.node_r = num(fields, "node_r");
  carrier.requester_nonce = hex_array<16>(fields, "nonce_i_hex");
  carrier.responder_nonce = hex_array<16>(fields, "nonce_r_hex");
  carrier.cookie = hex_array<16>(fields, "cookie_hex");
  carrier.capability_i = static_cast<std::uint32_t>(num(fields, "cap_i"));
  carrier.capability_r = static_cast<std::uint32_t>(num(fields, "cap_r"));
  carrier.scope_binding = hex_array<32>(fields, "scope_binding_hex");
  return carrier;
}

void check_carrier(const Fields& fields, const Fields* base) {
  const keys::LinkCarrier carrier = carrier_from(fields);
  ScopeDigest digest{};
  keys::link_carrier_digest(carrier, digest);
  CHECK(bytes_equal(digest.data(), digest.size(), hex(fields, "carrier_digest_hex")));
  const auto mac_i = hex_array<6>(fields, "mac_i_hex");
  const auto mac_r = hex_array<6>(fields, "mac_r_hex");
  ScopeDigest binding{};
  keys::resume_binding_link(mac_i, mac_r, digest, binding);
  const auto want_binding = hex(fields, "binding_link_hex");
  CHECK(bytes_equal(binding.data(), binding.size(), want_binding));
  if (base != nullptr) {
    // A single flipped field must move the (digest, binding) pair.
    const bool digest_same =
        bytes_equal(digest.data(), digest.size(), hex(*base, "carrier_digest_hex"));
    const bool binding_same = bytes_equal(binding.data(), binding.size(), hex(*base, "binding_link_hex"));
    CHECK(!digest_same || !binding_same);
  }
}

void check_end_binding(const Fields& fields, const Fields* base) {
  ScopeDigest binding{};
  keys::end_carrier_binding(num(fields, "network"), num(fields, "node_i"), num(fields, "node_r"),
                            static_cast<std::uint32_t>(num(fields, "exchange_id")), binding);
  CHECK(bytes_equal(binding.data(), binding.size(), hex(fields, "binding_hex")));
  if (base != nullptr) {
    CHECK(!bytes_equal(binding.data(), binding.size(), hex(*base, "binding_hex")));
  }
}

void check_capability(const Fields& fields) {
  const auto intent = hex(fields, "intent_hex");
  const auto state_r = hex(fields, "state_r_hex");
  const auto state_i = hex(fields, "state_i_hex");
  ScopeDigest digest{};
  CHECK(keys::session_capability_digest(ByteView{intent.data(), intent.size()},
                                       ByteView{state_r.data(), state_r.size()},
                                       ByteView{state_i.data(), state_i.size()}, digest)
            .ok());
  CHECK(bytes_equal(digest.data(), digest.size(), hex(fields, "digest_hex")));
}

void check_exporter_context(const Fields& fields, const Fields* base) {
  ExporterContextParams params{};
  params.purpose = static_cast<std::uint8_t>(num(fields, "purpose"));
  params.network = num(fields, "network");
  params.node_i = num(fields, "node_i");
  params.node_r = num(fields, "node_r");
  params.kid_i = hex_array<32>(fields, "kid_i_hex");
  params.kid_r = hex_array<32>(fields, "kid_r_hex");
  params.role_i = static_cast<std::uint32_t>(num(fields, "role_i"));
  params.role_r = static_cast<std::uint32_t>(num(fields, "role_r"));
  params.generation_i = static_cast<std::uint32_t>(num(fields, "generation_i"));
  params.generation_r = static_cast<std::uint32_t>(num(fields, "generation_r"));
  params.context_epoch = static_cast<std::uint32_t>(num(fields, "context_epoch"));
  params.direction = static_cast<std::uint8_t>(num(fields, "direction"));
  params.capability_digest = hex_array<32>(fields, "capability_hex");
  std::array<std::uint8_t, kExporterContextMax> encoded{};
  std::size_t used = 0;
  CHECK(exporter_context_encode(params, encoded, used).ok());
  const auto want = hex(fields, "context_hex");
  CHECK(used == want.size());
  CHECK(used == num(fields, "context_len"));
  CHECK(used <= kExporterContextMax);
  CHECK(bytes_equal(encoded.data(), used, want));
  if (base != nullptr) {
    CHECK(!bytes_equal(encoded.data(), used, hex(*base, "context_hex")));
  }
}

void check_contexts_digest(const Fields& fields) {
  const auto dir1 = hex(fields, "dir1_hex");
  const auto dir2 = hex(fields, "dir2_hex");
  const auto rms = hex(fields, "rms_hex");
  ScopeDigest digest{};
  CHECK(keys::session_contexts_digest(ByteView{dir1.data(), dir1.size()},
                                     ByteView{dir2.data(), dir2.size()},
                                     ByteView{rms.data(), rms.size()}, digest)
            .ok());
  CHECK(bytes_equal(digest.data(), digest.size(), hex(fields, "digest_hex")));
}

void check_exporter_output(const Fields& fields) {
  // The RFC 9528 KDF cross-check: our info encoder plus HKDF-Expand
  // must reproduce the Python reference output for the known PRK.
  const auto context = hex(fields, "context_hex");
  const auto length = static_cast<std::uint32_t>(num(fields, "length"));
  std::array<std::uint8_t, kEdhocKdfInfoMax> info{};
  std::size_t info_size = 0;
  CHECK(edhoc_kdf_info_encode(static_cast<std::uint32_t>(num(fields, "label")),
                              ByteView{context.data(), context.size()}, length, info, info_size)
            .ok());
  CHECK(bytes_equal(info.data(), info_size, hex(fields, "info_hex")));
  const auto prk = hex(fields, "prk_hex");
  std::array<std::uint8_t, 32> out{};
  CHECK(length <= out.size());
  CHECK(hkdf_sha256_expand(ByteView{prk.data(), prk.size()},
                           ByteView{info.data(), info_size},
                           MutableByteView{out.data(), length})
            .ok());
  CHECK(bytes_equal(out.data(), length, hex(fields, "output_hex")));
}

void check_invalid(const Fields& fields) {
  const auto codec_it = fields.find("codec");
  CHECK(codec_it != fields.end());
  const auto encoded = hex(fields, "encoded_hex");
  const ByteView view{encoded.data(), encoded.size()};
  if (codec_it->second == "session_intent") {
    SessionIntent intent{};
    CHECK(!session_intent_decode(view, intent).ok());
  } else if (codec_it->second == "session_state") {
    SessionState state{};
    CHECK(!session_state_decode(view, state).ok());
  } else if (codec_it->second == "context_confirm") {
    ContextConfirm confirm{};
    CHECK(!context_confirm_decode(view, confirm).ok());
  } else if (codec_it->second == "end_object") {
    EndObject object{};
    CHECK(!end_object_decode(view, object).ok());
  } else if (codec_it->second == "end_sub") {
    CHECK(encoded.size() == 1);
    if (encoded.size() == 1) {
      ObjectLane lane{};
      JoinAuthPhase phase{};
      std::uint8_t step = 0;
      CHECK(!object_sub_decode(encoded[0], lane, phase, step));
    }
  } else {
    std::fprintf(stderr, "[%s] unknown invalid codec %s\n", current.c_str(),
                 codec_it->second.c_str());
    ++failures;
  }
}

void check_end_object(const Fields& fields, const Fields* base) {
  const auto encoded = hex(fields, "object_hex");
  EndObject object{};
  CHECK(end_object_decode(ByteView{encoded.data(), encoded.size()}, object).ok());
  CHECK(object.phase == static_cast<JoinAuthPhase>(num(fields, "phase")));
  CHECK(object.step == num(fields, "step"));
  CHECK(object.exchange_id == num(fields, "exchange_id"));
  CHECK(object.profile == num(fields, "profile"));
  const auto message = hex(fields, "message_hex");
  CHECK(object.message.size == message.size());
  CHECK(std::equal(message.begin(), message.end(), object.message.data));
  std::array<std::uint8_t, kEndObjectMax> out{};
  std::size_t written = 0;
  CHECK(end_object_encode(object, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(bytes_equal(out.data(), written, encoded));
  if (base != nullptr) {
    const auto base_encoded = hex(*base, "object_hex");
    CHECK(encoded != base_encoded);
  }
}

void check_end_sub(const Fields& fields) {
  ObjectLane lane{};
  JoinAuthPhase phase{};
  std::uint8_t step = 0;
  CHECK(object_sub_decode(static_cast<std::uint8_t>(num(fields, "sub")), lane, phase, step));
  CHECK(lane == ObjectLane::EndSession);
  CHECK(phase == static_cast<JoinAuthPhase>(num(fields, "phase")));
  CHECK(step == num(fields, "step"));
  const auto lane_it = fields.find("lane");
  CHECK(lane_it != fields.end() && lane_it->second == "end");
}

}  // namespace

int main() {
  const std::filesystem::path root{ROUTELOOM_SDKV1_GOLDEN_DIR};
  const std::filesystem::path dir = root / "handshake";
  std::map<std::string, Fields> valid;
  for (const auto& entry : std::filesystem::directory_iterator(dir / "valid")) {
    if (entry.path().extension() != ".json") continue;
    current = entry.path().filename().string();
    const Fields fields = parse_flat_json(read_file(entry.path()));
    check_format(fields);
    const auto name_it = fields.find("name");
    if (name_it != fields.end()) {
      CHECK(valid.count(name_it->second) == 0);
      valid[name_it->second] = fields;
    } else {
      std::fprintf(stderr, "[%s] missing name\n", current.c_str());
      ++failures;
    }
  }
  // Flip vectors must name a base that exists; resolve after the full
  // load so directory order cannot hide a dangling reference.
  for (const auto& [name, fields] : valid) {
    current = name;
    const auto differs = fields.find("differs_from");
    if (differs != fields.end()) CHECK(valid.count(differs->second) != 0);
  }
  for (const auto& [name, fields] : valid) {
    current = name;
    const auto codec = fields.find("codec");
    if (codec == fields.end()) {
      std::fprintf(stderr, "[%s] missing codec\n", current.c_str());
      ++failures;
      continue;
    }
    if (codec->second == "session_intent") {
      check_intent(fields);
    } else if (codec->second == "session_state") {
      check_state(fields);
    } else if (codec->second == "context_confirm") {
      check_confirm(fields);
    } else if (codec->second == "carrier_link") {
      const Fields* base = nullptr;
      const auto differs = fields.find("differs_from");
      if (differs != fields.end()) {
        const auto base_it = valid.find(differs->second);
        if (base_it != valid.end()) base = &base_it->second;
      }
      check_carrier(fields, base);
    } else if (codec->second == "end_binding") {
      const Fields* base = nullptr;
      const auto differs = fields.find("differs_from");
      if (differs != fields.end()) {
        const auto base_it = valid.find(differs->second);
        if (base_it != valid.end()) base = &base_it->second;
      }
      check_end_binding(fields, base);
    } else if (codec->second == "capability_digest") {
      check_capability(fields);
    } else if (codec->second == "exporter_context") {
      const Fields* base = nullptr;
      const auto differs = fields.find("differs_from");
      if (differs != fields.end()) {
        const auto base_it = valid.find(differs->second);
        if (base_it != valid.end()) base = &base_it->second;
      }
      check_exporter_context(fields, base);
    } else if (codec->second == "contexts_digest") {
      check_contexts_digest(fields);
    } else if (codec->second == "exporter_output") {
      check_exporter_output(fields);
    } else if (codec->second == "end_object") {
      const Fields* base = nullptr;
      const auto differs = fields.find("differs_from");
      if (differs != fields.end()) {
        const auto base_it = valid.find(differs->second);
        if (base_it != valid.end()) base = &base_it->second;
      }
      check_end_object(fields, base);
    } else if (codec->second == "end_sub") {
      check_end_sub(fields);
    } else {
      std::fprintf(stderr, "[%s] unknown codec %s\n", current.c_str(), codec->second.c_str());
      ++failures;
    }
  }
  for (const auto& entry : std::filesystem::directory_iterator(dir / "invalid")) {
    if (entry.path().extension() != ".json") continue;
    current = entry.path().filename().string();
    const Fields fields = parse_flat_json(read_file(entry.path()));
    check_format(fields);
    check_invalid(fields);
  }
  // The max-encoding proof: no valid Exporter context may exceed the
  // pinned maximum, and the maximum itself must clear the 256 B budget.
  {
    current = "exporter_max bound";
    const auto max_it = valid.find("exporter_max");
    CHECK(max_it != valid.end());
    if (max_it != valid.end()) {
      const std::uint64_t max_len = num(max_it->second, "context_len");
      CHECK(max_len <= kExporterContextMax);
      for (const auto& [name, fields] : valid) {
        const auto codec = fields.find("codec");
        if (codec != fields.end() && codec->second == "exporter_context") {
          current = name;
          CHECK(num(fields, "context_len") <= max_len);
        }
      }
    }
  }
  if (failures == 0) {
    std::printf("sdkv1 session wire golden: all vectors agree\n");
    return 0;
  }
  std::fprintf(stderr, "sdkv1 session wire golden: %d failures\n", failures);
  return 1;
}
