// SDK v1 zero-touch join transport codecs (plan P3-1/P3-2, #116): the shared
// golden vectors in protocol/sdkv1-golden/join-transport/ (RLD1, generated by
// the independent tools/gen_sdkv1_join_transport_vectors.py) and
// protocol/sdkv1-golden/join-relay-v2/ (Wire v2, generated by the independent
// tools/gen_sdkv1_join_relay_v2_vectors.py), plus unit checks of the bounded
// object slot (out-of-order, duplicate, conflicting and late chunks,
// timeouts, receiver progress) and of the zero-touch admission rules.
// Valid vectors decode to the listed fields and re-encode byte-for-byte;
// chunk sequences are regenerated from the object and reassembled in reverse
// order; invalid vectors are rejected by the decoder. The frozen v1 Wire
// vectors in join-transport/v1-history/ are rejected by the v2 decoders.

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "routeloom/sdkv1_join_relay.hpp"
#include "routeloom/sdkv1_join_transport.hpp"

#ifndef ROUTELOOM_SDKV1_GOLDEN_DIR
#define ROUTELOOM_SDKV1_GOLDEN_DIR "protocol/sdkv1-golden"
#endif

namespace {

int failures = 0;
std::string current;
#define CHECK(expr)                                                                  \
  do {                                                                               \
    if (!(expr)) {                                                                   \
      std::fprintf(stderr, "CHECK failed %s:%d [%s]: %s\n", __FILE__, __LINE__,      \
                   current.c_str(), #expr);                                          \
      ++failures;                                                                    \
    }                                                                                \
  } while (false)

using namespace routeloom;
using namespace routeloom::sdkv1;
using Fields = std::map<std::string, std::string>;
using Bytes = std::vector<std::uint8_t>;

Fields parse_flat_json(const std::string& text) {
  Fields fields;
  std::size_t pos = 0;
  while (pos < text.size()) {
    const std::size_t key_begin = text.find('"', pos);
    if (key_begin == std::string::npos) break;
    const std::size_t key_end = text.find('"', key_begin + 1);
    if (key_end == std::string::npos) break;
    const std::size_t colon = text.find(':', key_end + 1);
    if (colon == std::string::npos) break;
    std::size_t cursor = colon + 1;
    while (cursor < text.size() && std::isspace(static_cast<unsigned char>(text[cursor]))) {
      ++cursor;
    }
    std::string value;
    if (cursor < text.size() && text[cursor] == '"') {
      const std::size_t value_end = text.find('"', cursor + 1);
      if (value_end == std::string::npos) break;
      value = text.substr(cursor + 1, value_end - cursor - 1);
      pos = value_end + 1;
    } else {
      std::size_t value_end = cursor;
      while (value_end < text.size() &&
             std::isdigit(static_cast<unsigned char>(text[value_end]))) {
        ++value_end;
      }
      value = text.substr(cursor, value_end - cursor);
      pos = value_end;
    }
    fields[text.substr(key_begin + 1, key_end - key_begin - 1)] = value;
  }
  return fields;
}

std::uint64_t num(const Fields& fields, const std::string& key) {
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.empty()) {
    std::fprintf(stderr, "[%s] missing numeric field %s\n", current.c_str(), key.c_str());
    ++failures;
    return 0;
  }
  return std::strtoull(it->second.c_str(), nullptr, 10);
}

Bytes hex(const Fields& fields, const std::string& key) {
  Bytes out;
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.size() % 2 != 0) {
    std::fprintf(stderr, "[%s] missing hex field %s\n", current.c_str(), key.c_str());
    ++failures;
    return out;
  }
  for (std::size_t i = 0; i < it->second.size(); i += 2) {
    out.push_back(
        static_cast<std::uint8_t>(std::strtoul(it->second.substr(i, 2).c_str(), nullptr, 16)));
  }
  return out;
}

template <std::size_t N>
std::array<std::uint8_t, N> hex_array(const Fields& fields, const std::string& key) {
  std::array<std::uint8_t, N> out{};
  const auto bytes = hex(fields, key);
  if (bytes.size() == N) {
    std::copy(bytes.begin(), bytes.end(), out.begin());
  } else {
    std::fprintf(stderr, "[%s] field %s is not %zu bytes\n", current.c_str(), key.c_str(), N);
    ++failures;
  }
  return out;
}

ByteView view(const Bytes& bytes) { return ByteView{bytes.data(), bytes.size()}; }

bool same(const ByteView a, const Bytes& b) {
  return a.size == b.size() && (b.empty() || std::memcmp(a.data, b.data(), b.size()) == 0);
}

std::string two(const std::size_t i) {
  char buffer[8];
  std::snprintf(buffer, sizeof(buffer), "%02zu", i);
  return buffer;
}

std::string read_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  std::ostringstream contents;
  contents << input.rdbuf();
  return contents.str();
}

std::vector<std::filesystem::path> list_json(const std::filesystem::path& dir) {
  std::vector<std::filesystem::path> out;
  if (!std::filesystem::exists(dir)) return out;
  for (const auto& entry : std::filesystem::directory_iterator(dir)) {
    if (entry.path().extension() == ".json") out.push_back(entry.path());
  }
  std::sort(out.begin(), out.end());
  return out;
}

JoinCarrier carrier_named(const std::string& name) {
  return name == "wire" ? JoinCarrier::WireRelay : JoinCarrier::Rld1;
}

Bytes rld1_frame(const FrameType kind, const std::uint32_t hint, const NodeId claimed,
                 const JoinNonce& nonce, const ByteView body) {
  autonomy::Rld1Envelope env{};
  env.kind = kind;
  env.network_hint = hint;
  env.claimed_node = claimed;
  env.transaction_nonce = nonce;
  std::memcpy(env.body.data(), body.data, body.size);
  env.body_size = body.size;
  autonomy::Rld1Encoded out{};
  CHECK(autonomy::rld1_encode(env, out).ok());
  return Bytes(out.bytes.begin(), out.bytes.begin() + static_cast<std::ptrdiff_t>(out.size));
}

autonomy::Rld1Envelope envelope(const Bytes& frame) {
  autonomy::Rld1Envelope env{};
  CHECK(autonomy::rld1_decode(view(frame), env).ok());
  return env;
}

// --- valid ------------------------------------------------------------------------

void valid_discover(const Fields& f) {
  const Bytes frame = hex(f, "frame_hex");
  autonomy::Rld1Envelope env{};
  ZtDiscoverBody body{};
  CHECK(zt_discover_frame_decode(view(frame), env, body).ok());
  CHECK(env.claimed_node == num(f, "claimed_node"));
  CHECK(env.transaction_nonce == (hex_array<16>(f, "nonce_hex")));
  CHECK(body.profile_bits == num(f, "profile_bits"));
  CHECK(body.org_hint == num(f, "org_hint"));
  CHECK(body.preferred_site_hint == num(f, "preferred_site_hint"));
  CHECK(body.avoid_site_hints[0] == num(f, "avoid0"));
  CHECK(body.avoid_site_hints[1] == num(f, "avoid1"));
  ByteBuffer<kZtDiscoverBodySize> encoded{};
  CHECK(zt_discover_body_encode(body, encoded).ok());
  CHECK(same(encoded.view(), hex(f, "body_hex")));
  autonomy::Rld1Encoded again{};
  CHECK(zt_discover_frame_encode(env.claimed_node, env.transaction_nonce, body, again).ok());
  CHECK(same(again.view(), frame));
  CHECK(zt_rld1_frame(env));
  // A joiner may send it, a proxy may receive it; never the other way.
  CHECK(zt_admit_rld1(MembershipState::Discovering, AdmissionDirection::Tx, env).ok());
  CHECK(zt_admit_rld1(MembershipState::Member, AdmissionDirection::Rx, env).ok());
  CHECK(!zt_admit_rld1(MembershipState::Member, AdmissionDirection::Tx, env).ok());
  CHECK(!zt_admit_rld1(MembershipState::Discovering, AdmissionDirection::Rx, env).ok());
  if (body.avoid_site_hints[0] != 0) CHECK(zt_discover_avoids(body, body.avoid_site_hints[0]));
  CHECK(!zt_discover_avoids(body, 0));
}

void valid_offer(const Fields& f) {
  const Bytes frame = hex(f, "frame_hex");
  autonomy::Rld1Envelope env{};
  ZtOfferBody body{};
  CHECK(zt_offer_frame_decode(view(frame), env, body).ok());
  CHECK(env.claimed_node == num(f, "proxy"));
  CHECK(env.network_hint == num(f, "network_low32"));
  CHECK(body.density == num(f, "density"));
  CHECK(body.flags == num(f, "flags"));
  CHECK(body.cookie == (hex_array<16>(f, "cookie_hex")));
  CHECK(body.responder_nonce == (hex_array<16>(f, "responder_nonce_hex")));
  CHECK(body.org_hint == num(f, "org_hint"));
  CHECK(body.site_hint == num(f, "site_hint"));
  CHECK(body.authority_hops == num(f, "authority_hops"));
  CHECK(body.load == num(f, "load"));
  ByteBuffer<kZtOfferBodySize> encoded{};
  CHECK(zt_offer_body_encode(body, encoded).ok());
  CHECK(same(encoded.view(), hex(f, "body_hex")));
  autonomy::Rld1Encoded again{};
  CHECK(zt_offer_frame_encode(env.claimed_node, env.network_hint, env.transaction_nonce, body,
                              again)
            .ok());
  CHECK(same(again.view(), frame));
  CHECK(zt_admit_rld1(MembershipState::Member, AdmissionDirection::Tx, env).ok());
  CHECK(zt_admit_rld1(MembershipState::Discovering, AdmissionDirection::Rx, env).ok());
  CHECK(!zt_admit_rld1(MembershipState::Discovering, AdmissionDirection::Tx, env).ok());
}

void valid_cookie(const Fields& f) {
  HmacJoinCookie sealer(hex_array<32>(f, "key_hex"));
  JoinCookieMaterial material{};
  material.requester_mac = hex_array<6>(f, "mac_hex");
  material.nonce = hex_array<16>(f, "nonce_hex");
  material.proxy = num(f, "proxy");
  material.network_low32 = static_cast<std::uint32_t>(num(f, "network_low32"));
  material.bucket = num(f, "bucket");
  JoinCookieBytes cookie{};
  CHECK(sealer.seal(material, cookie).ok());
  CHECK(cookie == (hex_array<16>(f, "cookie_hex")));
}

void valid_object(const Fields& f) {
  const Bytes encoded = hex(f, "object_hex");
  JoinAuthObject object{};
  CHECK(join_object_decode(view(encoded), object).ok());
  CHECK(static_cast<std::uint8_t>(object.phase) == num(f, "phase"));
  CHECK(object.step == num(f, "step"));
  CHECK(object.cookie_present == (num(f, "cookie_present") == 1));
  if (object.cookie_present) CHECK(object.cookie == (hex_array<16>(f, "cookie_hex")));
  if (object.phase == JoinAuthPhase::RelayStatus) {
    CHECK(static_cast<std::uint8_t>(object.relay_status) == num(f, "relay_status"));
    CHECK(object.retry_after_ms == num(f, "retry_after_ms"));
  } else {
    CHECK(same(object.message, hex(f, "message_hex")));
  }
  CHECK(join_object_encoded_size(object) == encoded.size());
  std::array<std::uint8_t, kJoinObjectMax> out{};
  std::size_t written = 0;
  CHECK(join_object_encode(object, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(same(ByteView{out.data(), written}, encoded));
}

void valid_rld1_frames(const Fields& f) {
  const Bytes object = hex(f, "object_hex");
  const auto phase = static_cast<JoinAuthPhase>(num(f, "phase"));
  const auto step = static_cast<std::uint8_t>(num(f, "step"));
  const JoinNonce nonce = hex_array<16>(f, "nonce_hex");
  const bool from_device = f.at("sender") == "device";
  const NodeId claimed = num(f, "claimed_node");
  const auto hint = static_cast<std::uint32_t>(num(f, "network_hint"));
  const std::uint32_t id = join_rld1_object_id(nonce);
  CHECK(id == num(f, "object_id"));
  const std::size_t count = num(f, "frame_count");
  const MembershipState sender_state =
      from_device ? MembershipState::Authenticating : MembershipState::Member;
  const MembershipState receiver_state =
      from_device ? MembershipState::Member : MembershipState::Authenticating;
  if (count == 1) {
    const Bytes frame = rld1_frame(FrameType::BootstrapAuth, hint, claimed, nonce, view(object));
    CHECK(same(view(frame), hex(f, "frame_00_hex")));
    const autonomy::Rld1Envelope env = envelope(frame);
    CHECK(zt_admit_rld1(sender_state, AdmissionDirection::Tx, env).ok());
    CHECK(zt_admit_rld1(receiver_state, AdmissionDirection::Rx, env).ok());
    CHECK(object.size() <= autonomy::kRld1MaxBody);
    return;
  }
  // Sender: the slot reproduces every chunk frame.
  JoinObjectSlot sender{};
  CHECK(sender.load(JoinCarrier::Rld1, phase, step, id, 0, 0, view(object), 0).ok());
  CHECK(sender.chunk_total() == count);
  // Chunk views borrow the sender's buffer, which a Done reply wipes: keep
  // the encoded payloads and decode them for the receiver runs.
  std::vector<Bytes> payloads;
  std::vector<JoinChunk> chunks;
  for (std::size_t i = 0; i < count; ++i) {
    JoinChunk chunk{};
    CHECK(sender.chunk_at(i, chunk).ok());
    std::array<std::uint8_t, autonomy::kRld1MaxBody> body{};
    std::size_t written = 0;
    CHECK(join_chunk_encode(JoinCarrier::Rld1, chunk, MutableByteView{body.data(), body.size()},
                            written)
              .ok());
    const Bytes frame =
        rld1_frame(FrameType::BootstrapChunk, hint, claimed, nonce, ByteView{body.data(), written});
    CHECK(same(view(frame), hex(f, "frame_" + two(i) + "_hex")));
    const autonomy::Rld1Envelope env = envelope(frame);
    CHECK(zt_admit_rld1(sender_state, AdmissionDirection::Tx, env).ok());
    CHECK(zt_admit_rld1(receiver_state, AdmissionDirection::Rx, env).ok());
    JoinChunk decoded{};
    CHECK(join_chunk_decode(JoinCarrier::Rld1, ByteView{env.body.data(), env.body_size}, decoded)
              .ok());
    payloads.emplace_back(body.data(), body.data() + written);
  }
  for (const Bytes& payload : payloads) {
    JoinChunk chunk{};
    CHECK(join_chunk_decode(JoinCarrier::Rld1, view(payload), chunk).ok());
    chunks.push_back(chunk);
  }
  // Receiver in order: the replies match the vector.
  const NodeId peer = from_device ? NodeId{0x00A1000000000777} : NodeId{0x00A1000000001234};
  const std::uint32_t peer_hint = from_device ? 0x0A1B2C3Du : 0u;
  JoinObjectSlot in_order{};
  for (std::size_t i = 0; i < count; ++i) {
    const JoinObjectSlot::Accepted accepted = in_order.accept(JoinCarrier::Rld1, chunks[i], 10);
    CHECK(accepted.send_reply);
    std::array<std::uint8_t, kJoinReplySize> body{};
    std::size_t written = 0;
    CHECK(join_reply_encode(JoinCarrier::Rld1, accepted.reply,
                            MutableByteView{body.data(), body.size()}, written)
              .ok());
    const Bytes frame =
        rld1_frame(FrameType::BootstrapReply, peer_hint, peer, nonce, ByteView{body.data(), written});
    CHECK(same(view(frame), hex(f, "reply_" + two(i) + "_hex")));
    const autonomy::Rld1Envelope env = envelope(frame);
    CHECK(zt_admit_rld1(receiver_state, AdmissionDirection::Tx, env).ok());
    CHECK(zt_admit_rld1(sender_state, AdmissionDirection::Rx, env).ok());
    // The sender takes the receiver's progress.
    const JoinObjectSlot::ReplyOutcome outcome = sender.on_reply(accepted.reply, 20);
    CHECK(outcome == (i + 1 == count ? JoinObjectSlot::ReplyOutcome::Done
                                     : JoinObjectSlot::ReplyOutcome::Progress));
  }
  CHECK(same(in_order.assembled(), object));
  CHECK(sender.mode() == JoinObjectSlot::Mode::Idle);
  // Receiver in reverse order with a duplicate of every chunk.
  JoinObjectSlot reverse{};
  for (std::size_t i = count; i-- > 0;) {
    const auto first = reverse.accept(JoinCarrier::Rld1, chunks[i], 30);
    if (i == 0) {
      CHECK(first.outcome == JoinObjectSlot::Outcome::Complete);
      CHECK(first.reply.status == JoinReplyStatus::Complete);
    } else {
      CHECK(first.outcome == JoinObjectSlot::Outcome::Progress);
      CHECK(first.reply.received == 0);  // no contiguous prefix before chunk 0
      const auto duplicate = reverse.accept(JoinCarrier::Rld1, chunks[i], 31);
      CHECK(duplicate.outcome == JoinObjectSlot::Outcome::Progress);
    }
  }
  CHECK(same(reverse.assembled(), object));
  JoinAuthObject decoded{};
  CHECK(join_object_decode(reverse.assembled(), decoded).ok());
  reverse.release_assembled();
  // A late duplicate re-sends Complete.
  const auto late = reverse.accept(JoinCarrier::Rld1, chunks[count - 1], 40);
  CHECK(late.outcome == JoinObjectSlot::Outcome::Repeat);
  CHECK(late.reply.status == JoinReplyStatus::Complete && late.reply.received == object.size());
}

void valid_chunk(const Fields& f) {
  const Bytes payload = hex(f, "payload_hex");
  const JoinCarrier carrier = carrier_named(f.at("carrier"));
  JoinChunk chunk{};
  CHECK(join_chunk_decode(carrier, view(payload), chunk).ok());
  CHECK(static_cast<std::uint8_t>(chunk.phase) == num(f, "phase"));
  CHECK(chunk.step == num(f, "step"));
  CHECK(chunk.id == num(f, "id"));
  CHECK(chunk.offset == num(f, "offset"));
  CHECK(chunk.total == num(f, "total"));
  if (carrier == JoinCarrier::WireRelay) {
    CHECK(chunk.gateway_epoch == num(f, "gateway_epoch"));
    CHECK(chunk.proxy_epoch == num(f, "proxy_epoch"));
  } else {
    CHECK(chunk.gateway_epoch == 0);
    CHECK(chunk.proxy_epoch == 0);
  }
  CHECK(same(chunk.data, hex(f, "data_hex")));
  std::array<std::uint8_t, kMaxApplicationPayload> out{};
  std::size_t written = 0;
  CHECK(join_chunk_encode(carrier, chunk, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(same(ByteView{out.data(), written}, payload));
}

void valid_reply(const Fields& f) {
  const Bytes payload = hex(f, "payload_hex");
  const JoinCarrier carrier = carrier_named(f.at("carrier"));
  JoinReply reply{};
  CHECK(join_reply_decode(carrier, view(payload), reply).ok());
  CHECK(static_cast<std::uint8_t>(reply.phase) == num(f, "phase"));
  CHECK(reply.step == num(f, "step"));
  CHECK(reply.id == num(f, "id"));
  CHECK(reply.received == num(f, "received"));
  CHECK(static_cast<std::uint8_t>(reply.status) == num(f, "status"));
  if (carrier == JoinCarrier::WireRelay) {
    CHECK(reply.gateway_epoch == num(f, "gateway_epoch"));
    CHECK(reply.proxy_epoch == num(f, "proxy_epoch"));
  } else {
    CHECK(reply.gateway_epoch == 0);
    CHECK(reply.proxy_epoch == 0);
  }
  std::array<std::uint8_t, kWireRelayReplySize> out{};
  std::size_t written = 0;
  CHECK(join_reply_encode(carrier, reply, MutableByteView{out.data(), out.size()}, written)
            .ok());
  CHECK(same(ByteView{out.data(), written}, payload));
  CHECK(written == join_reply_size(carrier));
}

void valid_relay(const Fields& f) {
  const Bytes encoded = hex(f, "object_hex");
  RelayObject object{};
  CHECK(relay_object_decode(view(encoded), object).ok());
  const RelayHeader& h = object.header;
  CHECK(static_cast<std::uint8_t>(h.dir) == num(f, "dir"));
  CHECK(h.relay_id == num(f, "relay_id"));
  CHECK(h.proxy == num(f, "proxy"));
  CHECK(h.joiner_mac == (hex_array<6>(f, "joiner_mac_hex")));
  CHECK(static_cast<std::uint8_t>(h.phase) == num(f, "phase"));
  CHECK(h.step == num(f, "step"));
  CHECK(static_cast<std::uint8_t>(h.state) == num(f, "state"));
  CHECK(static_cast<std::uint8_t>(h.joiner_rssi_dbm) == num(f, "rssi_u8"));
  CHECK(h.gateway_epoch == num(f, "gateway_epoch"));
  CHECK(h.proxy_epoch == num(f, "proxy_epoch"));
  CHECK(classify_wire_relay(view(encoded)) == WireRelayKind::RelayObject);
  if (h.state == RelayState::Abort) {
    CHECK(static_cast<std::uint8_t>(object.abort.status) == num(f, "abort_status"));
    CHECK(object.abort.retry_after_ms == num(f, "abort_retry_ms"));
  } else {
    CHECK(same(object.message, hex(f, "message_hex")));
  }
  CHECK(relay_object_encoded_size(object) == encoded.size());
  std::array<std::uint8_t, kJoinObjectMax> out{};
  std::size_t written = 0;
  CHECK(relay_object_encode(object, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(same(ByteView{out.data(), written}, encoded));
  const std::size_t count = num(f, "frame_count");
  if (count == 1) {
    const auto type = static_cast<FrameType>(num(f, "frame_00_type"));
    CHECK(static_cast<std::uint8_t>(type) == num(f, "wire_type"));
    CHECK(relay_single_frame_type(h) == type);
    RelayObject single{};
    CHECK(relay_single_frame_decode(type, view(encoded), single).ok());
    CHECK(same(view(encoded), hex(f, "frame_00_hex")));
    return;
  }
  CHECK(num(f, "wire_type") == 0);
  JoinObjectSlot sender{};
  CHECK(sender.load(JoinCarrier::WireRelay, h.phase, h.step, h.relay_id, h.gateway_epoch,
                    h.proxy_epoch, view(encoded), 0)
            .ok());
  CHECK(sender.chunk_total() == count);
  JoinObjectSlot receiver{};
  for (std::size_t i = 0; i < count; ++i) {
    CHECK(num(f, "frame_" + two(i) + "_type") ==
          static_cast<std::uint8_t>(FrameType::BootstrapChunk));
    JoinChunk chunk{};
    CHECK(sender.chunk_at(i, chunk).ok());
    std::array<std::uint8_t, kMaxApplicationPayload> body{};
    std::size_t size = 0;
    CHECK(join_chunk_encode(JoinCarrier::WireRelay, chunk,
                            MutableByteView{body.data(), body.size()}, size)
              .ok());
    CHECK(same(ByteView{body.data(), size}, hex(f, "frame_" + two(i) + "_hex")));
    const auto accepted = receiver.accept(JoinCarrier::WireRelay, chunk, 5);
    std::array<std::uint8_t, kWireRelayReplySize> receipt{};
    CHECK(join_reply_encode(JoinCarrier::WireRelay, accepted.reply,
                            MutableByteView{receipt.data(), receipt.size()}, size)
              .ok());
    CHECK(same(ByteView{receipt.data(), size}, hex(f, "receipt_" + two(i) + "_hex")));
  }
  CHECK(same(receiver.assembled(), encoded));
}

void valid_epoch_query(const Fields& f) {
  const Bytes payload = hex(f, "payload_hex");
  EpochQuery query{};
  CHECK(epoch_query_decode(view(payload), query).ok());
  CHECK(query.nonce == (hex_array<16>(f, "nonce_hex")));
  CHECK(classify_wire_relay(view(payload)) == WireRelayKind::EpochQuery);
  std::array<std::uint8_t, kEpochQuerySize> out{};
  std::size_t written = 0;
  CHECK(epoch_query_encode(query, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(same(ByteView{out.data(), written}, payload));
}

void valid_epoch_reply(const Fields& f) {
  const Bytes payload = hex(f, "payload_hex");
  EpochReply reply{};
  CHECK(epoch_reply_decode(view(payload), reply).ok());
  CHECK(reply.gateway_epoch == num(f, "gateway_epoch"));
  CHECK(reply.nonce == (hex_array<16>(f, "nonce_hex")));
  CHECK(reply.authority_ready == (num(f, "ready") != 0));
  CHECK(classify_wire_relay(view(payload)) == WireRelayKind::EpochReply);
  std::array<std::uint8_t, kEpochReplySize> out{};
  std::size_t written = 0;
  CHECK(epoch_reply_encode(reply, MutableByteView{out.data(), out.size()}, written).ok());
  CHECK(same(ByteView{out.data(), written}, payload));
}

// --- invalid ----------------------------------------------------------------------

void invalid(const Fields& f) {
  CHECK(f.at("expect") == "error");
  const std::string& codec = f.at("codec");
  const Bytes encoded = hex(f, "encoded_hex");
  const ByteView input = view(encoded);
  if (codec == "zt_discover_frame") {
    autonomy::Rld1Envelope env{};
    ZtDiscoverBody body{};
    CHECK(!zt_discover_frame_decode(input, env, body).ok());
  } else if (codec == "zt_offer_frame") {
    autonomy::Rld1Envelope env{};
    ZtOfferBody body{};
    CHECK(!zt_offer_frame_decode(input, env, body).ok());
  } else if (codec == "join_object") {
    JoinAuthObject object{};
    CHECK(!join_object_decode(input, object).ok());
  } else if (codec == "join_chunk") {
    JoinChunk chunk{};
    CHECK(!join_chunk_decode(carrier_named(f.at("carrier")), input, chunk).ok());
    // The slot refuses the same bytes too.
    JoinObjectSlot slot{};
    chunk = JoinChunk{};
    CHECK(slot.accept(carrier_named(f.at("carrier")), chunk, 0).outcome ==
          JoinObjectSlot::Outcome::Rejected);
  } else if (codec == "join_reply") {
    // Carriers split in v2: a vector names its carrier, otherwise both
    // carriers must refuse it.
    const auto carriers = f.count("carrier") != 0
                              ? std::vector<JoinCarrier>{carrier_named(f.at("carrier"))}
                              : std::vector<JoinCarrier>{JoinCarrier::Rld1,
                                                         JoinCarrier::WireRelay};
    for (const JoinCarrier carrier : carriers) {
      JoinReply reply{};
      CHECK(!join_reply_decode(carrier, input, reply).ok());
    }
  } else if (codec == "relay_object") {
    RelayObject object{};
    CHECK(!relay_object_decode(input, object).ok());
  } else if (codec == "relay_single_frame") {
    RelayObject object{};
    CHECK(!relay_single_frame_decode(static_cast<FrameType>(num(f, "wire_type")), input, object)
               .ok());
  } else if (codec == "epoch_query") {
    EpochQuery query{};
    CHECK(!epoch_query_decode(input, query).ok());
  } else if (codec == "epoch_reply") {
    EpochReply reply{};
    CHECK(!epoch_reply_decode(input, reply).ok());
  } else {
    CHECK(!"unknown invalid codec");
  }
}

// --- unit checks ------------------------------------------------------------------

JoinChunk make_chunk(const Bytes& object, const std::size_t index, const std::uint8_t step = 2,
                     const std::uint32_t id = 0x01020304) {
  JoinChunk chunk{};
  chunk.phase = JoinAuthPhase::EdhocMessage;
  chunk.step = step;
  chunk.id = id;
  chunk.total = static_cast<std::uint16_t>(object.size());
  chunk.offset = static_cast<std::uint16_t>(index * kRld1JoinChunkData);
  chunk.data = ByteView{object.data() + chunk.offset,
                        std::min<std::size_t>(kRld1JoinChunkData, object.size() - chunk.offset)};
  return chunk;
}

void unit_cookie_keying() {
  current = "unit_cookie_keying";
  // G-SEC P4 §8.4: the owner constructs the sealer before radio-up
  // entropy exists and arms it at boot. An unkeyed sealer refuses (never
  // a weak zero-key cookie); arming is one-time and rejects zero keys.
  HmacJoinCookie sealer;
  JoinCookieMaterial material{};
  material.proxy = 0x11;
  material.network_low32 = 0x524c0001;
  JoinCookieBytes cookie{};
  CHECK(!sealer.keyed());
  CHECK(sealer.seal(material, cookie).code == StatusCode::InvalidState);
  std::array<std::uint8_t, 32> zero{};
  CHECK(sealer.install_key(zero).code == StatusCode::InvalidArgument);
  CHECK(!sealer.keyed());
  std::array<std::uint8_t, 32> key{};
  for (std::size_t i = 0; i < key.size(); ++i) key[i] = static_cast<std::uint8_t>(i + 1);
  CHECK(sealer.install_key(key).ok());
  CHECK(sealer.keyed());
  CHECK(sealer.seal(material, cookie).ok());
  CHECK(sealer.install_key(key).code == StatusCode::InvalidState);
  // The explicit ctor stays keyed (existing proxy/gateway callers).
  HmacJoinCookie keyed(key);
  JoinCookieBytes again{};
  CHECK(keyed.keyed());
  CHECK(keyed.seal(material, again).ok());
  CHECK(cookie == again);
}

void unit_slot() {
  current = "unit_slot";
  Bytes object(300);
  for (std::size_t i = 0; i < object.size(); ++i) object[i] = static_cast<std::uint8_t>(i * 7);
  // Conflicting duplicate: same offset, different bytes -> Aborted reply.
  {
    JoinObjectSlot slot{};
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 1), 0).outcome ==
          JoinObjectSlot::Outcome::Progress);
    Bytes forged = object;
    forged[kRld1JoinChunkData + 3] ^= 0xFF;
    const auto conflict = slot.accept(JoinCarrier::Rld1, make_chunk(forged, 1), 1);
    CHECK(conflict.outcome == JoinObjectSlot::Outcome::Conflict);
    CHECK(conflict.reply.status == JoinReplyStatus::Aborted && conflict.reply.received == 0);
    CHECK(slot.mode() == JoinObjectSlot::Mode::Idle);
  }
  // Total changes mid-assembly -> Conflict; another object -> Busy.
  {
    JoinObjectSlot slot{};
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 0), 0).outcome ==
          JoinObjectSlot::Outcome::Progress);
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 0, 3), 1).outcome ==
          JoinObjectSlot::Outcome::Busy);
    CHECK(slot.accept(JoinCarrier::WireRelay, JoinChunk{}, 1).outcome ==
          JoinObjectSlot::Outcome::Rejected);
    Bytes longer(object);
    longer.resize(320);
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(longer, 1), 2).outcome ==
          JoinObjectSlot::Outcome::Conflict);
  }
  // Timeout drops an assembly; the next chunk starts over.
  {
    JoinObjectSlot slot{};
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 0), 1000).outcome ==
          JoinObjectSlot::Outcome::Progress);
    CHECK(!slot.expire(3999, 3000));
    CHECK(slot.expire(4000, 3000));
    CHECK(slot.mode() == JoinObjectSlot::Mode::Idle);
    const auto restart = slot.accept(JoinCarrier::Rld1, make_chunk(object, 1), 4001);
    CHECK(restart.outcome == JoinObjectSlot::Outcome::Progress && restart.reply.received == 0);
  }
  // Repeat also while the slot already sends another object.
  {
    JoinObjectSlot slot{};
    for (std::size_t i = 0; i < 3; ++i) (void)slot.accept(JoinCarrier::Rld1, make_chunk(object, i), 0);
    CHECK(slot.mode() == JoinObjectSlot::Mode::Assembled);
    Bytes next(500, 0x42);
    CHECK(slot.load(JoinCarrier::WireRelay, JoinAuthPhase::EdhocMessage, 3, 9, 7, 3, view(next), 5)
              .ok());
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 2), 6).outcome ==
          JoinObjectSlot::Outcome::Repeat);
    CHECK(slot.accept(JoinCarrier::Rld1, make_chunk(object, 0, 4), 6).outcome ==
          JoinObjectSlot::Outcome::Busy);
    // Sender side: pending chunks follow the receiver's contiguous prefix.
    CHECK(slot.chunk_total() == 5);
    CHECK(slot.pending_mask() == 0x1F);
    JoinReply progress{JoinAuthPhase::EdhocMessage, 3, 9, 236, JoinReplyStatus::Progress, ObjectLane::JoinRelay, 7, 3};
    CHECK(slot.on_reply(progress, 7) == JoinObjectSlot::ReplyOutcome::Progress);
    CHECK(slot.pending_mask() == 0x1C);
    JoinReply other{JoinAuthPhase::EdhocMessage, 3, 8, 500, JoinReplyStatus::Complete, ObjectLane::JoinRelay, 7, 3};
    CHECK(slot.on_reply(other, 7) == JoinObjectSlot::ReplyOutcome::Ignored);
    JoinReply stale{JoinAuthPhase::EdhocMessage, 3, 9, 500, JoinReplyStatus::Complete, ObjectLane::JoinRelay, 6, 3};
    CHECK(slot.on_reply(stale, 7) == JoinObjectSlot::ReplyOutcome::Ignored);
    JoinReply aborted{JoinAuthPhase::EdhocMessage, 3, 9, 0, JoinReplyStatus::Aborted, ObjectLane::JoinRelay, 7, 3};
    CHECK(slot.on_reply(aborted, 8) == JoinObjectSlot::ReplyOutcome::Restart);
    CHECK(slot.pending_mask() == 0x1F);
    JoinReply short_complete{JoinAuthPhase::EdhocMessage, 3, 9, 499, JoinReplyStatus::Complete,
                             ObjectLane::JoinRelay, 7, 3};
    CHECK(slot.on_reply(short_complete, 9) == JoinObjectSlot::ReplyOutcome::Ignored);
    JoinReply done{JoinAuthPhase::EdhocMessage, 3, 9, 500, JoinReplyStatus::Complete, ObjectLane::JoinRelay, 7, 3};
    CHECK(slot.on_reply(done, 9) == JoinObjectSlot::ReplyOutcome::Done);
    CHECK(slot.mode() == JoinObjectSlot::Mode::Idle);
  }
  // Loads refuse objects that fit one frame, RelayStatus, id 0 and bad epochs.
  {
    JoinObjectSlot slot{};
    Bytes small(116, 1);
    CHECK(!slot.load(JoinCarrier::Rld1, JoinAuthPhase::EdhocMessage, 2, 1, 0, 0, view(small), 0)
               .ok());
    Bytes wire_small(128, 1);
    CHECK(!slot.load(JoinCarrier::WireRelay, JoinAuthPhase::EdhocMessage, 2, 1, 7, 3,
                     view(wire_small), 0)
               .ok());
    Bytes big(1025, 1);
    CHECK(!slot.load(JoinCarrier::Rld1, JoinAuthPhase::EdhocMessage, 2, 1, 0, 0, view(big), 0)
               .ok());
    CHECK(!slot.load(JoinCarrier::Rld1, JoinAuthPhase::RelayStatus, 1, 1, 0, 0, view(object), 0)
               .ok());
    CHECK(!slot.load(JoinCarrier::Rld1, JoinAuthPhase::EdhocMessage, 2, 0, 0, 0, view(object), 0)
               .ok());
    CHECK(!slot.load(JoinCarrier::WireRelay, JoinAuthPhase::EdhocMessage, 2, 1, 0, 3,
                     view(object), 0)
               .ok());
    CHECK(!slot.load(JoinCarrier::Rld1, JoinAuthPhase::EdhocMessage, 2, 1, 7, 3, view(object), 0)
               .ok());
    CHECK(slot.mode() == JoinObjectSlot::Mode::Idle);
  }
  // A chunk from another epoch never joins this assembly, and the completed
  // key carries the epochs too.
  {
    JoinObjectSlot slot{};
    Bytes wire_object(300, 0x11);
    JoinChunk first{};
    first.phase = JoinAuthPhase::EdhocMessage;
    first.step = 2;
    first.id = 0x01020304;
    first.gateway_epoch = 7;
    first.proxy_epoch = 3;
    first.total = 300;
    first.offset = 0;
    first.data = ByteView{wire_object.data(), kWireRelayChunkData};
    CHECK(slot.accept(JoinCarrier::WireRelay, first, 0).outcome ==
          JoinObjectSlot::Outcome::Progress);
    JoinChunk foreign = first;
    foreign.proxy_epoch = 4;
    CHECK(slot.accept(JoinCarrier::WireRelay, foreign, 1).outcome ==
          JoinObjectSlot::Outcome::Busy);
    CHECK(slot.mode() == JoinObjectSlot::Mode::Assembling);
  }
}

autonomy::Rld1Envelope env_with(const FrameType kind, std::initializer_list<std::uint8_t> body) {
  autonomy::Rld1Envelope env{};
  env.kind = kind;
  std::size_t i = 0;
  for (const std::uint8_t b : body) env.body[i++] = b;
  env.body_size = i;
  return env;
}

void unit_admission() {
  current = "unit_admission";
  using S = MembershipState;
  const auto tx = AdmissionDirection::Tx;
  const auto rx = AdmissionDirection::Rx;
  // Classification: only the v3 bodies, phases 4-6 and phase-4/5 chunks.
  CHECK(!zt_rld1_frame(env_with(FrameType::Discover, {})));
  CHECK(!zt_rld1_frame(env_with(FrameType::Offer, {1, 0})));
  CHECK(!zt_rld1_frame(env_with(FrameType::Discover, {2, 1})));
  CHECK(zt_rld1_frame(env_with(FrameType::Discover, {3, 3})));
  CHECK(!zt_rld1_frame(env_with(FrameType::BootstrapAuth, {1, 1, 1, 0})));
  CHECK(zt_rld1_frame(env_with(FrameType::BootstrapAuth, {1, 4, 2, 0})));
  CHECK(zt_rld1_frame(env_with(FrameType::BootstrapAuth, {1, 6, 1, 0})));
  CHECK(!zt_rld1_frame(env_with(FrameType::BootstrapAuth, {1, 7, 1, 0})));
  CHECK(!zt_rld1_frame(env_with(FrameType::BootstrapChunk, {1, 1})));
  CHECK(zt_rld1_frame(env_with(FrameType::BootstrapChunk, {1, 0x42})));
  CHECK(!zt_rld1_frame(env_with(FrameType::BootstrapChunk, {1, 0x46})));
  CHECK(!zt_rld1_frame(env_with(FrameType::BootstrapReply, {1, 0x61})));
  CHECK(zt_rld1_frame(env_with(FrameType::BootstrapReply, {1, 0x53})));

  const auto m1 = env_with(FrameType::BootstrapAuth, {1, 4, 1, 0});
  const auto m2 = env_with(FrameType::BootstrapAuth, {1, 4, 2, 0});
  const auto err = env_with(FrameType::BootstrapAuth, {1, 4, 5, 0});
  const auto status = env_with(FrameType::BootstrapAuth, {1, 6, 1, 0});
  const auto m3_chunk = env_with(FrameType::BootstrapChunk, {1, 0x43});
  const auto m3_reply = env_with(FrameType::BootstrapReply, {1, 0x43});
  const auto r2_chunk = env_with(FrameType::BootstrapChunk, {1, 0x52});
  const auto r2_reply = env_with(FrameType::BootstrapReply, {1, 0x52});
  // Joiner (Authenticating): sends up, receives down.
  CHECK(zt_admit_rld1(S::Authenticating, tx, m1).ok());
  CHECK(!zt_admit_rld1(S::Authenticating, rx, m1).ok());
  CHECK(zt_admit_rld1(S::Authenticating, rx, m2).ok());
  CHECK(!zt_admit_rld1(S::Authenticating, tx, m2).ok());
  CHECK(zt_admit_rld1(S::Authenticating, tx, err).ok());
  CHECK(zt_admit_rld1(S::Authenticating, rx, err).ok());
  CHECK(zt_admit_rld1(S::Authenticating, rx, status).ok());
  CHECK(!zt_admit_rld1(S::Authenticating, tx, status).ok());
  CHECK(zt_admit_rld1(S::Authenticating, tx, m3_chunk).ok());
  CHECK(zt_admit_rld1(S::Authenticating, rx, m3_reply).ok());
  CHECK(!zt_admit_rld1(S::Authenticating, tx, m3_reply).ok());
  CHECK(zt_admit_rld1(S::Authenticating, rx, r2_chunk).ok());
  CHECK(zt_admit_rld1(S::Authenticating, tx, r2_reply).ok());
  // Discovering may only discover: the exchange needs Authenticating.
  CHECK(!zt_admit_rld1(S::Discovering, tx, m1).ok());
  CHECK(!zt_admit_rld1(S::Discovering, rx, m2).ok());
  // Proxy (Member): the mirror image.
  CHECK(zt_admit_rld1(S::Member, rx, m1).ok());
  CHECK(!zt_admit_rld1(S::Member, tx, m1).ok());
  CHECK(zt_admit_rld1(S::Member, tx, m2).ok());
  CHECK(zt_admit_rld1(S::Member, tx, status).ok());
  CHECK(!zt_admit_rld1(S::Member, rx, status).ok());
  CHECK(zt_admit_rld1(S::Member, rx, m3_chunk).ok());
  CHECK(zt_admit_rld1(S::Member, tx, m3_reply).ok());
  // Nobody else talks on this lane.
  for (const S state : {S::Unprovisioned, S::AuthorizedPendingCommit, S::Revoked}) {
    CHECK(zt_admit_rld1(state, tx, m1).code == StatusCode::AuthorizationFailed);
    CHECK(zt_admit_rld1(state, rx, m2).code == StatusCode::AuthorizationFailed);
  }
  CHECK(zt_admit_rld1(S::Member, rx, env_with(FrameType::BootstrapAuth, {1, 1, 1, 0})).code ==
        StatusCode::ProtocolError);

  // Wire relay lane.
  const NodeId gateway = 0x00A1000000000001;
  const NodeId proxy = 0x00A1000000000777;
  CHECK(zt_admit_relay(S::Member, false, tx, FrameType::BootstrapAuth, gateway, gateway).ok());
  CHECK(zt_admit_relay(S::Member, false, tx, FrameType::BootstrapChunk, gateway, gateway).ok());
  CHECK(!zt_admit_relay(S::Member, false, tx, FrameType::MembershipResult, gateway, gateway).ok());
  CHECK(!zt_admit_relay(S::Member, false, tx, FrameType::BootstrapAuth, proxy, gateway).ok());
  CHECK(zt_admit_relay(S::Member, false, rx, FrameType::MembershipResult, gateway, gateway).ok());
  CHECK(!zt_admit_relay(S::Member, false, rx, FrameType::BootstrapAuth, proxy, gateway).ok());
  CHECK(zt_admit_relay(S::Member, true, rx, FrameType::BootstrapChunk, proxy, gateway).ok());
  CHECK(!zt_admit_relay(S::Member, true, rx, FrameType::MembershipResult, proxy, gateway).ok());
  CHECK(zt_admit_relay(S::Member, true, tx, FrameType::MembershipResult, proxy, gateway).ok());
  CHECK(zt_admit_relay(S::Member, true, tx, FrameType::Data, proxy, gateway).code ==
        StatusCode::ProtocolError);
  CHECK(!zt_admit_relay(S::Authenticating, true, rx, FrameType::BootstrapChunk, proxy, gateway)
             .ok());
  CHECK(!zt_admit_relay(S::Member, true, rx, FrameType::BootstrapChunk, 0, gateway).ok());
}

void unit_budgets() {
  current = "unit_budgets";
  // 02 §5.3/§6: m1 (P2-3: 59 B with the 5-byte critical labels) plus the
  // 2-byte phase head and the 16-byte cookie fits one RLD1 BootstrapAuth.
  static_assert(kJoinObjectHeadSize + kJoinCookieSize + 59 <= autonomy::kRld1MaxBody,
                "m1 fits one RLD1 frame");
  // One message constant bounds every carrier (02 §5.4 / §7.4).
  static_assert(kJoinObjectHeadSize + kJoinCookieSize + kJoinMessageMax <= kJoinObjectMax, "");
  static_assert(kRelayHeaderSize + kJoinMessageMax <= kJoinObjectMax, "");
  static_assert(join_chunk_count(JoinCarrier::Rld1, kJoinObjectMax) == 10, "");
  static_assert(join_chunk_count(JoinCarrier::WireRelay, kJoinObjectMax) == 10, "");
  // 02 §7.1: m2/m3/m4 near 330-410 B take 4 Wire chunks per hop (110 B grid).
  static_assert(join_chunk_count(JoinCarrier::WireRelay, kRelayHeaderSize + 404) == 4, "");
  static_assert(join_chunk_count(JoinCarrier::WireRelay, kRelayHeaderSize + 330) == 4, "");
  // Encoders refuse what decoders refuse.
  ByteBuffer<kZtDiscoverBodySize> discover{};
  ZtDiscoverBody bad_discover{};
  bad_discover.profile_bits = kJoinProfileRlres1;
  CHECK(zt_discover_body_encode(bad_discover, discover).code == StatusCode::InvalidArgument);
  bad_discover = ZtDiscoverBody{};
  bad_discover.avoid_site_hints = {0, 5};
  CHECK(zt_discover_body_encode(bad_discover, discover).code == StatusCode::InvalidArgument);
  ByteBuffer<kZtOfferBodySize> offer{};
  ZtOfferBody bad_offer{};
  bad_offer.flags = 0x80;
  CHECK(zt_offer_body_encode(bad_offer, offer).code == StatusCode::InvalidArgument);
  autonomy::Rld1Encoded frame{};
  CHECK(!zt_discover_frame_encode(0, JoinNonce{}, ZtDiscoverBody{}, frame).ok());
  CHECK(!zt_offer_frame_encode(1, 0, JoinNonce{}, ZtOfferBody{}, frame).ok());
  std::array<std::uint8_t, 64> out{};
  std::size_t written = 0;
  JoinAuthObject object{};
  object.step = 1;  // m1 without the cookie
  const std::uint8_t message[3] = {1, 2, 3};
  object.message = ByteView{message, 3};
  CHECK(join_object_encode(object, MutableByteView{out.data(), out.size()}, written).code ==
        StatusCode::InvalidArgument);
  object.cookie_present = true;
  CHECK(join_object_encode(object, MutableByteView{out.data(), 10}, written).code ==
        StatusCode::NoCapacity);
  RelayObject relay{};
  relay.header.relay_id = 1;
  relay.header.proxy = 5;
  relay.header.joiner_mac = MacAddress{{2, 0, 0, 0, 0, 1}};
  relay.header.step = 2;  // m2 does not flow up
  relay.message = ByteView{message, 3};
  CHECK(relay_object_encode(relay, MutableByteView{out.data(), out.size()}, written).code ==
        StatusCode::InvalidArgument);
  JoinReply reply{};
  reply.id = 0;
  CHECK(join_reply_encode(JoinCarrier::Rld1, reply, MutableByteView{out.data(), out.size()},
                          written)
            .code == StatusCode::InvalidArgument);
  // The two 24 B epoch datagrams and the relay object classify by kind.
  CHECK(classify_wire_relay(ByteView{}) == WireRelayKind::Invalid);
  const std::uint8_t v1_head[2] = {1, 1};
  CHECK(classify_wire_relay(ByteView{v1_head, 2}) == WireRelayKind::Invalid);
  const std::uint8_t short_query[23] = {2, 3};
  CHECK(classify_wire_relay(ByteView{short_query, 23}) == WireRelayKind::Invalid);
}

void run_valid(const std::filesystem::path& file) {
  const Fields f = parse_flat_json(read_file(file));
  current = file.filename().string();
  CHECK(f.at("expect") == "ok");
  const std::string& codec = f.at("codec");
  if (codec == "zt_discover_frame") {
    valid_discover(f);
  } else if (codec == "zt_offer_frame") {
    valid_offer(f);
  } else if (codec == "cookie") {
    valid_cookie(f);
  } else if (codec == "join_object") {
    valid_object(f);
  } else if (codec == "rld1_object_frames") {
    valid_rld1_frames(f);
  } else if (codec == "join_chunk") {
    valid_chunk(f);
  } else if (codec == "join_reply") {
    valid_reply(f);
  } else if (codec == "relay_object") {
    valid_relay(f);
  } else if (codec == "epoch_query") {
    valid_epoch_query(f);
  } else if (codec == "epoch_reply") {
    valid_epoch_reply(f);
  } else {
    CHECK(!"unknown valid codec");
  }
}

void run_invalid(const std::filesystem::path& file) {
  const Fields f = parse_flat_json(read_file(file));
  current = file.filename().string();
  invalid(f);
}

// The frozen v1 Wire vectors: the v2 entrances reject every one of them,
// never upgrade them by filling epoch 0 (#116 §10.3).
void run_v1_history(const std::filesystem::path& file) {
  const Fields f = parse_flat_json(read_file(file));
  current = file.filename().string();
  const std::string& codec = f.at("codec");
  if (codec == "relay_object") {
    const Bytes encoded = hex(f, "object_hex");
    RelayObject object{};
    CHECK(!relay_object_decode(view(encoded), object).ok());
  } else if (codec == "join_chunk") {
    const Bytes payload = hex(f, "payload_hex");
    JoinChunk chunk{};
    CHECK(!join_chunk_decode(JoinCarrier::WireRelay, view(payload), chunk).ok());
  } else if (codec == "join_reply") {
    const Bytes payload = hex(f, "payload_hex");
    JoinReply reply{};
    CHECK(!join_reply_decode(JoinCarrier::WireRelay, view(payload), reply).ok());
  } else {
    CHECK(!"unknown v1 history codec");
  }
}

void run() {
  const std::filesystem::path root(ROUTELOOM_SDKV1_GOLDEN_DIR);
  const auto valid_files = list_json(root / "join-transport" / "valid");
  const auto invalid_files = list_json(root / "join-transport" / "invalid");
  const auto v2_valid_files = list_json(root / "join-relay-v2" / "valid");
  const auto v2_invalid_files = list_json(root / "join-relay-v2" / "invalid");
  const auto history_files = list_json(root / "join-transport" / "v1-history" / "valid");
  CHECK(valid_files.size() >= 30);
  CHECK(invalid_files.size() >= 100);
  CHECK(v2_valid_files.size() >= 30);
  CHECK(v2_invalid_files.size() >= 80);
  CHECK(history_files.size() == 20);
  for (const auto& path : valid_files) run_valid(path);
  for (const auto& path : v2_valid_files) run_valid(path);
  for (const auto& path : invalid_files) run_invalid(path);
  for (const auto& path : v2_invalid_files) run_invalid(path);
  for (const auto& path : history_files) run_v1_history(path);
  unit_cookie_keying();
  unit_slot();
  unit_admission();
  unit_budgets();
  std::printf("sdkv1 join transport golden: %zu+%zu valid, %zu+%zu invalid, %zu v1-history\n",
              valid_files.size(), v2_valid_files.size(), invalid_files.size(),
              v2_invalid_files.size(), history_files.size());
}

}  // namespace

int main() {
  run();
  if (failures != 0) {
    std::fprintf(stderr, "%d sdkv1 join transport check(s) failed\n", failures);
    return 1;
  }
  std::puts("routeloom_sdkv1_join_transport_tests: ok");
  return 0;
}
