// SDK v1 zero-touch join EAD items (plan P2-3): shared golden vectors in
// protocol/sdkv1-golden/ead/ (generated by tools/gen_sdkv1_ead_vectors.py)
// plus codec unit checks. Valid vectors decode to the listed fields and
// re-encode byte-for-byte (value, EAD item and, for Allow, the MemberCert /
// SitePackage split); RemovalNotice signatures verify under micro-ecc
// (verify-only, like test_sdkv1_golden). Invalid vectors are rejected by the
// decoder ("error") or decode but fail the named authorization step
// ("deny": SiteOffer vs SiteCert, JoinRequest vs DevCert, JoinIntent vs
// Site CA org_hint, RemovalNotice acceptance, and the 02 §10.2 Allow
// checks — acceptance V1-J12).

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "routeloom/rlcw1.hpp"
#include "routeloom/sdkv1_ead.hpp"

#ifndef ROUTELOOM_SDKV1_GOLDEN_DIR
#define ROUTELOOM_SDKV1_GOLDEN_DIR "protocol/sdkv1-golden"
#endif

namespace {

int failures = 0;
std::string current;
#define CHECK(expr)                                                                  \
  do {                                                                               \
    if (!(expr)) {                                                                   \
      std::fprintf(stderr, "CHECK failed %s:%d [%s]: %s\n", __FILE__, __LINE__,      \
                   current.c_str(), #expr);                                          \
      ++failures;                                                                    \
    }                                                                                \
  } while (false)

using namespace routeloom;
using namespace routeloom::sdkv1;
using Fields = std::map<std::string, std::string>;
using Bytes = std::vector<std::uint8_t>;

Fields parse_flat_json(const std::string& text) {
  Fields fields;
  std::size_t pos = 0;
  while (pos < text.size()) {
    const std::size_t key_begin = text.find('"', pos);
    if (key_begin == std::string::npos) break;
    const std::size_t key_end = text.find('"', key_begin + 1);
    if (key_end == std::string::npos) break;
    const std::size_t colon = text.find(':', key_end + 1);
    if (colon == std::string::npos) break;
    std::size_t cursor = colon + 1;
    while (cursor < text.size() && std::isspace(static_cast<unsigned char>(text[cursor]))) {
      ++cursor;
    }
    std::string value;
    if (cursor < text.size() && text[cursor] == '"') {
      const std::size_t value_end = text.find('"', cursor + 1);
      if (value_end == std::string::npos) break;
      value = text.substr(cursor + 1, value_end - cursor - 1);
      pos = value_end + 1;
    } else {
      std::size_t value_end = cursor;
      while (value_end < text.size() &&
             std::isdigit(static_cast<unsigned char>(text[value_end]))) {
        ++value_end;
      }
      value = text.substr(cursor, value_end - cursor);
      pos = value_end;
    }
    fields[text.substr(key_begin + 1, key_end - key_begin - 1)] = value;
  }
  return fields;
}

std::uint64_t num(const Fields& fields, const std::string& key) {
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.empty()) {
    std::fprintf(stderr, "[%s] missing numeric field %s\n", current.c_str(), key.c_str());
    ++failures;
    return 0;
  }
  return std::strtoull(it->second.c_str(), nullptr, 10);
}

Bytes hex(const Fields& fields, const std::string& key) {
  Bytes out;
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.size() % 2 != 0) {
    std::fprintf(stderr, "[%s] missing hex field %s\n", current.c_str(), key.c_str());
    ++failures;
    return out;
  }
  for (std::size_t i = 0; i < it->second.size(); i += 2) {
    out.push_back(
        static_cast<std::uint8_t>(std::strtoul(it->second.substr(i, 2).c_str(), nullptr, 16)));
  }
  return out;
}

template <std::size_t N>
std::array<std::uint8_t, N> hex_array(const Fields& fields, const std::string& key) {
  std::array<std::uint8_t, N> out{};
  const auto bytes = hex(fields, key);
  if (bytes.size() == N) {
    std::copy(bytes.begin(), bytes.end(), out.begin());
  } else {
    std::fprintf(stderr, "[%s] field %s is not %zu bytes\n", current.c_str(), key.c_str(), N);
    ++failures;
  }
  return out;
}

ByteView view(const Bytes& bytes) { return ByteView{bytes.data(), bytes.size()}; }

bool same(const ByteView a, const Bytes& b) {
  return a.size == b.size() && (b.empty() || std::memcmp(a.data, b.data(), b.size()) == 0);
}

template <std::size_t N>
bool equals(const ByteBuffer<N>& buffer, const Bytes& bytes) {
  return same(buffer.view(), bytes);
}

std::string read_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  std::ostringstream contents;
  contents << input.rdbuf();
  return contents.str();
}

std::vector<std::filesystem::path> list_json(const std::filesystem::path& dir) {
  std::vector<std::filesystem::path> files;
  if (!std::filesystem::is_directory(dir)) return files;
  for (const auto& entry : std::filesystem::directory_iterator(dir)) {
    if (entry.path().extension() == ".json") files.push_back(entry.path());
  }
  std::sort(files.begin(), files.end());
  return files;
}

JoinEad label_named(const std::string& name) {
  if (name == "intent") return JoinEad::Intent;
  if (name == "offer") return JoinEad::Offer;
  if (name == "request") return JoinEad::Request;
  return JoinEad::Result;
}

// value + item + EAD field round trip shared by the four item codecs.
void check_item(const Fields& f, const JoinEad label) {
  CHECK(num(f, "label") == static_cast<std::uint32_t>(label));
  const Bytes value = hex(f, "value_hex");
  const Bytes item = hex(f, "item_hex");
  ByteBuffer<kJoinEadItemMax> encoded{};
  CHECK(join_ead_item_encode(label, view(value), encoded).ok());
  CHECK(equals(encoded, item));
  ByteView found{};
  CHECK(join_ead_find(view(item), label, found).ok());
  CHECK(same(found, value));
  // The same item under any other message's expectation is rejected.
  for (const JoinEad other : {JoinEad::Intent, JoinEad::Offer, JoinEad::Request, JoinEad::Result}) {
    if (other != label) CHECK(!join_ead_find(view(item), other, found).ok());
  }
}

CertClaims decode_cert(const Fields& f, const std::string& key) {
  CertClaims claims{};
  CHECK(cert_decode(view(hex(f, key)), claims).ok());
  return claims;
}

SitePackage package_from(const Fields& f) {
  SitePackage p{};
  p.site_id = num(f, "site_id");
  p.network = num(f, "network");
  p.rs_epoch = static_cast<std::uint32_t>(num(f, "rs_epoch"));
  p.gk_epoch = static_cast<std::uint32_t>(num(f, "gk_epoch"));
  p.gk = hex_array<32>(f, "gk_hex");
  p.channel = static_cast<std::uint8_t>(num(f, "channel"));
  p.role = static_cast<std::uint8_t>(num(f, "role"));
  p.gateway_count = static_cast<std::uint8_t>(num(f, "gateway_count"));
  p.channel_epoch = static_cast<std::uint32_t>(num(f, "channel_epoch"));
  for (std::size_t i = 0; i < kSitePackageGatewayMax; ++i) {
    p.gateways[i] = num(f, "gateway" + std::to_string(i));
  }
  p.authority_time_s = num(f, "authority_time_s");
  p.time_uncertainty_ms = static_cast<std::uint32_t>(num(f, "time_uncertainty_ms"));
  p.membership_revision = static_cast<std::uint32_t>(num(f, "membership_revision"));
  return p;
}

bool package_equal(const SitePackage& a, const SitePackage& b) {
  return a.site_id == b.site_id && a.network == b.network && a.rs_epoch == b.rs_epoch &&
         a.gk_epoch == b.gk_epoch && a.gk == b.gk && a.channel == b.channel &&
         a.role == b.role && a.gateway_count == b.gateway_count &&
         a.channel_epoch == b.channel_epoch && a.gateways == b.gateways &&
         a.authority_time_s == b.authority_time_s &&
         a.time_uncertainty_ms == b.time_uncertainty_ms &&
         a.membership_revision == b.membership_revision;
}

// --- valid ------------------------------------------------------------------------

void valid_hint(const Fields& f) {
  CHECK(join_org_hint(hex_array<64>(f, "site_ca_pubkey_hex")) == num(f, "org_hint"));
  CHECK(join_site_hint(num(f, "site_id")) == num(f, "site_hint"));
}

void valid_intent(const Fields& f) {
  JoinIntent intent{};
  CHECK(join_intent_decode(view(hex(f, "value_hex")), intent).ok());
  CHECK(intent.org_hint == num(f, "org_hint"));
  CHECK(intent.profile_bits == num(f, "profile_bits"));
  ByteBuffer<kJoinIntentSize> encoded{};
  CHECK(join_intent_encode(intent, encoded).ok());
  CHECK(equals(encoded, hex(f, "value_hex")));
  check_item(f, JoinEad::Intent);
}

void valid_offer(const Fields& f) {
  SiteOffer offer{};
  CHECK(site_offer_decode(view(hex(f, "value_hex")), offer).ok());
  CHECK(offer.site_id == num(f, "site_id"));
  CHECK(offer.network_low32 == num(f, "network_low32"));
  CHECK(offer.site_epoch == num(f, "site_epoch"));
  CHECK(offer.decision_timeout_ms == num(f, "decision_timeout_ms"));
  ByteBuffer<kSiteOfferSize> encoded{};
  CHECK(site_offer_encode(offer, encoded).ok());
  CHECK(equals(encoded, hex(f, "value_hex")));
  CHECK(site_offer_matches_site_cert(offer, decode_cert(f, "site_cert_hex")).ok());
  check_item(f, JoinEad::Offer);
}

void valid_request(const Fields& f) {
  JoinRequest request{};
  CHECK(join_request_decode(view(hex(f, "value_hex")), request).ok());
  CHECK(request.model == num(f, "model"));
  CHECK(request.fw_version == num(f, "fw_version"));
  CHECK(request.capability == num(f, "capability"));
  CHECK(request.requested_role == num(f, "requested_role"));
  CHECK(request.last_site_id == num(f, "last_site_id"));
  CHECK(request.last_generation == num(f, "last_generation"));
  ByteBuffer<kJoinRequestSize> encoded{};
  CHECK(join_request_encode(request, encoded).ok());
  CHECK(equals(encoded, hex(f, "value_hex")));
  CHECK(join_request_matches_dev_cert(request, decode_cert(f, "dev_cert_hex")).ok());
  check_item(f, JoinEad::Request);
}

void valid_package(const Fields& f) {
  SitePackage decoded{};
  CHECK(site_package_decode(view(hex(f, "value_hex")), decoded).ok());
  CHECK(package_equal(decoded, package_from(f)));
  ByteBuffer<kSitePackageSize> encoded{};
  CHECK(site_package_encode(package_from(f), encoded).ok());
  CHECK(equals(encoded, hex(f, "value_hex")));
}

bool notice_verify(const Fields& f, const Bytes& object, bool& verified) {
  RemovalNotice notice{};
  return removal_notice_verify(view(object), hex_array<64>(f, "signer_pubkey_hex"),
                               num(f, "own_site_id"), num(f, "own_network"), num(f, "own_node"),
                               static_cast<std::uint32_t>(num(f, "own_generation")), notice,
                               verified)
      .ok();
}

void valid_notice(const Fields& f) {
  const Bytes object = hex(f, "object_hex");
  const Bytes payload = hex(f, "payload_hex");
  RemovalNotice notice{};
  CHECK(removal_notice_decode(view(object), notice).ok());
  CHECK(static_cast<std::uint64_t>(notice.reason) == num(f, "reason"));
  CHECK(notice.site_id == num(f, "site_id"));
  CHECK(notice.node_id == num(f, "node_id"));
  CHECK(notice.generation == num(f, "generation"));
  CHECK(notice.rs_epoch == num(f, "rs_epoch"));
  ByteBuffer<kRemovalNoticePayloadSize> encoded{};
  CHECK(removal_notice_payload_encode(notice, encoded).ok());
  CHECK(equals(encoded, payload));
  ByteBuffer<kRemovalNoticeAadSize> aad{};
  CHECK(removal_notice_aad(num(f, "network"), aad).ok());
  CHECK(equals(aad, hex(f, "aad_hex")));
  Bytes structure(256);
  std::size_t structure_size = 0;
  CHECK(cose_es256_sig_structure(view(payload), aad.view(),
                                 MutableByteView{structure.data(), structure.size()},
                                 structure_size)
            .ok());
  structure.resize(structure_size);
  CHECK(structure == hex(f, "sig_structure_hex"));
  ByteBuffer<kRemovalNoticeObjectSize> assembled{};
  CHECK(removal_notice_assemble(view(payload), view(hex(f, "signature_hex")), assembled).ok());
  CHECK(equals(assembled, object));
  bool verified = false;
  CHECK(notice_verify(f, object, verified));
  CHECK(verified);
}

bool allow_verified(const Fields& f, const JoinResult& result, Status* status_out = nullptr) {
  CertClaims member{};
  bool verified = false;
  const Status status =
      join_allow_verify(result, decode_cert(f, "site_cert_hex"), num(f, "node"),
                        hex_array<64>(f, "device_pubkey_hex"), num(f, "strict_assignment") != 0,
                        member, verified);
  if (status_out != nullptr) *status_out = status;
  return status.ok() && verified;
}

void valid_result(const Fields& f) {
  const Bytes value = hex(f, "value_hex");
  JoinResult result{};
  CHECK(join_result_decode(view(value), result).ok());
  CHECK(static_cast<std::uint64_t>(result.verdict) == num(f, "verdict"));
  CHECK(result.retry_after_s == num(f, "retry_after_s"));
  CHECK(value.size() == kJoinResultHeadSize + num(f, "body_len"));
  CHECK(join_result_encoded_size(result) == value.size());
  ByteBuffer<kJoinResultMax> encoded{};
  CHECK(join_result_encode(result, encoded).ok());
  CHECK(equals(encoded, value));
  switch (result.verdict) {
    case JoinVerdict::Allow: {
      CHECK(same(result.member_cert, hex(f, "member_cert_hex")));
      CHECK(same(result.assignment_ticket, hex(f, "assignment_ticket_hex")));
      ByteBuffer<kSitePackageSize> package{};
      CHECK(site_package_encode(result.site_package, package).ok());
      CHECK(equals(package, hex(f, "site_package_hex")));
      CHECK(allow_verified(f, result) == (num(f, "verified") == 1));
      break;
    }
    case JoinVerdict::PendingAssignment:
      CHECK(same(result.pending_ticket, hex(f, "pending_ticket_hex")));
      break;
    case JoinVerdict::Removed: {
      CHECK(same(result.removal_notice, hex(f, "removal_notice_hex")));
      bool verified = false;
      CHECK(notice_verify(f, hex(f, "removal_notice_hex"), verified));
      CHECK(verified);
      break;
    }
    default:
      CHECK(result.member_cert.size == 0 && result.pending_ticket.size == 0 &&
            result.removal_notice.size == 0);
      break;
  }
  check_item(f, JoinEad::Result);
}

void valid_field(const Fields& f) {
  const Bytes ead = hex(f, "ead_hex");
  ByteView value{};
  CHECK(join_ead_find(view(ead), label_named(f.at("expected")), value).ok());
  CHECK(same(value, hex(f, "value_hex")));
}

CertType cert_type_named(const std::string& name) {
  if (name == "site") return CertType::Site;
  if (name == "device") return CertType::Device;
  return CertType::Member;
}

// P3-1: EAD_2/EAD_3 carry the peer's RLCW1 certificate in the critical
// Credential item (label 65541) ahead of the message item; the certificate
// must match the kid the same message's ID_CRED_x names.
void valid_field_credential(const Fields& f) {
  const Bytes ead = hex(f, "ead_hex");
  const JoinEad expected = label_named(f.at("expected"));
  ByteView credential{};
  ByteView value{};
  CHECK(join_ead_find_with_credential(view(ead), expected, credential, value).ok());
  CHECK(same(credential, hex(f, "credential_hex")));
  CHECK(same(value, hex(f, "value_hex")));
  CHECK(num(f, "label") == static_cast<std::uint32_t>(JoinEad::Credential));
  // The plain single-item walk refuses a field that carries a Credential.
  ByteView plain{};
  CHECK(!join_ead_find(view(ead), expected, plain).ok());
  ByteBuffer<kJoinEadItemMax> item{};
  CHECK(join_ead_item_encode(JoinEad::Credential, credential, item).ok());
  CHECK(same(item.view(), hex(f, "credential_item_hex")));
  CertClaims claims{};
  const Bytes kid = hex(f, "kid_hex");
  CHECK(join_credential_check(credential, cert_type_named(f.at("cert_type")), view(kid), claims)
            .ok());
  CHECK(claims.type == cert_type_named(f.at("cert_type")));
  // Swapping the expected message fails.
  CHECK(!join_ead_find_with_credential(
             view(ead), expected == JoinEad::Offer ? JoinEad::Request : JoinEad::Offer,
             credential, value)
             .ok());
  CHECK(join_ead_find_with_credential(view(ead), JoinEad::Intent, credential, value).code ==
        StatusCode::InvalidArgument);
}

// --- invalid ----------------------------------------------------------------------

void invalid(const Fields& f) {
  const std::string& codec = f.at("codec");
  const bool deny = f.at("expect") == "deny";
  CHECK(deny || f.at("expect") == "error");
  const Bytes encoded = hex(f, "encoded_hex");
  const ByteView input = view(encoded);
  if (codec == "join_intent") {
    JoinIntent intent{};
    const bool ok = join_intent_decode(input, intent).ok();
    CHECK(ok == deny);
    if (deny) CHECK(intent.org_hint != join_org_hint(hex_array<64>(f, "site_ca_pubkey_hex")));
  } else if (codec == "site_offer") {
    SiteOffer offer{};
    const bool ok = site_offer_decode(input, offer).ok();
    CHECK(ok == deny);
    if (deny) {
      const Status match = site_offer_matches_site_cert(offer, decode_cert(f, "site_cert_hex"));
      CHECK(match.code == StatusCode::AuthorizationFailed);
    }
  } else if (codec == "join_request") {
    JoinRequest request{};
    const bool ok = join_request_decode(input, request).ok();
    CHECK(ok == deny);
    if (deny) {
      const Status match = join_request_matches_dev_cert(request, decode_cert(f, "dev_cert_hex"));
      CHECK(match.code == StatusCode::AuthorizationFailed);
    }
  } else if (codec == "site_package") {
    CHECK(!deny);
    SitePackage package{};
    CHECK(!site_package_decode(input, package).ok());
  } else if (codec == "removal_notice") {
    RemovalNotice notice{};
    CHECK(removal_notice_decode(input, notice).ok() == deny);
    bool verified = true;
    const bool status_ok = notice_verify(f, encoded, verified);
    CHECK(status_ok == deny);
    CHECK(!verified);
  } else if (codec == "join_result") {
    JoinResult result{};
    const bool ok = join_result_decode(input, result).ok();
    CHECK(ok == deny);
    if (deny) {
      Status status{};
      CHECK(!allow_verified(f, result, &status));
      CHECK(status.ok());  // a denial, not a malformed input
    }
  } else if (codec == "ead_field") {
    CHECK(!deny);
    ByteView value{};
    CHECK(!join_ead_find(input, label_named(f.at("expected")), value).ok());
    CHECK(value.size == 0);
  } else if (codec == "ead_field_credential") {
    CHECK(!deny);
    ByteView credential{};
    ByteView value{};
    CHECK(!join_ead_find_with_credential(input, label_named(f.at("expected")), credential, value)
               .ok());
    CHECK(credential.size == 0 && value.size == 0);
  } else if (codec == "credential") {
    CertClaims claims{};
    const Bytes kid = hex(f, "kid_hex");
    const Status status =
        join_credential_check(input, cert_type_named(f.at("cert_type")), view(kid), claims);
    CHECK(!status.ok());
    CHECK(deny == (status.code == StatusCode::AuthenticationFailed));
  } else {
    CHECK(!"unknown invalid codec");
  }
}

// --- unit checks ------------------------------------------------------------------

void unit_checks() {
  current = "unit";
  // Encoders refuse what decoders refuse.
  ByteBuffer<kJoinIntentSize> intent_out{};
  CHECK(join_intent_encode(JoinIntent{0, 0}, intent_out).code == StatusCode::InvalidArgument);
  ByteBuffer<kSiteOfferSize> offer_out{};
  CHECK(site_offer_encode(SiteOffer{}, offer_out).code == StatusCode::InvalidArgument);
  ByteBuffer<kJoinRequestSize> request_out{};
  JoinRequest request{};
  request.requested_role = 0;
  CHECK(join_request_encode(request, request_out).code == StatusCode::InvalidArgument);
  ByteBuffer<kSitePackageSize> package_out{};
  CHECK(site_package_encode(SitePackage{}, package_out).code == StatusCode::InvalidArgument);
  ByteBuffer<kRemovalNoticePayloadSize> notice_out{};
  CHECK(removal_notice_payload_encode(RemovalNotice{}, notice_out).code ==
        StatusCode::InvalidArgument);
  ByteBuffer<kJoinResultMax> result_out{};
  JoinResult pending{};
  pending.verdict = JoinVerdict::PendingAssignment;
  pending.retry_after_s = 60;
  CHECK(join_result_encode(pending, result_out).code == StatusCode::InvalidArgument);  // no ticket
  JoinResult deny{};
  CHECK(join_result_encode(deny, result_out).ok());
  CHECK(result_out.size == kJoinResultHeadSize);
  const std::uint8_t ticket[1] = {7};
  deny.pending_ticket = ByteView{ticket, 1};
  CHECK(join_result_encode(deny, result_out).code == StatusCode::InvalidArgument);
  ByteBuffer<kJoinEadItemMax> item{};
  CHECK(join_ead_item_encode(JoinEad::Intent, ByteView{ticket, 1}, item).code ==
        StatusCode::InvalidArgument);
  ByteView value{};
  CHECK(!join_ead_find(ByteView{}, JoinEad::Intent, value).ok());

  // Message budgets (02 §5.3/§6, V1-J14 EAD part). m1 = METHOD 1 + SUITES_I 1
  // + G_X bstr 34 + C_I (4-byte bstr) 5 + EAD_1 item; with the 2-byte phase
  // prefix and the 16-byte cookie it must fit one RLD1 BootstrapAuth body
  // (116 - 4 = 112 B).
  constexpr std::size_t kIntentItem = kJoinEadLabelSize + 1 + kJoinIntentSize;
  static_assert(kIntentItem == 18, "EAD_1 item");
  constexpr std::size_t kM1 = 1 + 1 + 34 + 5 + kIntentItem;
  static_assert(2 + 16 + kM1 <= 112, "m1 fits one RLD1 frame");
  static_assert(kJoinEadLabelSize + 1 + kSiteOfferSize == 28, "EAD_2 item");
  static_assert(kJoinEadLabelSize + 2 + kJoinRequestSize == 33, "EAD_3 item");
  // m4 allow with the largest v1 MemberCert (208 B), no ticket: EAD_4 item
  // + CIPHERTEXT_4 bstr head (3) + tag (8) stays within the 02 §6 estimate
  // (~355 B) plus the certificate's 10-byte headroom.
  constexpr std::size_t kAllowItem =
      kJoinEadLabelSize + 3 + kJoinResultHeadSize + 2 + kRlcw1CertLargest + kSitePackageSize + 2;
  static_assert(kAllowItem + 3 + 8 <= 365, "m4 allow budget");
  static_assert(kJoinEadItemMax <= kJoinEadFieldMax, "largest item fits a field");
  // Pending/deny m4 (02 §6: ~70-100 B).
  static_assert(kJoinEadLabelSize + 2 + kJoinResultHeadSize + kPendingTicketMax + 3 + 8 <= 100,
                "m4 pending budget");
}

void unit_allow_strict(const Fields& f) {
  // A2 with a ticket present: the ticket format is not pinned, so the
  // device fails closed with Unsupported rather than accepting it.
  const Bytes value = hex(f, "value_hex");
  JoinResult result{};
  CHECK(join_result_decode(view(value), result).ok());
  CertClaims member{};
  bool verified = true;
  const Status status =
      join_allow_verify(result, decode_cert(f, "site_cert_hex"), num(f, "node"),
                        hex_array<64>(f, "device_pubkey_hex"), true, member, verified);
  CHECK(status.code == StatusCode::Unsupported);
  CHECK(!verified);
  // A non-Allow result is an argument error.
  JoinResult deny{};
  CHECK(join_allow_verify(deny, decode_cert(f, "site_cert_hex"), num(f, "node"),
                          hex_array<64>(f, "device_pubkey_hex"), false, member, verified)
            .code == StatusCode::InvalidArgument);
}

void run() {
  const std::filesystem::path dir = std::filesystem::path(ROUTELOOM_SDKV1_GOLDEN_DIR) / "ead";
  const auto valid_files = list_json(dir / "valid");
  const auto invalid_files = list_json(dir / "invalid");
  CHECK(valid_files.size() >= 30);
  CHECK(invalid_files.size() >= 120);
  for (const auto& path : valid_files) {
    const Fields f = parse_flat_json(read_file(path));
    current = path.filename().string();
    CHECK(f.at("expect") == "ok");
    const std::string& codec = f.at("codec");
    if (codec == "hint") {
      valid_hint(f);
    } else if (codec == "join_intent") {
      valid_intent(f);
    } else if (codec == "site_offer") {
      valid_offer(f);
    } else if (codec == "join_request") {
      valid_request(f);
    } else if (codec == "site_package") {
      valid_package(f);
    } else if (codec == "removal_notice") {
      valid_notice(f);
    } else if (codec == "join_result") {
      valid_result(f);
      if (f.at("name") == "join_result_allow_with_ticket") unit_allow_strict(f);
    } else if (codec == "ead_field") {
      valid_field(f);
    } else if (codec == "ead_field_credential") {
      valid_field_credential(f);
    } else {
      CHECK(!"unknown valid codec");
    }
  }
  for (const auto& path : invalid_files) {
    const Fields f = parse_flat_json(read_file(path));
    current = path.filename().string();
    invalid(f);
  }
  unit_checks();
  std::printf("sdkv1 ead golden: %zu valid, %zu invalid vectors\n", valid_files.size(),
              invalid_files.size());
}

}  // namespace

int main() {
  run();
  if (failures != 0) {
    std::fprintf(stderr, "%d sdkv1 ead check(s) failed\n", failures);
    return 1;
  }
  std::puts("routeloom_sdkv1_ead_tests: ok");
  return 0;
}
