// SDK v1 shared golden vectors (protocol/sdkv1-golden/, generated by
// tools/gen_sdkv1_vectors.py): RLCW1 certificates, RLI1, RLS1, RRS1 (payload,
// AAD, Sig_structure, Sign1 object, storage record) and RLP1. Valid vectors
// must decode to the listed fields and re-encode byte-for-byte; signatures
// must verify under the vendored micro-ecc (the C++ side is verify-only: its
// deterministic signer is not RFC 6979 — the Rust harness re-signs). Invalid
// vectors must be rejected ("error") or decode but fail verification ("deny").

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "routeloom/rlcw1.hpp"
#include "routeloom/sdkv1_records.hpp"

extern "C" {
#include "uECC.h"
}

#ifndef ROUTELOOM_SDKV1_GOLDEN_DIR
#define ROUTELOOM_SDKV1_GOLDEN_DIR "protocol/sdkv1-golden"
#endif

namespace {

int failures = 0;
std::string current;
#define CHECK(expr)                                                                  \
  do {                                                                               \
    if (!(expr)) {                                                                   \
      std::fprintf(stderr, "CHECK failed %s:%d [%s]: %s\n", __FILE__, __LINE__,      \
                   current.c_str(), #expr);                                          \
      ++failures;                                                                    \
    }                                                                                \
  } while (false)

using namespace routeloom;
using namespace routeloom::sdkv1;
using Fields = std::map<std::string, std::string>;

Fields parse_flat_json(const std::string& text) {
  Fields fields;
  std::size_t pos = 0;
  while (pos < text.size()) {
    const std::size_t key_begin = text.find('"', pos);
    if (key_begin == std::string::npos) break;
    const std::size_t key_end = text.find('"', key_begin + 1);
    if (key_end == std::string::npos) break;
    const std::size_t colon = text.find(':', key_end + 1);
    if (colon == std::string::npos) break;
    std::size_t cursor = colon + 1;
    while (cursor < text.size() && std::isspace(static_cast<unsigned char>(text[cursor]))) {
      ++cursor;
    }
    std::string value;
    if (cursor < text.size() && text[cursor] == '"') {
      const std::size_t value_end = text.find('"', cursor + 1);
      if (value_end == std::string::npos) break;
      value = text.substr(cursor + 1, value_end - cursor - 1);
      pos = value_end + 1;
    } else {
      std::size_t value_end = cursor;
      while (value_end < text.size() &&
             std::isdigit(static_cast<unsigned char>(text[value_end]))) {
        ++value_end;
      }
      value = text.substr(cursor, value_end - cursor);
      pos = value_end;
    }
    fields[text.substr(key_begin + 1, key_end - key_begin - 1)] = value;
  }
  return fields;
}

bool has(const Fields& fields, const std::string& key) { return fields.count(key) != 0; }

std::uint64_t num(const Fields& fields, const std::string& key) {
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.empty()) {
    std::fprintf(stderr, "[%s] missing numeric field %s\n", current.c_str(), key.c_str());
    ++failures;
    return 0;
  }
  return std::strtoull(it->second.c_str(), nullptr, 10);
}

std::vector<std::uint8_t> hex(const Fields& fields, const std::string& key) {
  std::vector<std::uint8_t> out;
  const auto it = fields.find(key);
  if (it == fields.end() || it->second.size() % 2 != 0) {
    std::fprintf(stderr, "[%s] missing hex field %s\n", current.c_str(), key.c_str());
    ++failures;
    return out;
  }
  for (std::size_t i = 0; i < it->second.size(); i += 2) {
    out.push_back(static_cast<std::uint8_t>(std::strtoul(it->second.substr(i, 2).c_str(), nullptr, 16)));
  }
  return out;
}

template <std::size_t N>
std::array<std::uint8_t, N> hex_array(const Fields& fields, const std::string& key) {
  std::array<std::uint8_t, N> out{};
  const auto bytes = hex(fields, key);
  if (bytes.size() == N) {
    std::copy(bytes.begin(), bytes.end(), out.begin());
  } else {
    std::fprintf(stderr, "[%s] field %s is not %zu bytes\n", current.c_str(), key.c_str(), N);
    ++failures;
  }
  return out;
}

ByteView view(const std::vector<std::uint8_t>& bytes) {
  return ByteView{bytes.data(), bytes.size()};
}

template <std::size_t N>
bool equals(const ByteBuffer<N>& buffer, const std::vector<std::uint8_t>& bytes) {
  return buffer.size == bytes.size() &&
         std::equal(bytes.begin(), bytes.end(), buffer.bytes.begin());
}

std::string read_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  std::ostringstream contents;
  contents << input.rdbuf();
  return contents.str();
}

std::vector<std::filesystem::path> list_json(const std::filesystem::path& dir) {
  std::vector<std::filesystem::path> files;
  if (!std::filesystem::is_directory(dir)) return files;
  for (const auto& entry : std::filesystem::directory_iterator(dir)) {
    if (entry.path().extension() == ".json") files.push_back(entry.path());
  }
  std::sort(files.begin(), files.end());
  return files;
}

// --- valid ---------------------------------------------------------------------

void valid_cert(const Fields& f) {
  const auto cert = hex(f, "cert_hex");
  CertClaims claims{};
  CHECK(cert_decode(view(cert), claims).ok());
  CHECK(static_cast<std::uint64_t>(claims.type) == num(f, "cert_type"));
  CHECK(claims.issuer == num(f, "issuer"));
  CHECK(claims.subject == num(f, "subject"));
  CHECK(claims.pubkey == (hex_array<64>(f, "pubkey_hex")));
  CHECK(claims.model == num(f, "model"));
  CHECK(claims.hw_rev == num(f, "hw_rev"));
  CHECK(claims.network_low32 == num(f, "network_low32"));
  CHECK(claims.usage == num(f, "usage"));
  CHECK(claims.network == num(f, "network"));
  CHECK(claims.role == num(f, "role"));
  CHECK(claims.assignment_generation == num(f, "assignment_generation"));
  CHECK(claims.site_epoch == num(f, "site_epoch"));
  CHECK(claims.serial == num(f, "serial"));

  ByteBuffer<kRlcw1PayloadMax> payload{};
  CHECK(cert_payload_encode(claims, payload).ok());
  CHECK(equals(payload, hex(f, "payload_hex")));
  ByteBuffer<kRlcw1SigStructureMax> structure{};
  CHECK(cert_sig_structure(payload.view(), structure).ok());
  CHECK(equals(structure, hex(f, "sig_structure_hex")));
  const auto signature = hex(f, "signature_hex");
  ByteBuffer<kRlcw1CertMax> assembled{};
  CHECK(cert_assemble(payload.view(), view(signature), assembled).ok());
  CHECK(equals(assembled, cert));
  CHECK(assembled.size <= kRlcw1CertLargest);

  // The signer key is the fixed test scalar; its public half must match.
  const auto secret = hex_array<32>(f, "signer_secret_hex");
  P256PublicKey signer{};
  CHECK(uECC_compute_public_key(secret.data(), signer.data(), uECC_secp256r1()) != 0);
  CHECK(signer == (hex_array<64>(f, "signer_pubkey_hex")));
  bool verified = false;
  CertClaims again{};
  CHECK(cert_verify(view(cert), signer, again, verified).ok());
  CHECK(verified);
  CHECK(es256_signature_canonical(view(signature)));
  Digest256 kid{};
  CHECK(cert_subject_kid(claims, kid).ok());
  CHECK(kid == (hex_array<32>(f, "subject_kid_hex")));
}

void valid_rli1(const Fields& f) {
  const auto record = hex(f, "record_hex");
  IdentityRecord identity{};
  CHECK(identity_record_decode(view(record), identity).ok());
  CHECK(identity.node_id == num(f, "node_id"));
  CHECK(static_cast<std::uint64_t>(identity.key_location) == num(f, "key_location"));
  CHECK(identity.flags == num(f, "flags"));
  CHECK(identity.kid == (hex_array<32>(f, "kid_hex")));
  CHECK(identity.pubkey == (hex_array<64>(f, "pubkey_hex")));
  CHECK(identity.key_material == (hex_array<32>(f, "key_material_hex")));
  CHECK(identity.anchor_count == num(f, "anchor_count"));
  for (std::uint8_t i = 0; i < identity.anchor_count && i < kIdentityAnchorMax; ++i) {
    const std::string prefix = "anchor" + std::to_string(i) + "_";
    CHECK(identity.anchors[i].anchor_id == num(f, prefix + "id"));
    CHECK(static_cast<std::uint64_t>(identity.anchors[i].kind) == num(f, prefix + "kind"));
    CHECK(static_cast<std::uint64_t>(identity.anchors[i].status) == num(f, prefix + "status"));
    CHECK(identity.anchors[i].pubkey == (hex_array<64>(f, prefix + "pubkey_hex")));
  }
  CHECK(equals(identity.devcert, hex(f, "devcert_hex")));
  ByteBuffer<kIdentitySlotBytes> encoded{};
  CHECK(identity_record_encode(identity, kIdentitySealCommitted, encoded).ok());
  CHECK(equals(encoded, record));
  CHECK(identity_record_structure(view(record)).ok());
}

void valid_rls1(const Fields& f) {
  const auto record = hex(f, "record_hex");
  SiteRecord site{};
  std::uint32_t seq = 0;
  CHECK(site_record_decode(view(record), site, &seq).ok());
  CHECK(seq == num(f, "commit_seq"));
  CHECK(static_cast<std::uint64_t>(site.state) == num(f, "state"));
  CHECK(site.site_id == num(f, "site_id"));
  CHECK(site.network == num(f, "network"));
  CHECK(site.assignment_generation == num(f, "assignment_generation"));
  CHECK(site.rs_epoch_floor == num(f, "rs_epoch_floor"));
  CHECK(site.gk_epoch_current == num(f, "gk_epoch_current"));
  CHECK(site.gk_epoch_next == num(f, "gk_epoch_next"));
  CHECK(site.gk_current == (hex_array<32>(f, "gk_current_hex")));
  CHECK(site.gk_next == (hex_array<32>(f, "gk_next_hex")));
  CHECK(site.dams == (hex_array<32>(f, "dams_hex")));
  CHECK(site.role == num(f, "role"));
  CHECK(site.gateway_count == num(f, "gateway_count"));
  CHECK(site.channel == num(f, "channel"));
  CHECK(site.channel_epoch == num(f, "channel_epoch"));
  CHECK(site.boot_witness == num(f, "boot_witness"));
  for (std::size_t i = 0; i < kSiteGatewayMax; ++i) {
    CHECK(site.gateways[i] == num(f, "gateway" + std::to_string(i)));
  }
  CHECK(equals(site.site_cert, hex(f, "site_cert_hex")));
  CHECK(equals(site.member_cert, hex(f, "member_cert_hex")));
  ByteBuffer<kSiteSlotBytes> encoded{};
  CHECK(site_record_encode(site, kSiteSealCommitted, seq, encoded).ok());
  CHECK(equals(encoded, record));
  CHECK(site_record_structure(view(record)).ok());
}

void valid_rrs1(const Fields& f) {
  const auto payload = hex(f, "payload_hex");
  RevocationSet set{};
  CHECK(revocation_payload_decode(view(payload), set).ok());
  CHECK(set.site_id == num(f, "site_id"));
  CHECK(set.network == num(f, "network"));
  CHECK(set.rs_epoch == num(f, "rs_epoch"));
  CHECK(set.site_epoch_floor == num(f, "site_epoch_floor"));
  CHECK(set.count == num(f, "count"));
  for (std::uint8_t i = 0; i < set.count && i < kRevocationEntryMax; ++i) {
    char prefix[16];
    std::snprintf(prefix, sizeof(prefix), "entry%02u_", static_cast<unsigned>(i));
    CHECK(set.entries[i].node_id == num(f, std::string(prefix) + "node"));
    CHECK(set.entries[i].min_generation == num(f, std::string(prefix) + "min_generation"));
    CHECK(static_cast<std::uint64_t>(set.entries[i].reason) ==
          num(f, std::string(prefix) + "reason"));
  }
  ByteBuffer<kRevocationPayloadMax> encoded{};
  CHECK(revocation_payload_encode(set, encoded).ok());
  CHECK(equals(encoded, payload));
  ByteBuffer<kRevocationAadSize> aad{};
  CHECK(revocation_aad(set.network, aad).ok());
  CHECK(equals(aad, hex(f, "aad_hex")));
  std::array<std::uint8_t, 700> structure{};
  std::size_t structure_size = 0;
  CHECK(cose_es256_sig_structure(view(payload), aad.view(),
                                 MutableByteView{structure.data(), structure.size()},
                                 structure_size)
            .ok());
  const auto expected_structure = hex(f, "sig_structure_hex");
  CHECK(structure_size == expected_structure.size() &&
        std::equal(expected_structure.begin(), expected_structure.end(), structure.begin()));
  const auto object = hex(f, "object_hex");
  ByteBuffer<kRevocationObjectMax> assembled{};
  CHECK(revocation_object_assemble(view(payload), view(hex(f, "signature_hex")), assembled).ok());
  CHECK(equals(assembled, object));
  RevocationSet verified_set{};
  bool verified = false;
  CHECK(revocation_object_verify(view(object), hex_array<64>(f, "signer_pubkey_hex"),
                                 set.site_id, set.network, verified_set, verified)
            .ok());
  CHECK(verified);
  const auto record = hex(f, "record_hex");
  ByteBuffer<kRevocationSlotBytes> stored{};
  CHECK(revocation_record_encode(view(object), kRevocationSealCommitted,
                                 static_cast<std::uint32_t>(num(f, "commit_seq")), stored)
            .ok());
  CHECK(equals(stored, record));
  RevocationSet from_record{};
  ByteView stored_object{};
  std::uint32_t seq = 0;
  CHECK(revocation_record_decode(view(record), from_record, stored_object, &seq).ok());
  CHECK(seq == num(f, "commit_seq"));
  CHECK(stored_object.size == object.size());
  CHECK(from_record.rs_epoch == set.rs_epoch);
}

void valid_rrs1_record(const Fields& f) {
  const auto record = hex(f, "record_hex");
  RevocationSet set{};
  ByteView object{};
  std::uint32_t seq = 0;
  CHECK(revocation_record_decode(view(record), set, object, &seq).ok());
  CHECK(object.size == 0);
  CHECK(seq == num(f, "commit_seq"));
  ByteBuffer<kRevocationSlotBytes> stored{};
  CHECK(revocation_record_encode(ByteView{}, kRevocationSealCommitted, seq, stored).ok());
  CHECK(equals(stored, record));
}

void valid_rlp1(const Fields& f) {
  const auto record = hex(f, "record_hex");
  ResumeSlot slot{};
  CHECK(resume_slot_decode(view(record), slot).ok());
  CHECK(slot.valid == (num(f, "state") == 1));
  if (slot.valid) CHECK(static_cast<std::uint64_t>(slot.purpose) == num(f, "purpose"));
  CHECK(slot.flags == num(f, "flags"));
  CHECK(slot.peer == num(f, "peer"));
  CHECK(slot.network == num(f, "network"));
  CHECK(slot.peer_cert_id == (hex_array<8>(f, "peer_cert_id_hex")));
  CHECK(slot.peer_generation == num(f, "peer_generation"));
  CHECK(slot.created_gk_epoch == num(f, "created_gk_epoch"));
  CHECK(slot.last_used_boot == num(f, "last_used_boot"));
  CHECK(slot.rms == (hex_array<32>(f, "rms_hex")));
  std::array<std::uint8_t, kResumeSlotBytes> encoded{};
  CHECK(resume_slot_encode(slot, encoded).ok());
  CHECK(record.size() == encoded.size() && std::equal(record.begin(), record.end(), encoded.begin()));
  if (has(f, "peer_cert_hex")) {
    std::array<std::uint8_t, 8> id{};
    resume_peer_cert_id(view(hex(f, "peer_cert_hex")), id);
    CHECK(id == slot.peer_cert_id);
  }
}

// --- invalid -------------------------------------------------------------------

void invalid(const Fields& f, const std::string& codec, const std::string& expect) {
  const auto bytes = hex(f, "encoded_hex");
  const bool deny = expect == "deny";
  CHECK(deny || expect == "error");
  if (codec == "rlcw1") {
    CertClaims claims{};
    bool verified = true;
    const Status status = cert_verify(view(bytes), hex_array<64>(f, "signer_pubkey_hex"),
                                      claims, verified);
    if (deny) {
      CHECK(status.ok());
      CHECK(!verified);
    } else {
      CHECK(!status.ok());
      CHECK(!cert_decode(view(bytes), claims).ok());
    }
  } else if (codec == "rli1") {
    IdentityRecord record{};
    CHECK(!identity_record_decode(view(bytes), record).ok());
  } else if (codec == "rls1") {
    SiteRecord record{};
    CHECK(!site_record_decode(view(bytes), record).ok());
  } else if (codec == "rrs1") {
    RevocationSet set{};
    bool verified = true;
    const Status status =
        revocation_object_verify(view(bytes), hex_array<64>(f, "signer_pubkey_hex"),
                                 num(f, "expected_site_id"), num(f, "expected_network"), set,
                                 verified);
    if (deny) {
      CHECK(status.ok());
      CHECK(!verified);
    } else {
      CHECK(!status.ok());
      CHECK(!revocation_object_decode(view(bytes), set).ok());
    }
  } else if (codec == "rrs1_record") {
    RevocationSet set{};
    ByteView object{};
    CHECK(!revocation_record_decode(view(bytes), set, object).ok());
  } else if (codec == "rlp1") {
    ResumeSlot slot{};
    CHECK(!resume_slot_decode(view(bytes), slot).ok());
  } else {
    CHECK(!"unknown invalid codec");
  }
}

void run() {
  const std::filesystem::path dir(ROUTELOOM_SDKV1_GOLDEN_DIR);
  const auto valid_files = list_json(dir / "valid");
  const auto invalid_files = list_json(dir / "invalid");
  CHECK(valid_files.size() >= 15);
  CHECK(invalid_files.size() >= 60);
  for (const auto& path : valid_files) {
    const Fields f = parse_flat_json(read_file(path));
    current = path.filename().string();
    CHECK(f.at("expect") == "ok");
    const std::string& codec = f.at("codec");
    if (codec == "rlcw1") {
      valid_cert(f);
    } else if (codec == "rli1") {
      valid_rli1(f);
    } else if (codec == "rls1") {
      valid_rls1(f);
    } else if (codec == "rrs1") {
      valid_rrs1(f);
    } else if (codec == "rrs1_record") {
      valid_rrs1_record(f);
    } else if (codec == "rlp1") {
      valid_rlp1(f);
    } else {
      CHECK(!"unknown valid codec");
    }
  }
  for (const auto& path : invalid_files) {
    const Fields f = parse_flat_json(read_file(path));
    current = path.filename().string();
    invalid(f, f.at("codec"), f.at("expect"));
  }
  std::printf("sdkv1 golden: %zu valid, %zu invalid vectors\n", valid_files.size(),
              invalid_files.size());
}

}  // namespace

int main() {
  run();
  if (failures != 0) {
    std::fprintf(stderr, "%d sdkv1 golden check(s) failed\n", failures);
    return 1;
  }
  std::puts("routeloom_sdkv1_golden_tests: ok");
  return 0;
}
