//! Generated by tools/gen_manifest.py from protocol/manifest.json. Do not edit.

pub const SDK_VERSION: &str = "2.0.0-dev";

/// Core C ABI.
pub const CORE_C_ABI: u32 = 2;
/// Mesh wire major.
pub const WIRE_MAJOR: u32 = 2;
/// Mesh wire minor.
pub const WIRE_MINOR: u32 = 0;
/// RLD1 carrier.
pub const RLD1_VERSION: u32 = 1;
/// RLD1 ZeroTouch body.
pub const RLD1_ZT_BODY: u32 = 3;
/// HostLink (RLU1) protocol.
pub const HOSTLINK_PROTOCOL: u32 = 1;
/// HostOps schema.
pub const HOSTOPS_SCHEMA: u32 = 1;
/// HostOps join relay schema.
pub const HOSTOPS_JOIN_RELAY_SCHEMA: u32 = 2;
/// AuthorityEnvelope.
pub const AUTHORITY_ENVELOPE: u32 = 1;
/// API1 envelope.
pub const API1_ENVELOPE: u32 = 1;
/// API1 caps_version.
pub const API1_CAPS: u32 = 1;
/// Authority ledger (device).
pub const STORE_AUTHORITY_LEDGER: u32 = 1;
/// Config journal (device).
pub const STORE_CONFIG_JOURNAL: u32 = 1;
/// Power image (device).
pub const STORE_POWER_IMAGE: u32 = 1;
/// RLT1 trust store (device).
pub const STORE_TRUST: u32 = 1;
/// RLC1 device credential (device).
pub const STORE_CREDENTIAL: u32 = 1;
/// SDK v1 records RLI1/RLS1/RRS1/RLP1 format.
pub const STORE_SDKV1_FORMAT: u32 = 1;
/// SDK v1 records schema.
pub const STORE_SDKV1_SCHEMA: u32 = 1;
/// Host operation store (SQLite).
pub const STORE_HOST_OPS: u32 = 4;
/// Site Authority store (SQLite).
pub const STORE_SITE: u32 = 2;

pub const REASON_NONE: u16 = 0;
