//! Generated by tools/gen_manifest.py from protocol/manifest.json. Do not edit.

pub const SDK_VERSION: &str = "2.0.0-dev";

/// Core C ABI.
pub const CORE_C_ABI: u32 = 2;
/// Mesh wire major.
pub const WIRE_MAJOR: u32 = 2;
/// Mesh wire minor.
pub const WIRE_MINOR: u32 = 0;
/// RLD1 carrier.
pub const RLD1_VERSION: u32 = 1;
/// RLD1 ZeroTouch body.
pub const RLD1_ZT_BODY: u32 = 3;
/// HostLink (RLU1) protocol.
pub const HOSTLINK_PROTOCOL: u32 = 1;
/// HostOps schema.
pub const HOSTOPS_SCHEMA: u32 = 1;
/// HostOps join relay schema.
pub const HOSTOPS_JOIN_RELAY_SCHEMA: u32 = 2;
/// AuthorityEnvelope.
pub const AUTHORITY_ENVELOPE: u32 = 1;
/// API1 envelope.
pub const API1_ENVELOPE: u32 = 1;
/// API1 caps_version.
pub const API1_CAPS: u32 = 1;
/// Authority ledger format.
pub const STORE_AUTHORITY_LEDGER_FORMAT: u32 = 1;
/// Authority ledger (device).
pub const STORE_AUTHORITY_LEDGER: u32 = 1;
/// Config journal format (device).
pub const STORE_CONFIG_JOURNAL_FORMAT: u32 = 2;
/// Config journal schema (device).
pub const STORE_CONFIG_JOURNAL_SCHEMA: u32 = 1;
/// Power image (device).
pub const STORE_POWER_IMAGE: u32 = 1;
/// Security floor format (device).
pub const STORE_SECURITY_FLOOR_FORMAT: u32 = 1;
/// RLT1 trust store format.
pub const STORE_TRUST_FORMAT: u32 = 1;
/// RLT1 trust store (device).
pub const STORE_TRUST: u32 = 1;
/// RLC1 device credential format.
pub const STORE_CREDENTIAL_FORMAT: u32 = 1;
/// RLC1 device credential (device).
pub const STORE_CREDENTIAL: u32 = 1;
/// SDK v1 sealed records RLI1/RLS1/RRS1/RLV1 format.
pub const STORE_SDKV1_FORMAT: u32 = 1;
/// SDK v1 sealed records schema.
pub const STORE_SDKV1_SCHEMA: u32 = 1;
/// RRS1 signed revocation object.
pub const RRS1_OBJECT_VERSION: u32 = 1;
/// RLP1 resume slot.
pub const STORE_RLP1_FORMAT: u32 = 1;
/// RLP2 resume slot.
pub const STORE_RLP2_FORMAT: u32 = 1;
/// Migration active record.
pub const STORE_MIGRATION_ACTIVE: u32 = 1;
/// Migration commit record.
pub const STORE_MIGRATION_COMMIT: u32 = 2;
/// Migration recovery snapshot.
pub const STORE_MIGRATION_RECOVERY: u32 = 1;
/// Host canonical node request.
pub const STORE_CANONICAL_NODE: u32 = 1;
/// Host canonical gateway request.
pub const STORE_CANONICAL_GATEWAY: u32 = 2;
/// Host operation store (SQLite).
pub const STORE_HOST_OPS: u32 = 4;
/// Site Authority store (SQLite).
pub const STORE_SITE: u32 = 2;

pub const REASON_NONE: u16 = 0;
