//! Generated by tools/gen_manifest.py from protocol/manifest.json. Do not edit.

pub const SDK_VERSION: &str = "2.0.0-dev";

/// Core C ABI.
pub const CORE_C_ABI: u32 = 3;
/// Mesh wire major.
pub const WIRE_MAJOR: u32 = 2;
/// Mesh wire minor.
pub const WIRE_MINOR: u32 = 0;
/// RLD1 carrier.
pub const RLD1_VERSION: u32 = 1;
/// RLD1 ZeroTouch body.
pub const RLD1_ZT_BODY: u32 = 3;
/// HostLink (RLU1) protocol.
pub const HOSTLINK_PROTOCOL: u32 = 1;
/// HostOps schema.
pub const HOSTOPS_SCHEMA: u32 = 1;
/// HostOps join relay schema.
pub const HOSTOPS_JOIN_RELAY_SCHEMA: u32 = 2;
/// AuthorityEnvelope.
pub const AUTHORITY_ENVELOPE: u32 = 1;
/// API1 envelope.
pub const API1_ENVELOPE: u32 = 1;
/// API1 caps_version.
pub const API1_CAPS: u32 = 2;
/// Authority ledger format.
pub const STORE_AUTHORITY_LEDGER_FORMAT: u32 = 1;
/// Authority ledger (device).
pub const STORE_AUTHORITY_LEDGER: u32 = 1;
/// Config journal format (device).
pub const STORE_CONFIG_JOURNAL_FORMAT: u32 = 2;
/// Config journal schema (device).
pub const STORE_CONFIG_JOURNAL_SCHEMA: u32 = 1;
/// Power image (device).
pub const STORE_POWER_IMAGE: u32 = 1;
/// Security floor format (device).
pub const STORE_SECURITY_FLOOR_FORMAT: u32 = 1;
/// RLT1 trust store format.
pub const STORE_TRUST_FORMAT: u32 = 1;
/// RLT1 trust store (device).
pub const STORE_TRUST: u32 = 1;
/// RLC1 device credential format.
pub const STORE_CREDENTIAL_FORMAT: u32 = 1;
/// RLC1 device credential (device).
pub const STORE_CREDENTIAL: u32 = 1;
/// SDK v1 sealed records RLI1/RLS1/RRS1/RLV1 format.
pub const STORE_SDKV1_FORMAT: u32 = 1;
/// SDK v1 sealed records schema.
pub const STORE_SDKV1_SCHEMA: u32 = 1;
/// RRS1 signed revocation object.
pub const RRS1_OBJECT_VERSION: u32 = 1;
/// RLP1 resume slot.
pub const STORE_RLP1_FORMAT: u32 = 1;
/// RLP2 resume slot.
pub const STORE_RLP2_FORMAT: u32 = 1;
/// Migration active record.
pub const STORE_MIGRATION_ACTIVE: u32 = 1;
/// Migration commit record.
pub const STORE_MIGRATION_COMMIT: u32 = 2;
/// Migration recovery snapshot.
pub const STORE_MIGRATION_RECOVERY: u32 = 1;
/// Host canonical node request.
pub const STORE_CANONICAL_NODE: u32 = 1;
/// Host canonical gateway request.
pub const STORE_CANONICAL_GATEWAY: u32 = 2;
/// Host operation store (SQLite).
pub const STORE_HOST_OPS: u32 = 4;
/// Site Authority store (SQLite).
pub const STORE_SITE: u32 = 2;

pub const REASON_NONE: u16 = 0;
pub const REASON_QUEUED: u16 = 256;
pub const REASON_TX_ACCEPTED: u16 = 257;
pub const REASON_TX_MAC_PENDING: u16 = 258;
pub const REASON_TX_MAC_DONE: u16 = 259;
pub const REASON_HOP_ACCEPT_PENDING: u16 = 260;
pub const REASON_END_RECEIPT_PENDING: u16 = 261;
pub const REASON_END_RECEIVED: u16 = 262;
pub const REASON_ORDER_WAIT: u16 = 263;
pub const REASON_APP_RESULT_PENDING: u16 = 264;
pub const REASON_APP_APPLIED: u16 = 265;
pub const REASON_APP_REJECTED: u16 = 266;
pub const REASON_APP_RESULT_TIMEOUT: u16 = 267;
pub const REASON_APP_RESULT_LATE: u16 = 268;
pub const REASON_APP_RESULT_INDETERMINATE: u16 = 269;
pub const REASON_APP_RESULT_EXPIRED: u16 = 270;
pub const REASON_APP_RESULT_NOT_RETAINED: u16 = 271;
pub const REASON_END_RECEIPT_TIMEOUT: u16 = 272;
pub const REASON_DEADLINE_EXPIRED: u16 = 273;
pub const REASON_CANCELLED_BEFORE_TX: u16 = 274;
pub const REASON_CANCEL_AFTER_TX_INDETERMINATE: u16 = 275;
pub const REASON_NO_ROUTE: u16 = 276;
pub const REASON_NO_RETURN_ROUTE: u16 = 277;
pub const REASON_HOP_ACCEPT_TIMEOUT: u16 = 278;
pub const REASON_MAC_SEND_FAILED: u16 = 279;
pub const REASON_DRIVER_RESULT_UNKNOWN: u16 = 280;
pub const REASON_ATTEMPT_BUDGET_EXHAUSTED: u16 = 281;
pub const REASON_BUSY_BUDGET_EXHAUSTED: u16 = 282;
pub const REASON_TX_QUEUE_FULL: u16 = 283;
pub const REASON_TX_QUEUE_RESERVED: u16 = 284;
pub const REASON_CONTROL_LANE_FULL: u16 = 285;
pub const REASON_REPLY_UNAFFORDABLE: u16 = 286;
pub const REASON_TX_TOKEN_EXHAUSTED: u16 = 287;
pub const REASON_REVOKED_PEER: u16 = 288;
pub const REASON_TXN_EXPIRED: u16 = 289;
pub const REASON_TXN_NO_PORT: u16 = 290;
pub const REASON_TXN_REVOKED: u16 = 291;
pub const REASON_READMIT_QUEUE_FULL: u16 = 292;
pub const REASON_NOT_FOUND: u16 = 293;
pub const REASON_GROUP_QUEUED: u16 = 294;
pub const REASON_GROUP_BUDGET_WAIT: u16 = 295;
pub const REASON_GROUP_ROUND_PENDING: u16 = 296;
pub const REASON_GROUP_REPAIRING: u16 = 297;
pub const REASON_GROUP_REPAIR_PENDING: u16 = 298;
pub const REASON_GROUP_COMPLETE: u16 = 299;
pub const REASON_GROUP_INCOMPLETE: u16 = 300;
pub const REASON_GROUP_SUPERSEDED: u16 = 301;
pub const REASON_GROUP_NOT_SENT: u16 = 302;
pub const REASON_GROUP_NO_TREE: u16 = 303;
pub const REASON_GROUP_KEY_RETIRED: u16 = 304;
pub const REASON_SLEEP_DEFERRED: u16 = 305;
pub const REASON_SLEEP_DRAIN: u16 = 306;
pub const REASON_SLEEP_GROUP_NOT_PERSISTED: u16 = 307;
