#!/bin/bash
cd /home/sahur/orca/workspaces/RouteLoom/v2-h1
L=artifacts/hil/2026-09-30-h1/build
b(){ lab=$1; shift; rm -rf artifacts/hil/images/$lab; tools/hil/build_image.sh "$@" > $L/$lab.log 2>&1; echo "BUILD $lab rc=$?"; }
M=CONFIG_ROUTELOOM_SECURITY_MODE_MEMBER_EDHOC=y
EPP="CONFIG_ROUTELOOM_RESOURCE_PROFILE_ENDPOINT=y CONFIG_ROUTELOOM_ROLE_ENDPOINT=y"
b h1-rl-feat2 reference_node esp32c6 h1-rl-feat2 $M CONFIG_ROUTELOOM_HIL_HEAP_TELEMETRY=y CONFIG_ROUTELOOM_CONFIG=y CONFIG_ROUTELOOM_MIGRATION=2 CONFIG_ROUTELOOM_HIL_GATEWAY_SEND_COUNT=20 CONFIG_ROUTELOOM_HIL_GATEWAY_WRONG=0x3 &
b h1-ep-feat2 reference_node esp32c6 h1-ep-feat2 $M $EPP CONFIG_ROUTELOOM_HIL_HEAP_TELEMETRY=y CONFIG_ROUTELOOM_CONFIG=y CONFIG_ROUTELOOM_MIGRATION=2 CONFIG_ROUTELOOM_HIL_GATEWAY_SEND_COUNT=20 CONFIG_ROUTELOOM_HIL_GATEWAY_WRONG=0x2 &
wait
echo FLOW_DONE
