#!/usr/bin/env python3
"""Check (or write) protocol/abi-golden, the C ABI layouts.

core-abi3.json holds routeloom.h (core C ABI 3), device-api1.json holds
device.h (Device C API 1). Every `typedef struct ... rl_*_t;` of a header is
measured with the C
compiler for two data models: LP64 (the host) and ILP32 as the ESP32 targets
lay it out (4-byte pointers, 8-byte aligned 64-bit integers; emulated with
`-m32 -malign-double`, or measured with the ESP toolchain named by
ROUTELOOM_ILP32_CC). The compiler only emits assembly, so no target
libraries are needed. `--check` fails on any difference: an ABI 3.x change
may only append fields (the golden is then rewritten with `--write` and the
diff reviewed).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

# (header, golden, abi): each header's own structs; device.h reuses the
# core ones by include.
SURFACES = [
    ("components/routeloom/include/routeloom/routeloom.h",
     "protocol/abi-golden/core-abi3.json", 3),
    ("components/routeloom_device/include/routeloom/device.h",
     "protocol/abi-golden/device-api1.json", 1),
]
INCLUDES = ["components/routeloom/include", "components/routeloom_device/include"]
MODELS = {
    "lp64": ["-m64"],
    "ilp32": ["-m32", "-malign-double"],
}
STRUCT = re.compile(r"typedef struct (\w+) \{(.*?)\} (\w+_t);", re.S)


def members(body: str) -> list[str]:
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    names = []
    for decl in body.split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        pointer = re.search(r"\(\s*\*\s*(\w+)\s*\)", decl)
        name = pointer.group(1) if pointer else re.search(r"(\w+)\s*(\[[^\]]*\])?$", decl).group(1)
        names.append(name)
    return names


def structs(root: Path, header: str) -> dict[str, list[str]]:
    text = (root / header).read_text(encoding="utf-8")
    return {typedef: members(body) for _, body, typedef in STRUCT.findall(text)}


def model_command(model: str) -> list[str]:
    native = os.environ.get("ROUTELOOM_ILP32_CC") if model == "ilp32" else None
    if native:
        return shlex.split(native)
    return [*shlex.split(os.environ.get("CC", "cc")), *MODELS[model]]


def measure(root: Path, header: str, layout: dict[str, list[str]], model: str) -> dict:
    items = []
    for name, fields in layout.items():
        items += [f"sizeof({name})", f"_Alignof({name})"]
        items += [f"offsetof({name}, {field})" for field in fields]
    source = f"#include <stddef.h>\n#include \"routeloom/{Path(header).name}\"\n"
    source += "const unsigned int rl_abi_layout[] = {\n" + ",\n".join(items) + "\n};\n"
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "layout.c"
        path.write_text(source, encoding="utf-8")
        includes = [arg for include in INCLUDES for arg in ("-I", str(root / include))]
        command = [*model_command(model), "-std=c11", "-ffreestanding", "-O0", "-S", "-o", "-",
                   *includes, str(path)]
        out = subprocess.run(command, capture_output=True, text=True, check=False)
    if out.returncode != 0:
        raise SystemExit(f"{' '.join(command)} failed:\n{out.stderr}")
    table = out.stdout.split("rl_abi_layout:", 1)[-1]
    values = [int(v) for v in re.findall(r"^\s*\.(?:long|word|4byte)\s+(\d+)\s*$", table, re.M)]
    values = values[:len(items)]
    if len(values) != len(items):
        raise SystemExit(f"expected {len(items)} layout values, parsed {len(values)}")
    result, index = {}, 0
    for name, fields in layout.items():
        size, align = values[index], values[index + 1]
        offsets = dict(zip(fields, values[index + 2:index + 2 + len(fields)]))
        index += 2 + len(fields)
        result[name] = {"size": size, "align": align, "offsets": offsets}
    return result


def build(root: Path, header: str, abi: int) -> dict:
    layout = structs(root, header)
    measured = {model: measure(root, header, layout, model) for model in MODELS}
    return {
        "abi": abi,
        "note": "Generated by tools/abi_golden.py --write; ilp32 is the ESP32 layout.",
        "structs": {name: {model: measured[model][name] for model in MODELS} for name in layout},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true", help="rewrite the golden file")
    args = parser.parse_args()
    failed = False
    for header, name, abi in SURFACES:
        current = build(args.root, header, abi)
        text = json.dumps(current, indent=1) + "\n"
        golden = args.root / name
        if args.write:
            golden.parent.mkdir(parents=True, exist_ok=True)
            golden.write_text(text, encoding="utf-8")
            continue
        if not golden.exists() or golden.read_text(encoding="utf-8") != text:
            failed = True
            expected = json.loads(golden.read_text(encoding="utf-8")) if golden.exists() else {}
            for struct, models in current["structs"].items():
                if expected.get("structs", {}).get(struct) != models:
                    print(f"{name}: {struct} differs", file=sys.stderr)
            for struct in expected.get("structs", {}):
                if struct not in current["structs"]:
                    print(f"{name}: {struct} is gone", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
