#!/usr/bin/env python3
"""Check (or write) protocol/abi-golden/core-abi3.json, the core C ABI layout.

Every `typedef struct ... rl_*_t;` in routeloom.h is measured with the C
compiler for two data models: LP64 (the host) and ILP32 as the ESP32 targets
lay it out (4-byte pointers, 8-byte aligned 64-bit integers; emulated with
`-m32 -malign-double`, or measured with the ESP toolchain named by
ROUTELOOM_ILP32_CC). The compiler only emits assembly, so no target
libraries are needed. `--check` fails on any difference: an ABI 3.x change
may only append fields (the golden is then rewritten with `--write` and the
diff reviewed).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

HEADER = "components/routeloom/include/routeloom/routeloom.h"
GOLDEN = "protocol/abi-golden/core-abi3.json"
MODELS = {
    "lp64": ["-m64"],
    "ilp32": ["-m32", "-malign-double"],
}
STRUCT = re.compile(r"typedef struct (\w+) \{(.*?)\} (\w+_t);", re.S)


def members(body: str) -> list[str]:
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    names = []
    for decl in body.split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        pointer = re.search(r"\(\s*\*\s*(\w+)\s*\)", decl)
        name = pointer.group(1) if pointer else re.search(r"(\w+)\s*(\[[^\]]*\])?$", decl).group(1)
        names.append(name)
    return names


def structs(root: Path) -> dict[str, list[str]]:
    text = (root / HEADER).read_text(encoding="utf-8")
    return {typedef: members(body) for _, body, typedef in STRUCT.findall(text)}


def model_command(model: str) -> list[str]:
    native = os.environ.get("ROUTELOOM_ILP32_CC") if model == "ilp32" else None
    if native:
        return shlex.split(native)
    return [*shlex.split(os.environ.get("CC", "cc")), *MODELS[model]]


def measure(root: Path, layout: dict[str, list[str]], model: str) -> dict:
    items = []
    for name, fields in layout.items():
        items += [f"sizeof({name})", f"_Alignof({name})"]
        items += [f"offsetof({name}, {field})" for field in fields]
    source = "#include <stddef.h>\n#include \"routeloom/routeloom.h\"\n"
    source += "const unsigned int rl_abi_layout[] = {\n" + ",\n".join(items) + "\n};\n"
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "layout.c"
        path.write_text(source, encoding="utf-8")
        command = [*model_command(model), "-std=c11", "-ffreestanding", "-O0", "-S", "-o", "-",
                   "-I", str(root / "components/routeloom/include"), str(path)]
        out = subprocess.run(command, capture_output=True, text=True, check=False)
    if out.returncode != 0:
        raise SystemExit(f"{' '.join(command)} failed:\n{out.stderr}")
    table = out.stdout.split("rl_abi_layout:", 1)[-1]
    values = [int(v) for v in re.findall(r"^\s*\.(?:long|word|4byte)\s+(\d+)\s*$", table, re.M)]
    values = values[:len(items)]
    if len(values) != len(items):
        raise SystemExit(f"expected {len(items)} layout values, parsed {len(values)}")
    result, index = {}, 0
    for name, fields in layout.items():
        size, align = values[index], values[index + 1]
        offsets = dict(zip(fields, values[index + 2:index + 2 + len(fields)]))
        index += 2 + len(fields)
        result[name] = {"size": size, "align": align, "offsets": offsets}
    return result


def build(root: Path) -> dict:
    layout = structs(root)
    measured = {model: measure(root, layout, model) for model in MODELS}
    return {
        "abi": 3,
        "note": "Generated by tools/abi_golden.py --write; ilp32 is the ESP32 layout.",
        "structs": {name: {model: measured[model][name] for model in MODELS} for name in layout},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true", help="rewrite the golden file")
    args = parser.parse_args()
    current = build(args.root)
    text = json.dumps(current, indent=1) + "\n"
    golden = args.root / GOLDEN
    if args.write:
        golden.parent.mkdir(parents=True, exist_ok=True)
        golden.write_text(text, encoding="utf-8")
        return 0
    if not golden.exists() or golden.read_text(encoding="utf-8") != text:
        expected = json.loads(golden.read_text(encoding="utf-8")) if golden.exists() else {}
        for name, models in current["structs"].items():
            if expected.get("structs", {}).get(name) != models:
                print(f"{GOLDEN}: {name} differs", file=sys.stderr)
        for name in expected.get("structs", {}):
            if name not in current["structs"]:
                print(f"{GOLDEN}: {name} is gone", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
