#!/usr/bin/env python3
"""Generate version constants from protocol/manifest.json and detect drift.

protocol/manifest.json is the single source of the SDK version and of every
surface, persisted-format and reason-code number. This tool writes the C
header, the Rust module, the C++/Rust checks that compare the manifest with
the constants the code actually uses, and the tables in
docs/spec/compatibility.md. `--check` regenerates in memory and fails on any
difference, and also fails when a package manifest or toolchain pin disagrees.
Codecs are not generated: the constants stay where the code defines them.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

HEADER = "components/routeloom/include/routeloom/version.h"
CPP_CHECK = "tests/cpp/manifest_check.cpp"
RUST_MODULE = "host/routeloom-protocol/src/manifest.rs"
RUST_CHECK = "host/routeloom-host/src/manifest_check.rs"
COMPAT_DOC = "docs/spec/compatibility.md"
BEGIN = "<!-- manifest:begin (generated by tools/gen_manifest.py; edit protocol/manifest.json) -->"
END = "<!-- manifest:end -->"
NOTICE = "Generated by tools/gen_manifest.py from protocol/manifest.json. Do not edit."
SEMVER = re.compile(r"(\d+)\.(\d+)\.(\d+)(?:-[0-9A-Za-z.-]+)?")
IDF_COMPONENTS = sorted(["routeloom", "routeloom_bench", "routeloom_espnow", "routeloom_node_boot"])
IDF_DEPENDENCIES = {
    "routeloom_bench": "routeloom/routeloom",
    "routeloom_espnow": "routeloom/routeloom",
    "routeloom_node_boot": "routeloom/routeloom_espnow",
}


class ManifestError(ValueError):
    pass


def load(root: Path) -> dict:
    manifest = json.loads((root / "protocol/manifest.json").read_text(encoding="utf-8"))
    validate(manifest)
    return manifest


def entries(manifest: dict) -> list[dict]:
    return manifest["surfaces"] + manifest["persisted"]


def validate(manifest: dict) -> None:
    if manifest.get("schema") != 1:
        raise ManifestError("unknown manifest schema")
    if not SEMVER.fullmatch(manifest["sdk_version"]):
        raise ManifestError("sdk_version is not semver")
    seen: set[str] = set()
    for entry in entries(manifest):
        for key in ("id", "c", "rust"):
            name = entry.get(key)
            if name is None:
                continue
            if name in seen:
                raise ManifestError(f"duplicate name {name}")
            seen.add(name)
        value = entry["value"]
        if value is not None and (not isinstance(value, int) or not 0 <= value <= 0xFFFFFFFF):
            raise ManifestError(f"{entry['id']}: value must be u32 or null")
        if value is None and any(k in entry for k in ("c", "rust", "cpp_check", "rust_check")):
            raise ManifestError(f"{entry['id']}: a reserved entry has no constants")
        if "cpp_check" in entry and "c" not in entry:
            raise ManifestError(f"{entry['id']}: cpp_check needs a C name")
        if "rust_check" in entry and "rust" not in entry:
            raise ManifestError(f"{entry['id']}: rust_check needs a Rust name")
        checks = entry.get("rust_check", [])
        checks = [checks] if isinstance(checks, str) else checks
        if not isinstance(checks, list) or any(not isinstance(check, str) or not check for check in checks):
            raise ManifestError(f"{entry['id']}: rust_check must name Rust constants")
    reasons = manifest["reason_codes"]
    if reasons["width_bits"] != 16:
        raise ManifestError("reason_codes.width_bits must be 16")
    limit = 1 << reasons["width_bits"]
    ranges = reasons["ranges"]
    for index, span in enumerate(ranges):
        if not 0 <= span["first"] <= span["last"] < limit:
            raise ManifestError(f"reason range {span['area']} out of bounds")
        if index and span["first"] <= ranges[index - 1]["last"]:
            raise ManifestError(f"reason range {span['area']} overlaps")
    ids: set[int] = set()
    names: set[str] = set()
    for code in reasons["codes"]:
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", code["name"]):
            raise ManifestError(f"reason name {code['name']} is not UPPER_SNAKE")
        if code["id"] in ids or code["name"] in names:
            raise ManifestError(f"duplicate reason code {code['name']}")
        if not any(s["first"] <= code["id"] <= s["last"] for s in ranges):
            raise ManifestError(f"reason code {code['name']} is outside every range")
        api1 = code.get("api1")
        if api1 is not None and (not isinstance(api1, str) or not api1.isprintable() or '"' in api1):
            raise ManifestError(f"reason code {code['name']}: api1 must be null or a printable string")
        ids.add(code["id"])
        names.add(code["name"])


def render_header(manifest: dict) -> str:
    major, minor, patch = SEMVER.fullmatch(manifest["sdk_version"]).groups()
    lines = [
        f"/* {NOTICE} */",
        "/* clang-format off */",
        "#ifndef ROUTELOOM_VERSION_H",
        "#define ROUTELOOM_VERSION_H",
        "",
        f'#define ROUTELOOM_SDK_VERSION "{manifest["sdk_version"]}"',
        f"#define ROUTELOOM_SDK_VERSION_MAJOR {major}",
        f"#define ROUTELOOM_SDK_VERSION_MINOR {minor}",
        f"#define ROUTELOOM_SDK_VERSION_PATCH {patch}",
        "",
    ]
    for entry in entries(manifest):
        if "c" in entry:
            lines.append(f"#define {entry['c']} {entry['value']}  /* {entry['label']} */")
    lines.append("")
    codes = manifest["reason_codes"]["codes"]
    for code in codes:
        lines.append(f"#define ROUTELOOM_REASON_{code['name']} {code['id']}")
    lines += ["", "/* X(NAME, id) for every registered reason code. */", "#define ROUTELOOM_REASON_TABLE(X) \\"]
    lines += [f"  X({code['name']}, {code['id']})" + (" \\" if index + 1 < len(codes) else "")
              for index, code in enumerate(codes)]
    for span in manifest["reason_codes"]["ranges"]:
        area = [c for c in codes if span["first"] <= c["id"] <= span["last"]]
        lines += ["", f"/* X(NAME, id) for the {span['area']} area only. */",
                  f"#define ROUTELOOM_REASON_{span['area'].upper()}_TABLE(X)" + (" \\" if area else "")]
        lines += [f"  X({code['name']}, {code['id']})" + (" \\" if index + 1 < len(area) else "")
                  for index, code in enumerate(area)]
    lines += ["", "#endif /* ROUTELOOM_VERSION_H */", ""]
    return "\n".join(lines)


def render_cpp_check(manifest: dict) -> str:
    checked = [e for e in entries(manifest) if "cpp_check" in e]
    includes = sorted({"routeloom/version.h", *(e["cpp_include"] for e in checked)})
    lines = [f"// {NOTICE}", "// Fails to compile when a constant used by the code drifts from the manifest.",
             "// clang-format off", ""]
    lines += [f'#include "{name}"' for name in includes]
    lines.append("")
    for entry in checked:
        lines.append(f'static_assert({entry["cpp_check"]} == {entry["c"]}, "protocol/manifest.json {entry["id"]}");')
    lines.append("")
    return "\n".join(lines)


def render_rust_module(manifest: dict) -> str:
    lines = [f"//! {NOTICE}", "", f'pub const SDK_VERSION: &str = "{manifest["sdk_version"]}";', ""]
    for entry in entries(manifest):
        if "rust" in entry:
            lines.append(f"/// {entry['label']}.")
            lines.append(f"pub const {entry['rust']}: u32 = {entry['value']};")
    lines.append("")
    codes = manifest["reason_codes"]["codes"]
    for code in codes:
        lines.append(f"pub const REASON_{code['name']}: u16 = {code['id']};")
    lines += ["", "/// (id, API1 string) for every reason code; the string is `api1` when set, else the name.",
              "pub const REASON_API1: &[(u16, &str)] = &["]
    lines += [f'    ({code["id"]}, "{code.get("api1") or code["name"]}"),' for code in codes]
    lines += ["];", ""]
    return "\n".join(lines)


def render_rust_check(manifest: dict) -> str:
    lines = [
        f"// {NOTICE}",
        "// Fails when a constant used by the host drifts from the manifest.",
        "use routeloom_protocol::manifest as m;",
        "",
        "#[test]",
        "#[rustfmt::skip]",
        "fn manifest_matches_host_constants() {",
        '    assert_eq!(env!("CARGO_PKG_VERSION"), m::SDK_VERSION);',
    ]
    for entry in entries(manifest):
        checks = entry.get("rust_check", [])
        for check in [checks] if isinstance(checks, str) else checks:
            lines.append(f"    assert_eq!(u64::from({check}), u64::from(m::{entry['rust']}));")
    lines += ["}", ""]
    return "\n".join(lines)


def render_doc_block(manifest: dict) -> str:
    def value(entry: dict) -> str:
        return "reserved" if entry["value"] is None else str(entry["value"])

    tc = manifest["toolchain"]
    out = [
        BEGIN,
        "",
        f"SDK version: **{manifest['sdk_version']}** (one semver for the ESP-IDF components,",
        "the Rust workspace and meshviz). Each surface below carries its own number.",
        "",
        "| Surface | Value | C / Rust name | Defined in | Rule |",
        "|---|---|---|---|---|",
    ]
    for entry in manifest["surfaces"]:
        names = " / ".join(f"`{entry[k]}`" for k in ("c", "rust") if k in entry) or "-"
        out.append(f"| {entry['label']} | {value(entry)} | {names} | `{entry['source']}` | {entry['rule']} |")
    out += ["", "| Persisted format | Version | C / Rust name | Defined in | Unknown-version behavior |", "|---|---|---|---|---|"]
    for entry in manifest["persisted"]:
        names = " / ".join(f"`{entry[k]}`" for k in ("c", "rust") if k in entry) or "-"
        out.append(f"| {entry['label']} | {value(entry)} | {names} | `{entry['source']}` | {entry['rule']} |")
    layout = manifest["partition_layout"] or "not registered yet"
    out += [
        "",
        f"Toolchain: ESP-IDF {tc['esp_idf_tag']} (`{tc['esp_idf_commit']}`), Rust {tc['rust']}. "
        f"Partition layout ID: {layout}.",
        "",
        f"Reason codes are u{manifest['reason_codes']['width_bits']} and are allocated by area:",
        "",
        "| Area | Range |",
        "|---|---|",
    ]
    for span in manifest["reason_codes"]["ranges"]:
        out.append(f"| {span['area']} | 0x{span['first']:04X}-0x{span['last']:04X} |")
    out += ["", END]
    return "\n".join(out)


def splice_doc(current: str, block: str) -> str:
    start = current.find(BEGIN)
    stop = current.find(END)
    if start < 0 or stop < start:
        raise ManifestError(f"{COMPAT_DOC} lacks the manifest markers")
    return current[:start] + block + current[stop + len(END):]


def outputs(root: Path, manifest: dict) -> dict[str, str]:
    doc = (root / COMPAT_DOC).read_text(encoding="utf-8")
    return {
        HEADER: render_header(manifest),
        CPP_CHECK: render_cpp_check(manifest),
        RUST_MODULE: render_rust_module(manifest),
        RUST_CHECK: render_rust_check(manifest),
        COMPAT_DOC: splice_doc(doc, render_doc_block(manifest)),
    }


def package_drift(root: Path, manifest: dict) -> list[str]:
    """Version strings that are not generated but must equal the manifest."""
    version = manifest["sdk_version"]
    problems: list[str] = []
    for name in IDF_COMPONENTS:
        path = f"components/{name}/idf_component.yml"
        text = (root / path).read_text(encoding="utf-8")
        found = re.search(r"^version:\s*(\S+)\s*$", text, re.M)
        if not found or found.group(1) != version:
            problems.append(f"{path}: version is not {version}")
        dependencies = dict(re.findall(r'^\s+(routeloom/\w+):\s*"([^"]+)"', text, re.M))
        required = IDF_DEPENDENCIES.get(name)
        if required and required not in dependencies:
            problems.append(f"{path}: missing {required} dependency")
        for dep, constraint in dependencies.items():
            if constraint != f"^{version}":
                problems.append(f"{path}: {dep} constraint is not ^{version}")
    cargo = (root / "host/Cargo.toml").read_text(encoding="utf-8")
    workspace = tomllib.loads(cargo)["workspace"]
    if workspace["package"]["version"] != version:
        problems.append(f"host/Cargo.toml: workspace version is not {version}")
    members = set(workspace["members"])
    lock = tomllib.loads((root / "host/Cargo.lock").read_text(encoding="utf-8"))
    locked = {item["name"]: item["version"] for item in lock["package"]
              if item["name"] in members and "source" not in item}
    for member in sorted(members):
        if locked.get(member) != version:
            problems.append(f"host/Cargo.lock: {member} version is not {version}")
    meshviz = (root / "tools/meshviz/pyproject.toml").read_text(encoding="utf-8")
    found = re.search(r'^version\s*=\s*"([^"]+)"', meshviz, re.M)
    if not found or found.group(1) != version:
        problems.append(f"tools/meshviz/pyproject.toml: version is not {version}")
    tc = manifest["toolchain"]
    idf = json.loads((root / "docs/reference/radio-defaults.json").read_text(encoding="utf-8"))["esp_idf"]
    if idf != {"tag": tc["esp_idf_tag"], "commit": tc["esp_idf_commit"]}:
        problems.append("docs/reference/radio-defaults.json: esp_idf pin differs from the manifest")
    sdk_ci = (root / ".github/workflows/sdk.yml").read_text(encoding="utf-8")
    idf_images = re.findall(r"^\s*image:\s*espressif/idf:(\S+)\s*$", sdk_ci, re.M)
    if not idf_images or any(tag != tc["esp_idf_tag"] for tag in idf_images):
        problems.append(f".github/workflows/sdk.yml: ESP-IDF image differs from {tc['esp_idf_tag']}")
    toolchain = (root / "host/rust-toolchain.toml").read_text(encoding="utf-8")
    channel = re.search(r'^channel\s*=\s*"([^"]+)"', toolchain, re.M)
    if not channel:
        problems.append("host/rust-toolchain.toml: rust toolchain pin is missing")
    elif channel.group(1) != tc["rust"]:
        problems.append(f"host/rust-toolchain.toml: rust {channel.group(1)} differs from {tc['rust']}")
    for pin in re.findall(r"rustup toolchain install (\S+)", sdk_ci):
        if pin != tc["rust"]:
            problems.append(f".github/workflows/sdk.yml: rust {pin} differs from {tc['rust']}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        manifest = load(root)
        generated = outputs(root, manifest)
    except (OSError, ValueError, KeyError) as error:
        print(f"gen_manifest: {error}", file=sys.stderr)
        return 1
    if not args.check:
        for path, text in generated.items():
            (root / path).write_text(text, encoding="utf-8")
        return 0
    problems = [f"{path}: stale, run tools/gen_manifest.py" for path, text in generated.items()
                if not (root / path).is_file() or (root / path).read_text(encoding="utf-8") != text]
    try:
        problems += package_drift(root, manifest)
    except (OSError, ValueError, KeyError) as error:
        print(f"gen_manifest: {error}", file=sys.stderr)
        return 1
    for problem in problems:
        print(f"gen_manifest: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
