//! The relay objects of protocol/sdkv1-golden/join-transport/ (generated by
//! the independent tools/gen_sdkv1_join_transport_vectors.py, checked by
//! tests/cpp/test_sdkv1_join_transport.cpp): the host parses what a gateway
//! hands it in 0x60 and builds what it sends in 0x61, so every valid relay
//! object must decode to the listed fields and re-encode byte-for-byte, and
//! every invalid one must be refused.

use routeloom_protocol::join_relay::*;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("protocol/sdkv1-golden/join-transport")
}

/// Flat JSON (string and non-negative integer values only), as the C++ side.
fn parse_flat_json(text: &str) -> BTreeMap<String, String> {
    let mut fields = BTreeMap::new();
    let bytes = text.as_bytes();
    let mut pos = 0;
    while let Some(offset) = text[pos..].find('"') {
        let key_begin = pos + offset;
        let key_end = key_begin + 1 + text[key_begin + 1..].find('"').expect("key");
        let colon = key_end + 1 + text[key_end + 1..].find(':').expect("colon");
        let mut cursor = colon + 1;
        while cursor < bytes.len() && bytes[cursor].is_ascii_whitespace() {
            cursor += 1;
        }
        let value;
        if bytes[cursor] == b'"' {
            let end = cursor + 1 + text[cursor + 1..].find('"').expect("value");
            value = text[cursor + 1..end].to_string();
            pos = end + 1;
        } else {
            let mut end = cursor;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
            value = text[cursor..end].to_string();
            pos = end;
        }
        fields.insert(text[key_begin + 1..key_end].to_string(), value);
    }
    fields
}

fn unhex(text: &str) -> Vec<u8> {
    assert!(text.len() % 2 == 0, "odd hex");
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("hex"))
        .collect()
}

fn num(fields: &BTreeMap<String, String>, key: &str) -> u64 {
    fields[key].parse().expect(key)
}

fn load_dir(dir: &Path) -> Vec<(String, BTreeMap<String, String>)> {
    let mut paths: Vec<PathBuf> = fs::read_dir(dir)
        .expect("vector dir")
        .map(|entry| entry.expect("entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    paths.sort();
    paths
        .into_iter()
        .map(|path| {
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            (
                name,
                parse_flat_json(&fs::read_to_string(&path).expect("read")),
            )
        })
        .collect()
}

#[test]
fn valid_relay_objects_decode_and_re_encode() {
    let mut checked = 0;
    for (name, f) in load_dir(&vectors_dir().join("valid")) {
        if f["codec"] != "relay_object" {
            continue;
        }
        let bytes = unhex(&f["object_hex"]);
        let object = RelayObject::decode(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        let h = &object.header;
        assert_eq!(h.dir as u64, num(&f, "dir"), "{name}");
        assert_eq!(u64::from(h.relay_id), num(&f, "relay_id"), "{name}");
        assert_eq!(h.proxy, num(&f, "proxy"), "{name}");
        assert_eq!(h.joiner_mac.to_vec(), unhex(&f["joiner_mac_hex"]), "{name}");
        assert_eq!(u64::from(h.phase), num(&f, "phase"), "{name}");
        assert_eq!(u64::from(h.step), num(&f, "step"), "{name}");
        assert_eq!(h.state as u64, num(&f, "state"), "{name}");
        assert_eq!(
            u64::from(h.joiner_rssi_dbm as u8),
            num(&f, "rssi_u8"),
            "{name}"
        );
        match &object.body {
            RelayBody::Message(message) => assert_eq!(message, &unhex(&f["message_hex"])),
            RelayBody::Abort {
                status,
                retry_after_ms,
            } => {
                assert_eq!(*status as u64, num(&f, "abort_status"), "{name}");
                assert_eq!(
                    u64::from(*retry_after_ms),
                    num(&f, "abort_retry_ms"),
                    "{name}"
                );
            }
        }
        assert_eq!(object.encode().unwrap(), bytes, "{name}");
        let wire_type = num(&f, "wire_type");
        if wire_type != 0 {
            assert_eq!(u64::from(object.single_frame_type()), wire_type, "{name}");
            assert_eq!(
                decode_single_frame(wire_type as u8, &bytes).unwrap(),
                object,
                "{name}"
            );
        } else {
            assert!(bytes.len() > WIRE_PAYLOAD_MAX, "{name}");
        }
        checked += 1;
    }
    assert!(checked >= 13, "relay object vectors: {checked}");
}

#[test]
fn invalid_relay_objects_are_refused() {
    let mut checked = 0;
    for (name, f) in load_dir(&vectors_dir().join("invalid")) {
        let bytes = unhex(&f["encoded_hex"]);
        match f["codec"].as_str() {
            "relay_object" => {
                assert!(RelayObject::decode(&bytes).is_err(), "{name}");
            }
            "relay_single_frame" => {
                let wire_type = num(&f, "wire_type") as u8;
                assert!(decode_single_frame(wire_type, &bytes).is_err(), "{name}");
            }
            _ => continue,
        }
        checked += 1;
    }
    assert!(checked >= 30, "invalid relay vectors: {checked}");
}
