#pragma once

// SDK v1 zero-touch join transport (docs/design/sdk-v1/02-zero-touch-join.md
// §5, §7; plan P3-1/P3-2). Codecs and bounded buffers only — the engines
// that use them are in sdkv1_join_relay.hpp.
//
//   RLD1 body v3 (class ZeroTouch=3)   DISCOVER 24 B (broadcast), OFFER 48 B
//   BootstrapAuth phases 4-6           EdhocMessage / Resume / RelayStatus,
//                                      assembled objects of at most 1024 B
//   join chunk / reply                 RLD1 kinds 5/6 and Wire FrameTypes 5/6
//   RelayHeader + relay object         Wire FrameTypes 3/4 (single frame) or
//                                      5/6 (chunked) between proxy and gateway
//
// All integers are big-endian, reserved bytes are zero, every length is
// exact, and the byte layouts are pinned by protocol/sdkv1-golden/
// join-transport/ (generated by the independent
// tools/gen_sdkv1_join_transport_vectors.py). Every codec is allocation-free;
// decoders borrow their byte views from the input.
//
// Resolved in implementation (02 §5.4 / §7.4 record the rationale):
//   - One EDHOC / RLRES1 message is at most kJoinMessageMax = 960 B, so the
//     RLD1 object (6 + 16 + 960), the relay object (24 + 960) and the USB
//     0x60/0x61 inner bodies (<= 1005 B, usb_host_ops.hpp) all fit their
//     1024 B ceilings with one constant.
//   - Chunks of both carriers share one layout: ver u8=1 | sub u8 |
//     id u32 | offset u16 | total u16 | data, where sub = (phase << 4) |
//     step names the message (0x41..0x45 EDHOC, 0x51..0x53 RLRES1) — so a
//     retransmitted chunk of a completed object never reads as the next
//     object — and id is the first four nonce bytes on RLD1, the relay_id on
//     Wire. Offsets sit on the carrier's chunk grid (106 B RLD1, 118 B Wire)
//     and only objects above the carrier's single-frame limit are chunked.
//   - RelayHeader byte 23 (reserved in 02 §7.1) carries the BootstrapAuth
//     phase (4 EDHOC, 5 RLRES1), because `step` alone is ambiguous.

#include <array>
#include <cstddef>
#include <cstdint>

#include "routeloom/admission.hpp"
#include "routeloom/autonomy_wire.hpp"
#include "routeloom/sdkv1_ead.hpp"
#include "routeloom/status.hpp"
#include "routeloom/types.hpp"

namespace routeloom::sdkv1 {

// --- Common bounds ---------------------------------------------------------------
constexpr std::size_t kJoinObjectMax = autonomy::kBootstrapObjectMax;  // 1024
constexpr std::size_t kJoinMessageMax = 960;
constexpr std::size_t kJoinCookieSize = 16;
using JoinCookieBytes = std::array<std::uint8_t, kJoinCookieSize>;
using JoinNonce = std::array<std::uint8_t, 16>;
// Upper bound of every unauthenticated retry hint (02 §10.1 ZT_BACKOFF max).
constexpr std::uint32_t kJoinRetryAfterMaxMs = 600000;

// ===================================================================================
// RLD1 body v3 — ZeroTouch DISCOVER / OFFER (02 §5.1 / §5.2)
// ===================================================================================
constexpr std::uint8_t kZtBodyVersion = 3;
constexpr std::uint8_t kZtClass = 3;  // 1 Member, 2 Commissioning (endpoint_wire.hpp)
constexpr std::size_t kZtDiscoverBodySize = 24;
constexpr std::size_t kZtOfferBodySize = 48;
constexpr std::uint16_t kZtDiscoverPreferredValid = 0x0001;
constexpr std::uint8_t kZtOfferAuthorityReachable = 0x01;
constexpr std::uint8_t kZtOfferProxyBusy = 0x02;
constexpr std::uint8_t kZtOfferFlagMask = 0x03;
constexpr std::uint8_t kZtHopsUnknown = 255;
constexpr std::size_t kZtAvoidHints = 2;

// DISCOVER body (24 B):
//   0 u8 body_version = 3 | 1 u8 class = 3 | 2 u16 flags (bit0 preferred_site_valid)
//   4 u32 profile_bits (bit0 RLJOIN1 required, bit1 RLRES1) | 8 u32 org_hint
//  12 u32 preferred_site_hint (nonzero iff flags bit0) | 16 u32 avoid[0] | 20 u32 avoid[1]
// Avoid slots pack from the front (avoid[1] != 0 needs avoid[0] != 0), are
// distinct, and never equal the preferred hint. The encoder derives flags.
// Header: kind DISCOVER, network_hint 0, claimed_node = own NodeId (valid),
// capability_bits 0, broadcast destination, fresh transaction nonce.
struct ZtDiscoverBody {
  std::uint32_t profile_bits{kJoinProfileRljoin1};
  std::uint32_t org_hint{0};
  std::uint32_t preferred_site_hint{0};
  std::array<std::uint32_t, kZtAvoidHints> avoid_site_hints{};
};

Status zt_discover_body_validate(const ZtDiscoverBody& body) noexcept;
Status zt_discover_body_encode(const ZtDiscoverBody& body,
                               ByteBuffer<kZtDiscoverBodySize>& out) noexcept;
Status zt_discover_body_decode(ByteView encoded, ZtDiscoverBody& out) noexcept;
// 02 §5.2: a proxy never answers a DISCOVER that lists its own site_hint.
bool zt_discover_avoids(const ZtDiscoverBody& body, std::uint32_t site_hint) noexcept;

// OFFER body (48 B):
//   0 u8 body_version = 3 | 1 u8 class = 3 | 2 u8 density | 3 u8 flags
//     (bit0 authority_reachable, bit1 proxy_busy)
//   4 16B cookie | 20 16B responder_nonce | 36 u32 org_hint | 40 u32 site_hint
//  44 u8 authority_hops (255 unknown) | 45 u8 load | 46 u16 reserved = 0
// Header: kind OFFER, network_hint = site network_low32 (nonzero),
// claimed_node = proxy NodeId (valid), transaction nonce = the DISCOVER's,
// capability_bits 0, unicast to the observed requester MAC. Everything here
// is an UNAUTHENTICATED selection hint, never evidence (02 §5.2).
struct ZtOfferBody {
  std::uint8_t density{0};
  std::uint8_t flags{kZtOfferAuthorityReachable};
  JoinCookieBytes cookie{};
  JoinNonce responder_nonce{};
  std::uint32_t org_hint{0};
  std::uint32_t site_hint{0};
  std::uint8_t authority_hops{kZtHopsUnknown};
  std::uint8_t load{0};
};

Status zt_offer_body_validate(const ZtOfferBody& body) noexcept;
Status zt_offer_body_encode(const ZtOfferBody& body, ByteBuffer<kZtOfferBodySize>& out) noexcept;
Status zt_offer_body_decode(ByteView encoded, ZtOfferBody& out) noexcept;

// Whole RLD1 frames with the header rules above. Decoders run rld1_decode,
// then the kind/header/body checks; `env` is filled on success.
Status zt_discover_frame_encode(NodeId self, const JoinNonce& nonce, const ZtDiscoverBody& body,
                                autonomy::Rld1Encoded& out) noexcept;
Status zt_discover_frame_decode(ByteView frame, autonomy::Rld1Envelope& env,
                                ZtDiscoverBody& out) noexcept;
Status zt_offer_frame_encode(NodeId proxy, std::uint32_t network_low32, const JoinNonce& nonce,
                             const ZtOfferBody& body, autonomy::Rld1Encoded& out) noexcept;
Status zt_offer_frame_decode(ByteView frame, autonomy::Rld1Envelope& env,
                             ZtOfferBody& out) noexcept;

// ===================================================================================
// BootstrapAuth phases 4-6 (02 §5.3) — the assembled join object
// ===================================================================================
enum class JoinAuthPhase : std::uint8_t {
  EdhocMessage = 4,  // step 1..4 = EDHOC message_1..4, 5 = EDHOC error
  Resume = 5,        // step 1..3 = RLRES1 R1..R3 (06 §2.1)
  RelayStatus = 6,   // step 1, proxy -> device, unauthenticated hint
};
constexpr std::uint8_t kJoinEdhocErrorStep = 5;

enum class RelayStatusCode : std::uint8_t {
  Queued = 1,
  AuthorityUnreachable = 2,
  Busy = 3,
  Aborted = 4,
};

// Object layout (<= 1024 B):
//   0 u8 version = 1 | 1 u8 phase | 2 u8 step | 3 u8 reserved = 0   (BA prefix)
//   phase 4/5: 4 u8 cookie_echo_present | 5 u8 reserved = 0 | [cookie 16B] |
//              message 1..960 B
//     cookie_echo_present is 1 exactly for phase 4 step 1 (m1); phase 5
//     step 1 (R1) may carry it (0/1, the carrier policy decides), every
//     other step carries 0.
//   phase 6:   4 u8 status (1..4) | 5 u32 retry_after_ms (<= 600000) — 9 B
constexpr std::size_t kJoinAuthPrefixSize = autonomy::kBootstrapAuthHeaderSize;  // 4
constexpr std::size_t kJoinObjectHeadSize = kJoinAuthPrefixSize + 2;               // 6
constexpr std::size_t kRelayStatusObjectSize = kJoinAuthPrefixSize + 5;            // 9
static_assert(kJoinObjectHeadSize + kJoinCookieSize + kJoinMessageMax <= kJoinObjectMax,
              "largest RLD1 join object fits the 1024 B assembly ceiling");

struct JoinAuthObject {
  JoinAuthPhase phase{JoinAuthPhase::EdhocMessage};
  std::uint8_t step{1};
  bool cookie_present{false};
  JoinCookieBytes cookie{};
  ByteView message{};  // phase 4/5
  RelayStatusCode relay_status{RelayStatusCode::Queued};  // phase 6
  std::uint32_t retry_after_ms{0};                         // phase 6
};

using JoinObjectBytes = ByteBuffer<kJoinObjectMax>;

bool join_step_valid(JoinAuthPhase phase, std::uint8_t step) noexcept;
Status join_object_validate(const JoinAuthObject& object) noexcept;
std::size_t join_object_encoded_size(const JoinAuthObject& object) noexcept;
Status join_object_encode(const JoinAuthObject& object, MutableByteView out,
                          std::size_t& written) noexcept;
Status join_object_decode(ByteView encoded, JoinAuthObject& out) noexcept;

// Which way a join step flows on the device <-> proxy hop.
enum class JoinFlow : std::uint8_t {
  Up = 1,      // device -> proxy (-> authority)
  Down = 2,    // proxy -> device (authority -> device, or a proxy hint)
  Either = 3,  // EDHOC error (step 5): either end may abort
};
JoinFlow join_step_flow(JoinAuthPhase phase, std::uint8_t step) noexcept;

// ===================================================================================
// Chunks and replies (RLD1 kinds 5/6, Wire FrameTypes 5/6)
// ===================================================================================
enum class JoinCarrier : std::uint8_t {
  Rld1 = 0,       // device <-> proxy, 1 hop, 116 B bodies
  WireRelay = 1,  // proxy <-> gateway, member links, 128 B payloads
};

constexpr std::uint8_t kJoinChunkVersion = 1;
constexpr std::size_t kJoinChunkHeaderSize = 10;
constexpr std::size_t kJoinReplySize = 10;
constexpr std::size_t kRld1JoinChunkData = autonomy::kRld1MaxBody - kJoinChunkHeaderSize;  // 106
constexpr std::size_t kWireRelayChunkData = kMaxApplicationPayload - kJoinChunkHeaderSize;  // 118
constexpr std::size_t kJoinChunkBitmapBits = 16;

constexpr std::size_t join_single_frame_max(const JoinCarrier carrier) noexcept {
  return carrier == JoinCarrier::Rld1 ? autonomy::kRld1MaxBody : kMaxApplicationPayload;
}
constexpr std::size_t join_chunk_data_max(const JoinCarrier carrier) noexcept {
  return carrier == JoinCarrier::Rld1 ? kRld1JoinChunkData : kWireRelayChunkData;
}
constexpr std::size_t join_chunk_count(const JoinCarrier carrier, const std::size_t total) noexcept {
  return (total + join_chunk_data_max(carrier) - 1) / join_chunk_data_max(carrier);
}
static_assert(join_chunk_count(JoinCarrier::Rld1, kJoinObjectMax) <= kJoinChunkBitmapBits,
              "RLD1 chunk grid fits the receipt bitmap");
static_assert(join_chunk_count(JoinCarrier::WireRelay, kJoinObjectMax) <= kJoinChunkBitmapBits,
              "Wire chunk grid fits the receipt bitmap");

// sub = (phase << 4) | step for phases 4 and 5 (a RelayStatus is 9 B and
// never chunked). The legacy dev-PSK chunk uses sub 1, so the two never mix.
constexpr std::uint8_t join_sub(const JoinAuthPhase phase, const std::uint8_t step) noexcept {
  return static_cast<std::uint8_t>((static_cast<std::uint8_t>(phase) << 4U) | step);
}
bool join_sub_decode(std::uint8_t sub, JoinAuthPhase& phase, std::uint8_t& step) noexcept;

// Object lane (G-SEC P4 §7.3): join-relay objects and member end-session
// objects share the Wire chunk/reply carriers (FrameTypes 5/6) but never an
// assembly. The lane bit lives in the sub byte, so the slot's (carrier,
// sub, id) key already separates the lanes and join golden bytes stay
// identical. End chunks never ride RLD1.
enum class ObjectLane : std::uint8_t { JoinRelay = 0, EndSession = 1 };
// end_sub = 0x80 | (phase << 4) | step, phases 4/5 only: 0xC1..0xC4 and
// 0xD1..0xD3. Member EDHOC has no step-5 error object.
constexpr std::uint8_t kEndSubLaneBit = 0x80;
constexpr std::uint8_t end_sub(const JoinAuthPhase phase, const std::uint8_t step) noexcept {
  return static_cast<std::uint8_t>(kEndSubLaneBit | join_sub(phase, step));
}
constexpr std::uint8_t object_sub(const ObjectLane lane, const JoinAuthPhase phase,
                                  const std::uint8_t step) noexcept {
  return lane == ObjectLane::EndSession ? end_sub(phase, step) : join_sub(phase, step);
}
bool object_sub_decode(std::uint8_t sub, ObjectLane& lane, JoinAuthPhase& phase,
                       std::uint8_t& step) noexcept;
// RLD1: the chunk id is the first four transaction-nonce bytes (big-endian).
std::uint32_t join_rld1_object_id(const JoinNonce& nonce) noexcept;

// Chunk: 0 u8 ver = 1 | 1 u8 sub | 2 u32 id (nonzero) | 6 u16 offset |
//        8 u16 total | 10 data
//   total > join_single_frame_max(carrier) and <= 1024; offset = k * grid;
//   data length = min(grid, total - offset), exactly.
struct JoinChunk {
  JoinAuthPhase phase{JoinAuthPhase::EdhocMessage};
  std::uint8_t step{1};
  std::uint32_t id{0};
  std::uint16_t offset{0};
  std::uint16_t total{0};
  ByteView data{};
  ObjectLane lane{ObjectLane::JoinRelay};
};

// Reply: 0 u8 ver = 1 | 1 u8 sub | 2 u32 id | 6 u16 received | 8 u8 status |
//        9 u8 reserved = 0   (10 B, 02 §5.3)
//   received = contiguous prefix held by the receiver; Complete carries the
//   object's total. Aborted asks the sender to restart the object.
enum class JoinReplyStatus : std::uint8_t {
  Progress = 0,
  Complete = 1,
  Aborted = 2,
};
struct JoinReply {
  JoinAuthPhase phase{JoinAuthPhase::EdhocMessage};
  std::uint8_t step{1};
  std::uint32_t id{0};
  std::uint16_t received{0};
  JoinReplyStatus status{JoinReplyStatus::Progress};
  ObjectLane lane{ObjectLane::JoinRelay};
};

Status join_chunk_encode(JoinCarrier carrier, const JoinChunk& chunk, MutableByteView out,
                         std::size_t& written) noexcept;
Status join_chunk_decode(JoinCarrier carrier, ByteView encoded, JoinChunk& out) noexcept;
Status join_reply_encode(const JoinReply& reply, MutableByteView out,
                         std::size_t& written) noexcept;
Status join_reply_decode(ByteView encoded, JoinReply& out) noexcept;

// --- Bounded object slot -----------------------------------------------------------
// One 1024 B buffer that holds EITHER an inbound assembly OR an outbound
// object awaiting its receiver's Complete reply. Chunks land on the fixed
// grid in any order; an exact duplicate is re-acknowledged, a chunk whose
// bytes differ from the held ones (or whose total changes) aborts the
// assembly (Conflict), a chunk of another object while one is assembling is
// refused (Busy), and an assembly older than its timeout is discarded. After
// Complete the slot remembers the object key so a late duplicate chunk
// re-sends the Complete reply instead of starting over — also while the
// slot already sends another object (only reset() forgets it).
class JoinObjectSlot {
 public:
  enum class Mode : std::uint8_t { Idle = 0, Assembling, Assembled, Sending };
  enum class Outcome : std::uint8_t {
    Progress = 0,  // stored (or exact duplicate): send `reply`
    Complete,      // whole object held: send `reply`, then read assembled()
    Repeat,        // duplicate chunk of the object completed last: re-send Complete
    Conflict,      // differing bytes / total: assembly dropped, reply Aborted
    Busy,          // another object is assembling or sending: dropped, no reply
    Rejected,      // chunk does not belong here (bad key/total): dropped
  };
  struct Accepted {
    Outcome outcome{Outcome::Rejected};
    JoinReply reply{};
    bool send_reply{false};
  };
  enum class ReplyOutcome : std::uint8_t {
    Ignored = 0,  // not for the object being sent
    Progress,     // receiver progress recorded
    Done,         // receiver holds the whole object; slot is Idle again
    Restart,      // receiver aborted: every chunk is due again
  };

  Mode mode() const noexcept { return mode_; }
  void reset() noexcept;

  // --- inbound
  Accepted accept(JoinCarrier carrier, const JoinChunk& chunk, MonotonicMs now_ms) noexcept;
  // Valid in Assembled until reset()/load()/the next accept of a new object.
  ByteView assembled() const noexcept;
  JoinAuthPhase phase() const noexcept { return phase_; }
  std::uint8_t step() const noexcept { return step_; }
  std::uint32_t id() const noexcept { return id_; }
  ObjectLane lane() const noexcept { return lane_; }
  // Wipes the buffer and returns to Idle in any mode, keeping the key of
  // the object completed last for Repeat detection (the owner consumed or
  // converted the object).
  void release_assembled() noexcept;
  // Occupant tag: bumped on every mode change, so a value captured before
  // a callback still names the occupant that was current then.
  std::uint32_t generation() const noexcept { return generation_; }
  // release_assembled() only while the slot still holds the occupant that
  // `expected` names — a callback that re-entered the owner (a fresh send,
  // a close, a new assembly) is left alone.
  void release_assembled_if(std::uint32_t expected) noexcept;

  // --- outbound
  // Copies `object` (> the carrier's single-frame limit, <= 1024 B) and
  // marks every chunk due. The caller emits chunk_at(i) for due chunks.
  // `lane` selects the chunk sub namespace (P4 §7.3); the default keeps the
  // join-relay 0x41..0x53 bytes. End objects never load on Rld1.
  Status load(JoinCarrier carrier, JoinAuthPhase phase, std::uint8_t step, std::uint32_t id,
              ByteView object, MonotonicMs now_ms,
              ObjectLane lane = ObjectLane::JoinRelay) noexcept;
  // In-place variant: the object was built in writable_buffer() already.
  Status load_in_place(JoinCarrier carrier, JoinAuthPhase phase, std::uint8_t step,
                       std::uint32_t id, std::size_t size, MonotonicMs now_ms,
                       ObjectLane lane = ObjectLane::JoinRelay) noexcept;
  MutableByteView writable_buffer() noexcept { return MutableByteView{data_.data(), data_.size()}; }
  std::size_t chunk_total() const noexcept;
  Status chunk_at(std::size_t index, JoinChunk& out) const noexcept;
  // Chunks the receiver has not confirmed (bit i = chunk i).
  std::uint16_t pending_mask() const noexcept;
  ReplyOutcome on_reply(const JoinReply& reply, MonotonicMs now_ms) noexcept;
  // Retransmission bookkeeping for Sending: marks the send time; the owner
  // decides when to retransmit (last_send_ms + interval) and gives up after
  // its own attempt budget.
  void note_sent(MonotonicMs now_ms) noexcept;
  MonotonicMs last_send_ms() const noexcept { return last_send_ms_; }
  std::uint8_t sends() const noexcept { return sends_; }

  // --- timing
  MonotonicMs started_ms() const noexcept { return started_ms_; }
  // Drops an Assembling object older than `timeout_ms`. True if dropped.
  bool expire(MonotonicMs now_ms, std::uint32_t timeout_ms) noexcept;

 private:
  // Drops the current assembly but keeps the completed-object memory.
  void drop_keep_completed() noexcept;
  std::uint16_t full_mask() const noexcept;
  std::uint16_t contiguous() const noexcept;

  std::array<std::uint8_t, kJoinObjectMax> data_{};
  Mode mode_{Mode::Idle};
  JoinCarrier carrier_{JoinCarrier::Rld1};
  ObjectLane lane_{ObjectLane::JoinRelay};
  JoinAuthPhase phase_{JoinAuthPhase::EdhocMessage};
  std::uint8_t step_{0};
  std::uint32_t id_{0};
  std::uint16_t total_{0};
  std::uint16_t have_{0};  // inbound: received chunks; outbound: confirmed chunks
  MonotonicMs started_ms_{0};
  MonotonicMs last_send_ms_{0};
  std::uint8_t sends_{0};
  // Bumped on every mode change: separates the occupant a callback saw
  // from one a reentrant call installed (see release_assembled_if).
  std::uint32_t generation_{0};
  // Last completed inbound object (Repeat detection).
  bool completed_valid_{false};
  JoinCarrier completed_carrier_{JoinCarrier::Rld1};
  std::uint8_t completed_sub_{0};
  std::uint32_t completed_id_{0};
  std::uint16_t completed_total_{0};
};

// ===================================================================================
// Wire relay object (02 §7.1): RelayHeader 24 B + message
// ===================================================================================
enum class RelayDirection : std::uint8_t { Up = 1, Down = 2 };
enum class RelayState : std::uint8_t {
  Continue = 0,  // more messages follow
  Final = 1,     // down only: last message of the exchange; the proxy frees its slot
  Abort = 2,     // either way: body is the 5 B RelayAbortBody
};

// RelayHeader (24 B):
//   0 u8 ver = 1 | 1 u8 dir (1 up, 2 down) | 2 u32 relay_id (nonzero)
//   6 u64 proxy NodeId | 14 6B joiner MAC (observed by the proxy)
//  20 u8 step | 21 u8 status (RelayState) | 22 i8 joiner_rssi_dbm (up only,
//     <= 0; down 0) | 23 u8 phase (4 EDHOC, 5 RLRES1)
// Body rules:
//   up   Continue  EDHOC steps 1/3/5, RLRES1 steps 1/3; message 1..960 B
//   down Continue  EDHOC step 2, RLRES1 step 2;         message 1..960 B
//   down Final     EDHOC steps 4/5, RLRES1 step 2;       message 1..960 B
//   Abort          any valid step of the phase; body = RelayAbortBody
//                  (up: status Aborted; down: AuthorityUnreachable/Busy/Aborted)
constexpr std::uint8_t kRelayVersion = 1;
constexpr std::size_t kRelayHeaderSize = 24;
constexpr std::size_t kRelayObjectMax = kRelayHeaderSize + kJoinMessageMax;  // 984
static_assert(kRelayObjectMax <= kJoinObjectMax, "relay object fits one object slot");

struct RelayHeader {
  RelayDirection dir{RelayDirection::Up};
  std::uint32_t relay_id{0};
  NodeId proxy{kInvalidNodeId};
  MacAddress joiner_mac{};
  JoinAuthPhase phase{JoinAuthPhase::EdhocMessage};
  std::uint8_t step{1};
  RelayState state{RelayState::Continue};
  std::int8_t joiner_rssi_dbm{0};
};

// Abort body (5 B): status u8 (RelayStatusCode) | retry_after_ms u32 (<= 600000).
constexpr std::size_t kRelayAbortBodySize = 5;
struct RelayAbortBody {
  RelayStatusCode status{RelayStatusCode::Aborted};
  std::uint32_t retry_after_ms{0};
};

struct RelayObject {
  RelayHeader header{};
  ByteView message{};       // Continue / Final
  RelayAbortBody abort{};   // Abort
};

Status relay_object_validate(const RelayObject& object) noexcept;
std::size_t relay_object_encoded_size(const RelayObject& object) noexcept;
Status relay_object_encode(const RelayObject& object, MutableByteView out,
                           std::size_t& written) noexcept;
Status relay_object_decode(ByteView encoded, RelayObject& out) noexcept;

// Single-frame carriage (object <= 128 B): up and down Continue ride Wire
// FrameType 3 (BootstrapAuth); down Final/Abort ride FrameType 4
// (MembershipResult) so the proxy releases its slot on the final type; an up
// Abort rides type 3. Larger objects ride FrameType 5 chunks (sub = phase/
// step, id = relay_id) acknowledged by FrameType 6 receipts.
FrameType relay_single_frame_type(const RelayHeader& header) noexcept;
Status relay_single_frame_decode(FrameType type, ByteView payload, RelayObject& out) noexcept;

// ===================================================================================
// Lane classification and admission (02 §4, §7.1, §9; 06-membership-admission §3-4)
// ===================================================================================
// RLD1 frames of the zero-touch / SDK v1 object lane: DISCOVER/OFFER body v3,
// BootstrapAuth phases 4-6, and chunks/replies whose sub is a phase-4/5 step.
// The owner hands them to the engine that owns the transaction nonce; legacy
// frames keep going to NeighborDiscovery unchanged.
bool zt_rld1_frame(const autonomy::Rld1Envelope& env) noexcept;

// RLD1 admission (after zt_rld1_frame): the local membership decides the
// role — a node that is not yet a member (Discovering/Authenticating) is the
// JOINER, a Member is a PROXY; nothing else talks on this lane.
//   joiner TX DISCOVER v3 (Discovering/Authenticating); RX OFFER v3;
//          Authenticating: TX up steps, RX down steps + RelayStatus, chunks of
//          up steps TX / down steps RX, replies the other way
//   proxy  RX DISCOVER v3; TX OFFER v3; RX up steps, TX down steps + RelayStatus;
//          chunks/replies accordingly. A Member never sends DISCOVER v3.
// A frame that does not parse far enough to classify is ProtocolError; a
// frame the role may not send/receive is AuthorizationFailed.
Status zt_admit_rld1(MembershipState local, AdmissionDirection direction,
                     const autonomy::Rld1Envelope& env) noexcept;

// Wire relay admission (02 §7.1): both ends are Members; only FrameTypes
// 3/4/5/6; a proxy exchanges relay frames with its configured gateway only;
// the gateway accepts relay frames from members and sends only to the proxy
// named in the object. `peer` is the verified mesh origin (RX) or
// destination (TX). Frames that are not relay frames are not this lane's.
Status zt_admit_relay(MembershipState local, bool local_is_gateway, AdmissionDirection direction,
                      FrameType type, NodeId peer, NodeId gateway) noexcept;

}  // namespace routeloom::sdkv1
