#pragma once

// SDK v1 zero-touch join: EDHOC External Authorization Data items
// (docs/design/sdk-v1/02-zero-touch-join.md §6.1/§6.2, 04 §6.1; plan P2-3).
//
// The join EDHOC (device = Initiator, Site Authority = Responder) carries
// one RouteLoom EAD item per message:
//
//   m1  EAD_1  JoinIntent   (plaintext)         12 B value
//   m2  EAD_2  SiteOffer    (encrypted)         22 B value
//   m3  EAD_3  JoinRequest  (encrypted)         26 B value
//   m4  EAD_4  JoinResult   (encrypted)   12 B head + verdict body
//
// EAD item (RFC 9528 §3.8): `ead_label int, ead_value bstr`. The four
// labels are outside the IANA EDHOC EAD registry range (0..65535 is the
// whole registrable space; there is no private-use range), so they can
// never collide with a registered item, and every item is sent CRITICAL
// (negative label): a Responder or Initiator that does not implement the
// RouteLoom join must abort with an EDHOC error rather than silently
// complete an exchange whose authorization it ignored.
//
//   JoinIntent  = -65537 -> 3a 00 01 00 00 <bstr 12 B>
//   SiteOffer   = -65538 -> 3a 00 01 00 01 <bstr 22 B>
//   JoinRequest = -65539 -> 3a 00 01 00 02 <bstr 26 B>
//   JoinResult  = -65540 -> 3a 00 01 00 03 <bstr 12..520 B>
//
// Values are fixed-width big-endian structures; reserved bytes and
// undefined flag bits are zero; every length is exact. Parsing an EAD
// field (the CBOR sequence of items) is strict: the one expected item must
// appear exactly once, critical, with a canonical definite bstr value;
// padding items (label 0, RFC 9528 §3.8.1) are skipped as the RFC
// requires; any other item, a non-canonical integer or length, or
// trailing bytes is a ProtocolError.
//
// JoinResult bodies (02 §6.1):
//   Allow              u16 membercert_len | MemberCert (RLCW1, 1..256) |
//                      SitePackage 120 B | u16 ticket_len | AssignmentTicket
//                      (0..128 B, opaque here; A2 only)
//   PendingAssignment  pending ticket 1..48 B (opaque to the device)
//   Removed            RemovalNotice (04 §6.1): restricted ES256 COSE_Sign1,
//                      external AAD "RouteLoom/removal-notice/v1" 00 ||
//                      network u64, 28 B payload, exactly 103 B
//   DenyNotHere / DenyBlocked / AuthorityBusy   empty
//
// The exact bytes are pinned by protocol/sdkv1-golden/ead/ (generated by
// the independent tools/gen_sdkv1_ead_vectors.py) and mirrored in Rust by
// host/routeloom-join. Every decode is allocation-free: the JoinResult
// decode borrows its byte views from the input.

#include <cstddef>
#include <cstdint>

#include "routeloom/rlcw1.hpp"
#include "routeloom/sdkv1_records.hpp"  // RevocationReason
#include "routeloom/status.hpp"
#include "routeloom/types.hpp"

namespace routeloom::sdkv1 {

// --- EAD items ------------------------------------------------------------------
// Absolute label values; the wire carries -label (critical).
enum class JoinEad : std::uint32_t {
  Intent = 65537,   // EAD_1
  Offer = 65538,    // EAD_2
  Request = 65539,  // EAD_3
  Result = 65540,   // EAD_4
};

constexpr std::uint8_t kJoinEadVersion = 1;
constexpr std::size_t kJoinEadLabelSize = 5;  // 3a 00 01 00 0x

// --- JoinIntent (m1, plaintext: nothing identifying) ---------------------------
//  0 u8 ver = 1 | 1 u8 flags = 0 | 2 u32 org_hint | 6 u32 profile_bits |
// 10 u16 reserved = 0
constexpr std::size_t kJoinIntentSize = 12;
constexpr std::uint32_t kJoinProfileRljoin1 = 1u << 0;  // EDHOC join (required)
constexpr std::uint32_t kJoinProfileRlres1 = 1u << 1;   // pending-ticket retry
constexpr std::uint32_t kJoinProfileMask = 0x3u;

struct JoinIntent {
  std::uint32_t org_hint{0};
  std::uint32_t profile_bits{kJoinProfileRljoin1};
};

// profile_bits: RLJOIN1 set, known bits only.
Status join_intent_validate(const JoinIntent& intent) noexcept;
Status join_intent_encode(const JoinIntent& intent, ByteBuffer<kJoinIntentSize>& out) noexcept;
Status join_intent_decode(ByteView value, JoinIntent& out) noexcept;

// 02 §5.1: first4(SHA-256("RouteLoom/org-hint/v1" 00 || Site CA pubkey 64 B)),
// big-endian. The Site Authority compares a JoinIntent's org_hint with the
// hint of the Site CA that issued its SiteCert (unauthenticated filter only).
std::uint32_t join_org_hint(const P256PublicKey& site_ca_pubkey) noexcept;
// 02 §5.2: first4(SHA-256("RouteLoom/site-hint/v1" 00 || site_id u64)).
std::uint32_t join_site_hint(std::uint64_t site_id) noexcept;

// --- SiteOffer (m2) --------------------------------------------------------------
//  0 u8 ver = 1 | 1 u8 flags = 0 | 2 u64 site_id | 10 u32 network_low32 |
// 14 u32 site_epoch | 18 u16 decision_timeout_ms (500..5000) | 20 u16 reserved = 0
constexpr std::size_t kSiteOfferSize = 22;
constexpr std::uint16_t kDecisionTimeoutMinMs = 500;
constexpr std::uint16_t kDecisionTimeoutMaxMs = 5000;

struct SiteOffer {
  std::uint64_t site_id{0};
  std::uint32_t network_low32{0};
  std::uint32_t site_epoch{0};
  std::uint16_t decision_timeout_ms{2000};
};

Status site_offer_validate(const SiteOffer& offer) noexcept;
Status site_offer_encode(const SiteOffer& offer, ByteBuffer<kSiteOfferSize>& out) noexcept;
Status site_offer_decode(ByteView value, SiteOffer& out) noexcept;
constexpr NetworkId site_offer_network(const SiteOffer& offer) noexcept {
  return (static_cast<NetworkId>(offer.site_epoch) << 32U) | offer.network_low32;
}
// Device, after authenticating m2: the offer names the SiteCert's site,
// network_low32 and site_epoch. Mismatch -> AuthorizationFailed.
Status site_offer_matches_site_cert(const SiteOffer& offer, const CertClaims& site_cert) noexcept;

// --- JoinRequest (m3) ------------------------------------------------------------
//  0 u8 ver = 1 | 1 u8 flags = 0 | 2 u16 model | 4 u32 fw_version |
//  8 u32 capability | 12 u8 requested_role | 13 u8 reserved = 0 |
// 14 u64 last_site_id | 22 u32 last_generation
constexpr std::size_t kJoinRequestSize = 26;
constexpr std::uint32_t kJoinCapabilitySleepy = 1u << 0;
constexpr std::uint32_t kJoinCapabilityRelay = 1u << 1;
constexpr std::uint32_t kJoinCapabilityGateway = 1u << 2;
constexpr std::uint32_t kJoinCapabilityMask = 0x7u;

struct JoinRequest {
  std::uint16_t model{0};
  std::uint32_t fw_version{0};
  std::uint32_t capability{0};
  std::uint8_t requested_role{static_cast<std::uint8_t>(kMemberRoleEndpoint)};
  std::uint64_t last_site_id{0};    // 0 = never a member
  std::uint32_t last_generation{0}; // 0 iff last_site_id == 0
};

// capability known bits; requested_role nonzero MemberCert role bits, relay
// only with the relay capability, gateway only with the gateway capability;
// last_site_id 0 (then last_generation 0) or a valid id with generation >= 1.
Status join_request_validate(const JoinRequest& request) noexcept;
Status join_request_encode(const JoinRequest& request,
                           ByteBuffer<kJoinRequestSize>& out) noexcept;
Status join_request_decode(ByteView value, JoinRequest& out) noexcept;
// Site Authority, after verifying the DevCert from m3: the request's model
// is the certified model. Mismatch -> AuthorizationFailed.
Status join_request_matches_dev_cert(const JoinRequest& request,
                                     const CertClaims& dev_cert) noexcept;

// --- SitePackage (Allow body) ----------------------------------------------------
//   0 u8 ver = 1 | u8 flags = 0 | u16 reserved = 0
//   4 u64 site_id | 12 u64 network
//  20 u32 rs_epoch | 24 u32 gk_epoch (>= 1) | 28 32B GK (nonzero)
//  60 u8 channel (1..14) | u8 role | u8 gateway_count (1..4) | u8 reserved = 0
//  64 u32 channel_epoch | 68 4 x u64 gateways (count valid, unique, zero tail)
// 100 u64 authority_time_s | 108 u32 time_uncertainty_ms
// 112 u32 membership_revision | 116 u32 reserved = 0
constexpr std::size_t kSitePackageSize = 120;
constexpr std::size_t kSitePackageGatewayMax = 4;

struct SitePackage {
  std::uint64_t site_id{0};
  NetworkId network{0};
  std::uint32_t rs_epoch{0};
  std::uint32_t gk_epoch{0};
  std::array<std::uint8_t, 32> gk{};
  std::uint8_t channel{0};
  std::uint8_t role{0};
  std::uint8_t gateway_count{0};
  std::uint32_t channel_epoch{0};
  std::array<NodeId, kSitePackageGatewayMax> gateways{};
  std::uint64_t authority_time_s{0};
  std::uint32_t time_uncertainty_ms{0};
  std::uint32_t membership_revision{0};
};

Status site_package_validate(const SitePackage& package) noexcept;
Status site_package_encode(const SitePackage& package,
                           ByteBuffer<kSitePackageSize>& out) noexcept;
Status site_package_decode(ByteView bytes, SitePackage& out) noexcept;

// --- RemovalNotice (04 §6.1) -----------------------------------------------------
// payload: 0 u8 ver = 1 | 1 u8 reason (1..4, RRS1 reasons) | 2 u16 reserved = 0 |
//          4 u64 site_id | 12 u64 node_id | 20 u32 generation (>= 1) |
//          24 u32 rs_epoch (>= 1)
constexpr std::size_t kRemovalNoticePayloadSize = 28;
// d2 84 43 a1 01 26 a0 | 58 1c payload | 58 40 sig
constexpr std::size_t kRemovalNoticeObjectSize = 7 + 2 + kRemovalNoticePayloadSize + 2 + 64;
static_assert(kRemovalNoticeObjectSize == 103, "04 §6.1: RemovalNotice ~110 B");
inline constexpr char kRemovalNoticeDomain[] = "RouteLoom/removal-notice/v1";
constexpr std::size_t kRemovalNoticeAadSize = sizeof(kRemovalNoticeDomain) + 8;  // 36

struct RemovalNotice {
  RevocationReason reason{RevocationReason::Removed};
  std::uint64_t site_id{0};
  NodeId node_id{kInvalidNodeId};
  std::uint32_t generation{0};
  std::uint32_t rs_epoch{0};
};

Status removal_notice_validate(const RemovalNotice& notice) noexcept;
Status removal_notice_payload_encode(const RemovalNotice& notice,
                                     ByteBuffer<kRemovalNoticePayloadSize>& out) noexcept;
Status removal_notice_payload_decode(ByteView payload, RemovalNotice& out) noexcept;
Status removal_notice_aad(NetworkId network, ByteBuffer<kRemovalNoticeAadSize>& out) noexcept;
Status removal_notice_assemble(ByteView payload, ByteView signature,
                               ByteBuffer<kRemovalNoticeObjectSize>& out) noexcept;
// Structure only (envelope + payload), no signature.
Status removal_notice_decode(ByteView object, RemovalNotice& out) noexcept;
// 04 §6.1 acceptance (device, from its own RLS1): signature under the SAK
// with the AAD bound to `own_network`, site_id == own site, node_id == own
// node, generation >= own MemberCert generation. Malformed -> error; any
// failed check -> verified = false. Only verified == true may erase state.
Status removal_notice_verify(ByteView object, const P256PublicKey& sak_pubkey,
                             std::uint64_t own_site_id, NetworkId own_network,
                             NodeId own_node, std::uint32_t own_generation,
                             RemovalNotice& out, bool& verified,
                             const Es256Verifier& verifier = default_es256_verifier()) noexcept;

// --- JoinResult (m4) --------------------------------------------------------------
//  0 u8 ver = 1 | 1 u8 verdict | 2 u16 reason = 0 | 4 u32 retry_after_s |
//  8 u16 body_len | 10 u16 reserved = 0 | 12 body
enum class JoinVerdict : std::uint8_t {
  Allow = 1,
  PendingAssignment = 2,
  DenyNotHere = 3,
  DenyBlocked = 4,
  Removed = 5,
  AuthorityBusy = 6,
};

constexpr std::size_t kJoinResultHeadSize = 12;
constexpr std::size_t kPendingTicketMax = 48;       // 02 §6.1, RLRES1 R1 ticket
constexpr std::size_t kAssignmentTicketMax = 128;   // format not pinned yet (A2)
constexpr std::size_t kJoinAllowBodyMin = 2 + 1 + kSitePackageSize + 2;
constexpr std::size_t kJoinAllowBodyMax =
    2 + kRlcw1CertMax + kSitePackageSize + 2 + kAssignmentTicketMax;  // 508
constexpr std::size_t kJoinResultMax = kJoinResultHeadSize + kJoinAllowBodyMax;  // 520
// retry_after_s: PendingAssignment 30..3600 (API1 join.decide range),
// AuthorityBusy 1..3600, every other verdict 0.
constexpr std::uint32_t kPendingRetryMinS = 30;
constexpr std::uint32_t kRetryAfterMaxS = 3600;

// A decoded (or to-be-encoded) JoinResult. Only the fields of `verdict`
// may be set: the others stay empty/default (validate enforces it). Byte
// views borrow from the decoded input.
struct JoinResult {
  JoinVerdict verdict{JoinVerdict::DenyNotHere};
  std::uint32_t retry_after_s{0};
  ByteView member_cert{};        // Allow: RLCW1 MemberCert
  SitePackage site_package{};    // Allow
  ByteView assignment_ticket{};  // Allow: empty unless A2
  ByteView pending_ticket{};     // PendingAssignment: 1..48 B
  ByteView removal_notice{};     // Removed: 103 B Sign1
};

// Structure: verdict-specific retry range and body shape; the MemberCert
// decodes as a MemberCert, the SitePackage validates, the RemovalNotice
// decodes. Cross-field agreement is join_allow_verify's job.
Status join_result_validate(const JoinResult& result) noexcept;
std::size_t join_result_encoded_size(const JoinResult& result) noexcept;
Status join_result_encode(const JoinResult& result, ByteBuffer<kJoinResultMax>& out) noexcept;
Status join_result_decode(ByteView value, JoinResult& out) noexcept;

// 02 §10.2, device side, for an Allow already decoded: (1) MemberCert
// signed by the SAK of the SiteCert authenticated in m2; (2) sub == own
// node, cnf == own key, iss == SiteCert sub; (3) MemberCert network ==
// SitePackage network, low32/site_epoch == SiteCert; SitePackage site_id
// == SiteCert sub; (4) generation >= 1, known role bits, SitePackage role
// == MemberCert role; (5) A2: an AssignmentTicket is required — its format
// is not pinned yet, so strict mode fails closed (Unsupported) for any
// Allow; (6) SitePackage shape (decode). A result that is not an Allow is
// InvalidArgument; a failed check is verified = false (store nothing and
// avoid the site). `member_out` is filled when the MemberCert decodes.
Status join_allow_verify(const JoinResult& result, const CertClaims& site_cert, NodeId node,
                         const P256PublicKey& device_pubkey, bool strict_assignment,
                         CertClaims& member_out, bool& verified,
                         const Es256Verifier& verifier = default_es256_verifier()) noexcept;

// --- EAD field (CBOR sequence of items) -----------------------------------------
constexpr std::size_t kJoinEadItemMax = kJoinEadLabelSize + 3 + kJoinResultMax;  // 528
// Bound on a whole EAD field accepted by ead_find (the reassembled BA
// object is at most 1024 B, 02 §5.3).
constexpr std::size_t kJoinEadFieldMax = 1024;

// One critical item: -label || bstr(value). The value must match the
// item's size rule (exact for Intent/Offer/Request, 12..520 for Result).
Status join_ead_item_encode(JoinEad label, ByteView value,
                            ByteBuffer<kJoinEadItemMax>& out) noexcept;
// Strict EAD field parse (see the file comment): returns the value of the
// single `expected` item, borrowed from `ead`.
Status join_ead_find(ByteView ead, JoinEad expected, ByteView& value) noexcept;

}  // namespace routeloom::sdkv1
