#pragma once

// SDK v1 persistent record codecs (docs/design/sdk-v1/08 P1-3):
//   RLI1 — device identity, site-independent (02-zero-touch-join.md §2)
//   RLS1 — site membership (02 §10.3)
//   RRS1 — SAK-signed revocation set + its storage record (04 §2)
//   RLP1 — one fixed-size resumption-cache slot (05-nvs-state-37.md §3.2)
//
// All integers big-endian, reserved bytes zero, every record closed by
// crc32_iso_hdlc over [0, len-4). RLI1/RLS1/RRS1 records share the sealed
// head used by RLT1/RLC1: magic u32 | format u16 | used_len u16 |
// schema u32 | seal u32 (0 = pending, a per-record committed value).
// RLS1 and the RRS1 storage record add `commit_seq u32` at offset 16 —
// the A/B ordinal of their alternating dual-slot store (sdkv1_store.hpp).
// RLI1 is written once (office) as an identical twin pair and has no
// ordinal, exactly like RLC1.
//
// The exact layouts are pinned by protocol/sdkv1-golden/ (README there),
// generated by tools/gen_sdkv1_vectors.py and consumed byte-for-byte by
// the C++ and Rust harnesses.

#include <array>
#include <cstddef>
#include <cstdint>

#include "routeloom/authority.hpp"          // Digest256
#include "routeloom/device_credential.hpp"  // CredentialKeyLocation (RLC1 values)
#include "routeloom/rlcw1.hpp"
#include "routeloom/status.hpp"
#include "routeloom/types.hpp"

namespace routeloom::sdkv1 {

constexpr std::uint32_t kSealPending = 0U;
constexpr std::uint16_t kRecordFormat = 1;
constexpr std::uint32_t kRecordSchema = 1;
constexpr std::size_t kSealedHeadSize = 16;
constexpr std::size_t kSequencedHeadSize = 20;  // + commit_seq u32
constexpr std::size_t kRecordSealOffset = 12;
constexpr std::size_t kRecordSeqOffset = 16;

// --- RLI1 --------------------------------------------------------------------
//   0 u32 magic "RLI1" | 4 u16 format | 6 u16 used_len | 8 u32 schema | 12 u32 seal
//  16 u64 node_id
//  24 u8 key_location | u8 flags | u8 anchor_count (1..3) | u8 reserved
//  28 u32 reserved
//  32 32B kid = SHA-256(canonical COSE_Key(pubkey))
//  64 64B pubkey X||Y
// 128 32B key_material (location 1: private scalar; 2/3: handle; 0: zero)
// 160 anchors[n] x 80: anchor_id u64 | kind u8 | status u8 | reserved 6 | pubkey 64
// 160+80n u16 devcert_len (1..256) | u16 reserved
// 164+80n DevCert
// len-4 u32 crc32
constexpr std::uint32_t kIdentityMagic = 0x524C4931U;  // "RLI1"
constexpr std::uint32_t kIdentitySealCommitted = 0x1DE71771U;
constexpr std::size_t kIdentitySlotBytes = 1024;
constexpr std::size_t kIdentityAnchorMax = 3;
constexpr std::size_t kIdentityAnchorEntrySize = 80;
constexpr std::size_t kIdentityFixedSize = 160;
constexpr std::size_t kIdentityRecordMin = kIdentityFixedSize + kIdentityAnchorEntrySize + 4 + 1 + 4;
constexpr std::size_t kIdentityRecordMax =
    kIdentityFixedSize + kIdentityAnchorMax * kIdentityAnchorEntrySize + 4 + kRlcw1CertMax + 4;
static_assert(kIdentityRecordMax == 664, "02 §2: RLI1 max 664 B");

constexpr std::uint8_t kIdentityFlagConsoleLocked = 0x01;
constexpr std::uint8_t kIdentityFlagStrictAssignment = 0x02;  // A2 mode
constexpr std::uint8_t kIdentityFlagMask = 0x03;

enum class AnchorKind : std::uint8_t {
  SiteCa = 1,              // verifies SiteCert
  AssignmentVerifier = 2,  // A2: verifies AssignmentTicket
};
enum class AnchorStatus : std::uint8_t { Active = 1, Disabled = 2 };

struct IdentityAnchor {
  std::uint64_t anchor_id{0};  // the SiteCert/ticket issuer id this key answers to
  AnchorKind kind{AnchorKind::SiteCa};
  AnchorStatus status{AnchorStatus::Active};
  P256PublicKey pubkey{};
};

struct IdentityRecord {
  NodeId node_id{kInvalidNodeId};
  CredentialKeyLocation key_location{CredentialKeyLocation::None};
  std::uint8_t flags{0};
  Digest256 kid{};
  P256PublicKey pubkey{};
  std::array<std::uint8_t, 32> key_material{};
  std::array<IdentityAnchor, kIdentityAnchorMax> anchors{};
  std::uint8_t anchor_count{0};
  ByteBuffer<kRlcw1CertMax> devcert{};
};

// Boot checks (02 §2): node_id not 0/all-ones; kid recompute; key
// location 0 -> zero material, 1 -> scalar reproduces pubkey; anchors
// 1..3 with unique nonzero ids, known kind/status, on-curve keys; >=1
// ACTIVE SiteCA; strict flag -> >=1 ACTIVE AssignmentVerifier; DevCert
// decodes as a DevCert with sub == node_id and cnf == pubkey (its
// signature is NOT checked: the device does not hold the Device CA key).
Status identity_validate(const IdentityRecord& record) noexcept;
std::size_t identity_encoded_size(const IdentityRecord& record) noexcept;
Status identity_record_encode(const IdentityRecord& record, std::uint32_t seal,
                              ByteBuffer<kIdentitySlotBytes>& out) noexcept;
// Committed record, strict: head, seal, exact length, CRC, schema, reserved
// zero, then identity_validate.
Status identity_record_decode(ByteView record, IdentityRecord& out) noexcept;
// Anchor lookup by id restricted to ACTIVE anchors of `kind`.
const IdentityAnchor* identity_active_anchor(const IdentityRecord& record,
                                             std::uint64_t anchor_id,
                                             AnchorKind kind) noexcept;
// SiteCert chain step (02 §10.1 ZT_HANDSHAKE): the SiteCert's issuer must
// name an ACTIVE SiteCA anchor and its signature must verify under it.
Status identity_verify_site_cert(const IdentityRecord& record, ByteView site_cert,
                                 CertClaims& out, bool& verified,
                                 const Es256Verifier& verifier = default_es256_verifier()) noexcept;

// --- RLS1 --------------------------------------------------------------------
//   0 u32 magic "RLS1" | 4 u16 format | 6 u16 used_len | 8 u32 schema | 12 u32 seal
//  16 u32 commit_seq
//  20 u64 site_id | 28 u64 network
//  36 u32 assignment_generation | 40 u32 rs_epoch_floor
//  44 u32 gk_epoch_current | 48 u32 gk_epoch_next (0 = none)
//  52 32B gk_current | 84 32B gk_next | 116 32B dams
// 148 u8 state | u8 role | u8 gateway_count | u8 channel
// 152 u32 channel_epoch | 156 u32 boot_witness
// 160 4 x u64 gateways
// 192 u16 sitecert_len | u16 membercert_len
// 196 SiteCert | MemberCert
// len-4 u32 crc32
// state 0 is the tombstone the removal path writes: every body byte zero,
// no certificates (200 B) — the "sealed empty record" of 04 §6.4.
constexpr std::uint32_t kSiteMagic = 0x524C5331U;  // "RLS1"
constexpr std::uint32_t kSiteSealCommitted = 0x5173AB1EU;
constexpr std::size_t kSiteSlotBytes = 1024;
constexpr std::size_t kSiteFixedSize = 196;
constexpr std::size_t kSiteGatewayMax = 4;
constexpr std::size_t kSiteRecordMin = kSiteFixedSize + 4;
constexpr std::size_t kSiteRecordMax = kSiteFixedSize + 2 * kRlcw1CertMax + 4;
static_assert(kSiteRecordMax == 712, "RLS1 max = 02 §10.3 708 B + commit_seq");

enum class SiteState : std::uint8_t { Cleared = 0, Member = 1 };

struct SiteRecord {
  SiteState state{SiteState::Cleared};
  std::uint64_t site_id{0};
  NetworkId network{0};
  std::uint32_t assignment_generation{0};
  std::uint32_t rs_epoch_floor{0};
  std::uint32_t gk_epoch_current{0};
  std::uint32_t gk_epoch_next{0};
  std::array<std::uint8_t, 32> gk_current{};
  std::array<std::uint8_t, 32> gk_next{};
  std::array<std::uint8_t, 32> dams{};
  std::uint8_t role{0};
  std::uint8_t gateway_count{0};
  std::uint8_t channel{0};
  std::uint32_t channel_epoch{0};
  std::uint32_t boot_witness{0};
  std::array<NodeId, kSiteGatewayMax> gateways{};
  ByteBuffer<kRlcw1CertMax> site_cert{};
  ByteBuffer<kRlcw1CertMax> member_cert{};
};

// Member: ids/network nonzero (network low32 too), generation >= 1,
// gk_epoch_current >= 1 with a nonzero key, gk_next present iff
// gk_epoch_next != 0 (and then > current), nonzero dams, role nonzero
// known bits, gateway_count 1..4 with unique valid ids and zero tail,
// channel 1..14, both certificates decode with their type and agree with
// the record (SiteCert sub/network_low32/site_epoch, MemberCert
// iss/network/generation/role). Cleared: everything zero.
Status site_validate(const SiteRecord& record) noexcept;
std::size_t site_encoded_size(const SiteRecord& record) noexcept;
Status site_record_encode(const SiteRecord& record, std::uint32_t seal,
                          std::uint32_t commit_seq,
                          ByteBuffer<kSiteSlotBytes>& out) noexcept;
Status site_record_decode(ByteView record, SiteRecord& out,
                          std::uint32_t* commit_seq = nullptr) noexcept;
// Cross-record binding (02 §10.2 step 2): MemberCert names this device.
Status site_matches_identity(const SiteRecord& site, const IdentityRecord& identity) noexcept;

// --- RRS1 --------------------------------------------------------------------
// Signed payload (04 §2), inside the restricted ES256 COSE_Sign1 with
// external AAD "RouteLoom/revocation-set/v1" 0x00 || network u64:
//   0 u8 ver = 1 | 1 u8 flags = 0 | 2 u16 count (<= 32)
//   4 u64 site_id | 12 u64 network
//  20 u32 rs_epoch (>= 1) | 24 u32 site_epoch_floor (<= network>>32)
//  28 entries x 16: node_id u64 | min_generation u32 (>= 1) |
//                   reason u8 (1..4) | reserved 3
// Entries strictly ascending by node_id.
// Storage record ("rlrevo", 640 B slot):
//   0 sealed head (magic "RRS1") | 16 u32 commit_seq | 20 COSE object | len-4 crc
// An object-less record (24 B) is the cleared tombstone.
constexpr std::uint8_t kRevocationVersion = 1;
constexpr std::size_t kRevocationEntryMax = 32;
constexpr std::size_t kRevocationHeadSize = 28;
constexpr std::size_t kRevocationEntrySize = 16;
constexpr std::size_t kRevocationPayloadMax =
    kRevocationHeadSize + kRevocationEntryMax * kRevocationEntrySize;  // 540
// d2 84 43 a1 01 26 a0 | 59 hi lo | payload | 58 40 | sig
constexpr std::size_t kRevocationObjectMax = 7 + 3 + kRevocationPayloadMax + 2 + 64;  // 616
inline constexpr char kRevocationDomain[] = "RouteLoom/revocation-set/v1";
constexpr std::size_t kRevocationAadSize = sizeof(kRevocationDomain) + 8;  // 36
constexpr std::uint32_t kRevocationMagic = 0x52525331U;  // "RRS1"
constexpr std::uint32_t kRevocationSealCommitted = 0x2E5E7C0DU;
constexpr std::size_t kRevocationSlotBytes = 640;
constexpr std::size_t kRevocationRecordMin = kSequencedHeadSize + 4;
constexpr std::size_t kRevocationRecordMax = kSequencedHeadSize + kRevocationObjectMax + 4;
static_assert(kRevocationRecordMax == kRevocationSlotBytes, "04 §2: rlrevo slot <= 640 B");

enum class RevocationReason : std::uint8_t { Removed = 1, Lost = 2, Replaced = 3, Blocked = 4 };

struct RevocationEntry {
  NodeId node_id{kInvalidNodeId};
  std::uint32_t min_generation{0};
  RevocationReason reason{RevocationReason::Removed};
};

struct RevocationSet {
  std::uint64_t site_id{0};
  NetworkId network{0};
  std::uint32_t rs_epoch{0};
  std::uint32_t site_epoch_floor{0};
  std::array<RevocationEntry, kRevocationEntryMax> entries{};
  std::uint8_t count{0};
};

Status revocation_validate(const RevocationSet& set) noexcept;
Status revocation_payload_encode(const RevocationSet& set,
                                 ByteBuffer<kRevocationPayloadMax>& out) noexcept;
Status revocation_payload_decode(ByteView payload, RevocationSet& out) noexcept;
Status revocation_aad(NetworkId network, ByteBuffer<kRevocationAadSize>& out) noexcept;
Status revocation_object_assemble(ByteView payload, ByteView signature,
                                  ByteBuffer<kRevocationObjectMax>& out) noexcept;
// Structure only (envelope + payload); no signature.
Status revocation_object_decode(ByteView object, RevocationSet& out) noexcept;
// Acceptance-side verification: structure, signature under the SAK with
// the AAD bound to `expected_network` (the device's own RLS1 network, never
// a transport claim), and site_id/network equal to the expectation.
// Malformed -> error; wrong site/network or bad signature -> verified=false.
Status revocation_object_verify(ByteView object, const P256PublicKey& sak_pubkey,
                                std::uint64_t expected_site_id, NetworkId expected_network,
                                RevocationSet& out, bool& verified,
                                const Es256Verifier& verifier = default_es256_verifier()) noexcept;
// Membership test: node's MemberCert (generation, site_epoch) is rejected
// by the set (generation < min_generation of its entry, or site_epoch
// below the floor).
bool revocation_rejects(const RevocationSet& set, NodeId node,
                        std::uint32_t generation, std::uint32_t site_epoch) noexcept;
// Same-network replacement rule (04 §2, P6): every entry of `old_set` is
// still present in `next` with a min_generation that did not decrease. Past
// revocations can only be compressed by a verified cutover (PR C), never by
// a plain replacement. Only the (node, min_generation) binding carries
// authority — a reason change alone is not an omission.
bool revocation_covers(const RevocationSet& old_set, const RevocationSet& next) noexcept;

Status revocation_record_encode(ByteView object, std::uint32_t seal,
                                std::uint32_t commit_seq,
                                ByteBuffer<kRevocationSlotBytes>& out) noexcept;
// Committed storage record: `object` borrows from `record`; an empty
// object is the cleared tombstone (out stays default).
Status revocation_record_decode(ByteView record, RevocationSet& out, ByteView& object,
                                std::uint32_t* commit_seq = nullptr) noexcept;

// --- Structure-only gates (dual-slot classifier) ------------------------------
// Head magic/format and used_len == record.size, internal lengths
// consistent with used_len, fixed reserved bytes zero. No seal, CRC or
// schema verdict and no semantic checks: passing only proves the record's
// fields (notably commit_seq) are positioned where the codec expects.
Status identity_record_structure(ByteView record) noexcept;
Status site_record_structure(ByteView record) noexcept;
Status revocation_record_structure(ByteView record) noexcept;

// --- RLP1 --------------------------------------------------------------------
//  0 u32 magic "RLP1" | 4 u8 format=1 | 5 u8 purpose (1 link, 2 end) |
//  6 u8 state (0 empty, 1 valid) | 7 u8 flags (bit0 pinned)
//  8 u64 peer node_id | 16 u64 network
// 24 8B peer_cert_id = first8(SHA-256(peer MemberCert))
// 32 u32 peer_generation | 36 u32 created_gk_epoch
// 40 u32 last_used_boot  | 44 u32 reserved
// 48 32B rms | 80 u32 crc32
// An empty slot (state 0) has every field after byte 6 zero (the RMS is
// scrubbed on invalidation); a missing/erased slot reads as empty too.
constexpr std::uint32_t kResumeMagic = 0x524C5031U;  // "RLP1"
constexpr std::uint8_t kResumeFormat = 1;
constexpr std::size_t kResumeSlotBytes = 84;
constexpr std::uint8_t kResumeFlagPinned = 0x01;

enum class ResumePurpose : std::uint8_t { Link = 1, End = 2 };

struct ResumeSlot {
  bool valid{false};
  ResumePurpose purpose{ResumePurpose::Link};
  std::uint8_t flags{0};
  NodeId peer{kInvalidNodeId};
  NetworkId network{0};
  std::array<std::uint8_t, 8> peer_cert_id{};
  std::uint32_t peer_generation{0};
  std::uint32_t created_gk_epoch{0};
  std::uint32_t last_used_boot{0};
  std::array<std::uint8_t, 32> rms{};
};

Status resume_validate(const ResumeSlot& slot) noexcept;
Status resume_slot_encode(const ResumeSlot& slot,
                          std::array<std::uint8_t, kResumeSlotBytes>& out) noexcept;
// Strict decode. An empty record decodes with valid=false.
Status resume_slot_decode(ByteView bytes, ResumeSlot& out) noexcept;
// first8(SHA-256(member_cert)).
void resume_peer_cert_id(ByteView member_cert, std::array<std::uint8_t, 8>& out) noexcept;

// --- RLP2 --------------------------------------------------------------------
// P4 membership/session records: one fixed-size resumption-cache slot with the
// enforceable 64-use ceiling (G-SEC P4 design §6.2). RLP1's reserved word is
// NOT redefined in place: old RLP1 blobs are a safe cache miss and the next
// full EDHOC overwrites them. Fixed NVS key names stay unchanged.
//  0 u32 magic "RLP2" | 4 u8 format=1 | 5 u8 purpose (1 link, 2 end; 0 empty)
//  6 u8 state (0 empty, 1 valid) | 7 u8 flags (bit0 pinned)
//  8 u64 peer node_id | 16 u64 network
// 24 8B peer_cert_id = first8(SHA-256(peer MemberCert))
// 32 8B local_cert_id = first8(SHA-256(local MemberCert))
// 40 u32 peer_generation | 44 u32 peer_role (nonzero known bits)
// 48 u32 created_gk_epoch | 52 u32 last_used_boot
// 56 u32 reserved_uses (0..64 durable high-water)
// 60 32B rms | 92 u32 crc32
// An empty slot (state 0) has every field after byte 6 zero.
constexpr std::uint32_t kResume2Magic = 0x524C5032U;  // "RLP2"
constexpr std::uint8_t kResume2Format = 1;
constexpr std::size_t kResume2SlotBytes = 96;
constexpr std::uint32_t kResume2MaxUses = 64;
constexpr std::uint32_t kResume2ReserveQuantum = 8;

struct ResumeSlot2 {
  bool valid{false};
  ResumePurpose purpose{ResumePurpose::Link};
  std::uint8_t flags{0};
  NodeId peer{kInvalidNodeId};
  NetworkId network{0};
  std::array<std::uint8_t, 8> peer_cert_id{};
  std::array<std::uint8_t, 8> local_cert_id{};
  std::uint32_t peer_generation{0};
  std::uint32_t peer_role{0};
  std::uint32_t created_gk_epoch{0};
  std::uint32_t last_used_boot{0};
  std::uint32_t reserved_uses{0};
  std::array<std::uint8_t, 32> rms{};
};

Status resume2_validate(const ResumeSlot2& slot) noexcept;
Status resume2_slot_encode(const ResumeSlot2& slot,
                           std::array<std::uint8_t, kResume2SlotBytes>& out) noexcept;
// Strict decode. An empty record decodes with valid=false.
Status resume2_slot_decode(ByteView bytes, ResumeSlot2& out) noexcept;

// --- RLV1 --------------------------------------------------------------------
// Durable local-removal evidence (G-SEC P4 design §3.3, issue #60-2): a record
// of refusal, not permission. While one exists unresolved (Blocked, Cleaned
// within holdoff, torn, or unreadable) the node must not return to Member —
// not even across reboot. Fixed two keys (sequenced A/B like RLS1/RRS1);
// the RLS1 frozen layout is untouched.
//  0 u32 magic "RLV1" | 4 u16 format=1 | 6 u16 used_len=108 | 8 u32 schema=1
// 12 u32 seal | 16 u32 commit_seq
// 20 u64 local_node | 28 u64 site_id | 36 u64 network
// 44 u32 removed_generation | 48 u32 rs_epoch_floor | 52 u32 site_epoch_floor
// 56 u8 state (1 Blocked, 2 Cleaned) | 57 u8 cause | 58 u16 reserved=0
// 60 32B evidence_digest (SHA-256 of the verified removal object)
// 92 u32 rls_commit_seq (diagnostic) | 96 u32 boot_witness
// 100 u32 holdoff_ms | 104 u32 crc32
constexpr std::uint32_t kLocalRevocationMagic = 0x524C5631U;  // "RLV1"
constexpr std::uint32_t kLocalRevocationSealCommitted = 0x72564B31U;
constexpr std::size_t kLocalRevocationSlotBytes = 108;
constexpr std::size_t kLocalRevocationRecordLen = 108;
constexpr std::uint32_t kLocalRevocationHoldoffMs = 600000;  // 10 minutes

enum class LocalRevocationState : std::uint8_t { Blocked = 1, Cleaned = 2 };
enum class LocalRevocationCause : std::uint8_t {
  Rrs = 1,              // an accepted RRS1 set rejected this node
  Notice = 2,           // a verified RemovalNotice named this node
  LocalMaintenance = 3,  // physical maintenance revocation (dev)
};

struct LocalRevocationRecord {
  LocalRevocationState state{LocalRevocationState::Blocked};
  LocalRevocationCause cause{LocalRevocationCause::Rrs};
  NodeId local_node{kInvalidNodeId};
  std::uint64_t site_id{0};
  NetworkId network{0};
  std::uint32_t removed_generation{0};
  std::uint32_t rs_epoch_floor{0};
  std::uint32_t site_epoch_floor{0};
  std::array<std::uint8_t, 32> evidence_digest{};
  std::uint32_t rls_commit_seq{0};
  std::uint32_t boot_witness{0};
  std::uint32_t holdoff_ms{kLocalRevocationHoldoffMs};
};

Status local_revocation_validate(const LocalRevocationRecord& record) noexcept;
Status local_revocation_record_encode(const LocalRevocationRecord& record, std::uint32_t seal,
                                      std::uint32_t commit_seq,
                                      ByteBuffer<kLocalRevocationSlotBytes>& out) noexcept;
Status local_revocation_record_decode(ByteView record, LocalRevocationRecord& out,
                                      std::uint32_t* commit_seq = nullptr) noexcept;
// Structure-only gate for the dual-slot classifier (see above).
Status local_revocation_record_structure(ByteView record) noexcept;

}  // namespace routeloom::sdkv1
