/* Generated by tools/gen_manifest.py from protocol/manifest.json. Do not edit. */
#ifndef ROUTELOOM_VERSION_H
#define ROUTELOOM_VERSION_H

#define ROUTELOOM_SDK_VERSION "2.0.0-dev"
#define ROUTELOOM_SDK_VERSION_MAJOR 2
#define ROUTELOOM_SDK_VERSION_MINOR 0
#define ROUTELOOM_SDK_VERSION_PATCH 0

#define ROUTELOOM_CORE_C_ABI 2  /* Core C ABI */
#define ROUTELOOM_WIRE_MAJOR 2  /* Mesh wire major */
#define ROUTELOOM_WIRE_MINOR 0  /* Mesh wire minor */
#define ROUTELOOM_RLD1_VERSION 1  /* RLD1 carrier */
#define ROUTELOOM_RLD1_ZT_BODY 3  /* RLD1 ZeroTouch body */
#define ROUTELOOM_HOSTLINK_PROTOCOL 1  /* HostLink (RLU1) protocol */
#define ROUTELOOM_HOSTOPS_SCHEMA 1  /* HostOps schema */
#define ROUTELOOM_HOSTOPS_JOIN_RELAY_SCHEMA 2  /* HostOps join relay schema */
#define ROUTELOOM_AUTHORITY_ENVELOPE 1  /* AuthorityEnvelope */
#define ROUTELOOM_STORE_AUTHORITY_LEDGER 1  /* Authority ledger (device) */
#define ROUTELOOM_STORE_CONFIG_JOURNAL 1  /* Config journal (device) */
#define ROUTELOOM_STORE_POWER_IMAGE 1  /* Power image (device) */
#define ROUTELOOM_STORE_TRUST 1  /* RLT1 trust store (device) */
#define ROUTELOOM_STORE_CREDENTIAL 1  /* RLC1 device credential (device) */
#define ROUTELOOM_STORE_SDKV1_FORMAT 1  /* SDK v1 records RLI1/RLS1/RRS1/RLP1 format */
#define ROUTELOOM_STORE_SDKV1_SCHEMA 1  /* SDK v1 records schema */

#define ROUTELOOM_REASON_NONE 0

#endif /* ROUTELOOM_VERSION_H */
